### ISSUE TITLE
Do the zoom and drag behaviors need to cancel click events?

### ISSUE THREAD

**Issue by ansis** [d3/d3#1005]
https://github.com/mbostock/d3/blob/master/src/behavior/zoom.js#L113-L118
It cancels the first click event after the drag, the one assumed to be created by the drag. Is there any reason it needs to be cancelled? Could leaving the click event cause trouble?

It also seems to cause problems with Opera, which doesn't trigger click events for drags, which could be an Opera bug or an accepted inconsistency (not sure yet). Ran into that at systemed/iD#357

**Comment by airandfingers** [comment]
I've observed inconsistent behavior with v3.5.8 in Chrome, as have others in the comments at http://stackoverflow.com/a/19951105/877682.

I don't see this behavior with simple examples like http://jsfiddle.net/2EqA3/3, leading me to believe that the inconsistency has to do with our draggable nodes, which are complex, comprising multiple path and text elements

I've worked around the problem by changing d3: when dragRestore doesn't check if d3.event.target === target, this issue goes away for me. I haven't observed side effects caused by this, but I don't understand the code well enough to know what to test. https://github.com/mbostock/d3/commit/a8de36bd85cecafbc76f6e4c7e5d80b9b280b500

**Comment by mbostock** [comment]
The issue you are seeing is indeed related to draggable nodes with multiple elements. See #312 and specifically @jasondavies’ comment:

> The problem is that the browser only fires a click event if mousedown and mouseup occur on the same element. So if you have a mousedown occurring on one element, and then mouseup on another, no click event is fired. This could happen in a number of ways e.g. if you clamped the dragged element and mouseup occurred outside the clamp region.
> 
> We had mistakenly assumed that a click event is always fired after mousedown + mouseup, so we always cancelled the next click event. In the original bug report, the OP found that he had to double-click on links after dragging a different element, because the next click was always being cancelled. We only want to cancel the click if it is actually going to be fired as a result of the mousedown + mouseup combination, which isn't always the case.

That said, it looks like we don’t need this sanity-check since we added the 0ms timeout, which automatically expires click suppression if a click event doesn’t immediately fire. In other words, since we only suppress an *immediate* click event, we don’t have to worry about false positives due to inconsistent browser behavior. (Before the 0ms-timeout, the click could be suppressed indefinitely!)

So, I’d be okay with removing target checks and relying on the timeout for click suppression.

**Comment by airandfingers** [comment]
Great, thanks for the context and fix!
