### ISSUE TITLE
Subticks division not available when there is just one major tick

### ISSUE THREAD

**Issue by danse** [d3/d3#1115]
Hello, I have a chart showing data from two weeks, with a major tick for each week and a minor tick for each day.

I implemented this using:

```
xAxis.ticks(d3.time.weeks).tickSubdivide(6);
```

I was surprised in finding today the minor ticks disappearing. This was due to the time interval coming with the data, which you can understand looking the attached screenshot.

![Screenshot from 2013-03-04 11:13:28](https://f.cloud.github.com/assets/885935/216098/68160280-84b4-11e2-959b-1fe00cf14781.png)

Days and day numbers are not ticks, they are added by extra code. The subticks, here, should be vertical lines similar to the week major tick. In this case, there is one start tick, one end tick, and just one major tick. I discovered with the debugger that in this case, the `d3_svg_axisSubdivide` function inside `svg/axis.js` does not compute any subtick, because ticks.length is not greater then one.

Before trying to add some tests to `svg/axis-test.js` and to fix the problem, I wanted to have some comments from you. Thanks!

**Comment by AaronSikes** [comment]
Sorry for commenting in an old closed issue. Found this because http://bl.ocks.org/mbostock/1166403 is linked from the first google result for 'd3 axis'.
Just wanted to say something that completely removes functionality should probably be considered a breaking change. If someone upgrades d3 and all the ticks disappear from their graph, that's a breakage. Even though it doesn't throw an error, it breaks apps
