### ISSUE TITLE
Omit .0 precision with d3.format() ?

### ISSUE THREAD

**Issue by micha149** [d3/d3#1152]
Hey.

I try to format an percentage value using d3.format(). I want to print a precision of one single digit but not, if this digit is 0. Example:

```
var total      = 100,
    percentage = d3.format('.1%);

percentage(12.3456 / total); // outputs the expected 12.3% 
percentage(75 / total); // should return 75%
```

What format string is necessary for this behavior?

**Comment by richiepreece** [comment]
@mbostock Quick thought here.

We're running into an issue where we are formatting with `.3s`, but when the number is less than 0, we get outputs such as `0.500`, `0.020` etc.

As per your statement above, it's best to have numbers line up, but we get:

`120`
`12.0`
`1.20`
`0.120`

Which ruins the aesthetic. Is there a good way to trim either the leading or trailing 0? Or are we simply in a situation where we need to`substr` the result from `.format` ourselves?

**Comment by mbostock** [comment]
The `s` [format type](https://github.com/d3/d3-format#locale_format) is for decimal notation with an SI prefix, rounded to significant digits. So what you describe is the expected behavior. The leading zero does not count as a significant digit, and the presence or absence of the leading zero, the decimal separator, and the SI prefix can cause the resulting string to have variable length.

If you want the strings to have the same length, you might want to specify a width in addition to a precision. For example, `4.3s` will right-align and fill with spaces, resulting in:

```
 120
12.0
1.20
120m
```

Or with `5.3g`, to use significant digits but without the SI prefix:

```
  120
 12.0
 1.20
0.120
```

You can also use `4.3` to trim the insignificant trailing zeros:

```
 120
  12
 1.2
0.12
```

I suggest reviewing the documentation:

https://github.com/d3/d3-format#locale_format

Of course you can also post-process the string returned by a format to modify it however you like if the built-in format types aren’t doing it for you.

More generally, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by jasonmerry** [comment]
Having come across this today and trying all the different combinations of 'format type' Mike suggested I ended up using parseFloat on the final value.

Worked a treat.

I get my values as I want with the decimal point precision I require and no unwanted .0 or .00 or even .50.

`var percent = d3.format('.1f');
  parseFloat(percent(value));`

(My code isn't set up for using the percent format type hence it not being used here. I don't know if it would work with parseFloat?)

**Comment by mbostock** [comment]
The *none* format type trims trailing zeros, but the precision is interpreted as significant digits rather than the number of digits past the decimal point. There isn’t a variant of `f` that trims trailing zeros, but this is the default behavior of JavaScript number formatting ([*number*.toString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString)) so you might not even need d3-format.

Here’s using *number*.toString, [*number*.toFixed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed), and unary `+` (instead of [parseFloat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat)), to round a number to the specified precision.

```js
function formatFixed(x) {
  return +(+x).toFixed(1) + "";
}

formatFixed(12.3456); // "12.3"
formatFixed(75); // "75"
```

Or broken down:

```js
function formatFixed(x) {
  x = +x; // Coerce x to a number if it isn’t already.
  x = x.toFixed(1); // Format x as a string with 1 decimal place.
  x = +x; // Coerce x back to a number.
  x = x + ""; // Format x as a string using the default behavior.
  return x;
}
```
