### ISSUE TITLE
Fuller's Dymaxion projection, how hard would be implementing?

### ISSUE THREAD

**Issue by ghost** [d3/d3#1209]
hi!

i see that d3 supports a lot of useful world map projections, but i think i can't find Bucky Fuller's Dymaxion projection - http://en.wikipedia.org/wiki/Dymaxion_projection - http://en.wikipedia.org/wiki/File:Map-of-human-migrations.jpg

i don't know how hard is to implement it, but would be really awesome, and useful for some situations (like worldwide transportation, migration, etc.)

thanks and cheers,
p.

**Comment by jgladch** [comment]
Can we reopen this? Still no projection :(

**Comment by pierrebrt** [comment]
Yes please <3

**Comment by curran** [comment]
It has been implemented, see https://github.com/d3/d3-geo-projection/issues/25

The problem is that the Fuller Institute has placed licensing restrictions on the whole concept of the "Dymaxion Projection" that are incompatible with the BSD License, so it's a social problem not a technical problem that's preventing this projection from being added to D3.

**Comment by jgladch** [comment]
Damn... That's the least Buckminster Fuller thing ever... Copyrights
preventing his ideas from being used more widely....

**Comment by Fil** [comment]
@curran I'm not a lawyer but I've checked the restrictions and my understanding is that:

- the patent awarded in 1946 has expired after 20 years

- there should be no copyright on the projection itself

- the BFI (Buckminster Fuller Institute) claims [on their site](https://www.bfi.org/about-fuller/big-ideas/dymaxion-world/dymaxion-map) to have registered some trademarks: “The word *Dymaxion*, *Spaceship Earth* and the *Fuller Projection Map* are trademarks of the Buckminster Fuller Institute.” 

I checked on [TESS](https://www.uspto.gov/trademark) the trademarks owned by the BFI, and currently they are limited to "SPACESHIP EARTH" "WORLD GAME" and "FLY'S EYE DOME" and "GLOBAL ISSUES NETWORK". Some other companies have claimed the names “DYMAXION“ and “BUCKMINSTER FULLER”, but they seem unrelated.

So where does this leave us? I'm 99.9% confident anyone is free to do this projection and use it as they want. If we want to be extra careful we can _brand_ that projection by some other name that those claimed on the BFI site and those found in TESS (which do not match…).

“Buckminster Fuller's Dymaxion projection 1946“ is probably OK, and “Buckminster Fuller's projection 1946” is without a doubt OK. If we're totally paranoid about this we can also brand it “Constant Zenith Projection”.

But before that we need some code :)

**Comment by jgladch** [comment]
Here here!

**Comment by curran** [comment]
@jgladch Right?! (re: least BuckminsterFuller thing ever)

@Fil That's great information! A few months ago I had a few email exchanges that are relevant to this discussion.

I emailed the original author of the C implementation, Robert Gray, asking his permission to include the JS port of his C implementation of the projection in D3. His response:

>The Dymaxion map layout, I think, is copyrighted by the Buckminster Fuller Institute or the Estate of Buckminster Fuller.  I would send an email to the Buckminster Fuller Institute and ask them.  If they grant permission, then I wouldn't have any problem with someone using my code, or a variation of it.  But I don't own the copyrights to the map layout.

So I sent an email to the Buckminster Fuller Institute asking for clarification on the copyright of the projection and asking if we could include an implementation of it in D3. Their response:

>Thank you for your interest in the Fuller Projection Map™. BFI owns the rights to the projection, and yes, it requires a licensing agreement for use. 
> ...
>I would need to get permission from our Board and determine if there would be a fee for use. There will certainly be credit information that will need to be included somewhere on the site and below the projection to ensure that users understand that any use of the map projections for consumer or public use would require a licensing agreement with BFI. 

So ... I'm not sure what they mean by "rights to the projection" - is it the math? is it the name? I'm not sure where that leaves us.

I really want to see the projection JS implementation packaged nicely and released, but it feels a bit unethical as the original author, Robert Gray, said it's fine as long as BFI grants permission, but the tone of the BFI response is not exactly granting permission.

I wonder if I could do anything more to follow up. Maybe I could ask the BFI folks to cite a copyright/patent registration that states that they own the "rights to the projection" (and mention that 20 years has passed since the patent was granted)?

**Comment by curran** [comment]
@Fil 
>But before that we need some code :)

The code is here: https://github.com/mbostock/protovis/blob/gh-pages/ex/dymax.js

Here's an example that uses it: https://github.com/mbostock/protovis/blob/gh-pages/ex/dymax.html

I also made a Gist in case the above links break for some reason https://gist.github.com/curran/798f862e23d598fe52bb9749165cd939

**Comment by jgladch** [comment]
I also have a working version up at theworldpeacegame.herokuapp.com 👍🤘

**Comment by Fil** [comment]
Robert Gray's copyright is a different story.
“Copyrights subsist for the author’s life plus 50 years after the author’s death or, in the case of works made for hire, 75 years from the year of first publication.”
Fortunately “Copyright protects against copying, but not against independent development.”

In summary the maths is free to use, but not this code. If we want to freely distribute a port of Robert Gray's code, we need his authorization at least for 150 years (wishing him well). So either ask for the BFI's yeah so that Gray can yeah it too, or write an independent implementation.

**Comment by curran** [comment]
Robert Gray sounded generally OK with us using his code if it's legal with respect to BFI, and he did respond to my email way back when. Maybe I could contact him again and request that he release his C code under BSD so we can release the JS port also under BSD.
