### ISSUE TITLE
Force Layout tick without d3.timer

### ISSUE THREAD

**Issue by tmcw** [d3/d3#1283]
So, I'm interested in using d3's force layout headlessly - but with manually calling tick rather than having it run on a timer. Right now the `.alpha()` method is coupled to animation and it's not really possible to have it both ways - to have alpha set to an animating value but not have the timer firing.

Could these APIs be decoupled somehow? Or is there a workaround I'm missing? Thanks!

**Comment by SpencerCarstens** [comment]
Sorry for resurrecting an old post.

Is there any downside when checking against the current `.alpha()` value instead of a fixed `n` like your example? I dug around the docs and couldn't find one, nor did my benchmarks show a big difference, but wanted to make sure since you specifically suggested one way.

Perhaps a combination?

Thanks!

```
function calculateLayout( alpha, max ) {
    alpha = alpha || 0;
    max = max || 1000;
    var i = 0;
    while ( force.alpha() > alpha && i++ < max ) {
        force.tick();
    }
}
```
