### ISSUE TITLE
The zoom behavior should support pointer events.

### ISSUE THREAD

**Issue by Ta4i** [d3/d3#1439]
Users of Win 8 on touch devices which use IE 10 are disable to zoom in D3 using gestures. It's because in IE there are different gestures model.

Description of Pointer concept:
http://msdn.microsoft.com/en-us/library/ie/hh673557(v=vs.85).aspx http://github.com

Existing approaches of unifying events:
http://blogs.msdn.com/b/eternalcoding/archive/2013/01/16/hand-js-a-polyfill-for-supporting-pointer-events-on-every-browser.aspx

> Back in September 2012, Microsoft proposed a specification to W3C
> for unifying touch, pen and mouse events called Pointer Events
> and based on the APIs available today in IE10 on Windows 8.
> The W3C has since created a new Working Group which already published
> a last call draft.The Microsoft Open Technologies, Inc. team has also released
> a Pointer Events initial prototype for Webkit on HTML5Labs to further contribute
> to the technical discussions in the W3C Pointer Events Working Group. 

So seems like "Pointer" is upcoming standard (at least it's make sense). So it'll be cool to start support this model. Or just add ability to perform zooming by MSGesture.

**Comment by natevw** [comment]
xref: https://github.com/mbostock/d3/issues/2380

**Comment by bwestpha** [comment]
hey @mbostock :)

Since this is a very old request / topic, are there any new information about it? 
It's because Windows tablets are really popular and quite common in big companys and there is no fix for zooming with an MS tablet ?!
Is there any reason why this was going to the icebox?



### (and also, just a question by the way: is there any option / tutorial / code snippet, which makes the tooltips useable with an MS touch device? )

**Comment by Herst** [comment]
Touch events are in Edge but disabled per default and the setting hidden at **about:flags**. With this activated zooming in works but zooming out does not. All-in-all the situation is inadequate.

For what it's worth, here is a simple demo of how to support the pinch zooming gesture for triggering a d3 zoom (not the browser gesture for doing page zooming): <https://mdn.github.io/dom-examples/pointerevents/Pinch_zoom_gestures.html>
Maybe I find time for hacking support for this into d3 because pinch-zooming is the only thing in my project which does not work on touch-enabled devices with Windows (at least if they have keyboards, according to some voice on the web it makes a difference).

Currently, I am not very motivated to do so though because in MS Edge 16 (Fall Creators Update from few days ago) the renderer process stops working when zooming or programmatically panning on my page (page randomly freezes and reloads, after some reloads a "This page is having a problem reloading" message pops up. This happens when doing programmatic resizing as well, if anyone else has the problem with a d3-related page please tell me so we can report it to Microsoft).
