### ISSUE TITLE
d3.geo.clipExtent doesn’t preserve polygon semantics of geometry stream.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#1558]
Jason and I were debugging a [winding order issue](http://bl.ocks.org/mbostock/0e46bdc044a82aa0ee0b) and uncovered an interesting issue in d3.geo.clipExtent: although it outputs the rings in the correct winding order, it does not properly group exterior rings and interior rings using stream.polygonStart & stream.polygonEnd. For example, if you have an exterior ring that is split into two exterior rings, this should be represented as:

stream.polygonStart
stream.lineStart
stream.point …
stream.lineEnd
stream.polygonEnd
stream.polygonStart
stream.lineStart
stream.point …
stream.lineEnd
stream.polygonEnd

Instead, the clipExtent outputs:

stream.polygonStart
stream.lineStart
stream.point …
stream.lineEnd
stream.lineStart
stream.point …
stream.lineEnd
stream.polygonEnd

Since the additional polygonEnd / polygonStart is missing, stream listeners might assume that the second line is an interior ring (a hole) rather than the second exterior ring of a multipolygon.

**Comment by rasmuse** [comment]
Bumping an old thread here. Many thanks for a great library.

If I understand things correctly, there is still a mismatch between the implementation and the docs on this point.

As of v1.2.3, the [docs](https://github.com/d3/d3-geo/blob/v1.2.3/README.md#stream_lineStart) say that *"[t]he first ring of a polygon is the exterior ring, and is typically clockwise"* etc. However, the [implementation](https://github.com/d3/d3-geo/blob/v1.2.3/src/stream.js) does not seem to do so. I guess @mbostock's proposed solution (updating the docs to say that order is undefined) still works.

Or has this issue been fixed in some other way in d3 v4?

**Comment by mbostock** [comment]
@rasmuse The docs you linked describe the *stream* interface and are correct. d3.geoStream does not implement the stream interface: it streams a geometry object to something that implements the *stream* interface, such as a projection. (See the [implementation of d3.geoPath](https://github.com/d3/d3-geo/blob/master/src/path/index.js#L19) for example usage of d3.geoStream.) This issue describes a bug specifically in d3.geoClipExtent, which does not preserve the polygon semantics of the stream as described in the top post. This is neither a bug in the documentation of the stream interface or in d3.geoStream but in d3.geoClipExtent.

**Comment by rasmuse** [comment]
Thanks for the clarification. That makes perfect sense.
