### ISSUE TITLE
Something wrong with the http://d3js.org/d3.v3.min.js package

### ISSUE THREAD

**Issue by kevinsigwart** [d3/d3#1693]
All of sudden all my applications that reference  http://d3js.org/d3.v3.min.js broke.  I'm getting a d3 reference not found error.  When I go to the downloaded version, that I downloaded a month or two ago, everything works fine.  Was there some new push that came out sometime this past week or two?

Thanks!

**Comment by JohnGilmore100** [comment]
Is there a way to connect to 

HTTPS:://d3js.org/d3.v3.min.js  

as opposed to HTTP://d3js.org/d3.v3.min.js ?

**Comment by JohnGilmore100** [comment]
Connecting to: HTTP://d3js.org/d3.v3.min.js  is OK

Where can I find a link to HTTPS:://d3js.org/d3.v3.min.js ?

**Comment by cliveb** [comment]
Can't remember how I solved or hacked a d3 solution
http://navigator.xclimatechange.com/
Answer may be in the code https://github.com/cliveb/Gigaimpacts

Browser Vendors enforcing https over http notching up security for web
components keeps us on our toes.



--
clive || http://about.me/cliveboulton

**Comment by cliveb** [comment]
I asked a Googler on Chrome Polymer/Web team how to solve this.

Polymer/Web Components don't have anything to do with security. Imports
behave no differently then trying to pull in JS from a different domain. If
you're getting errors in your console about linking to assets on different
domains then it may be because they haven't enabled CORS headers. The
easiest solution would be to serve the library from your own domain.

As for creating a custom element that uses d3, that should be fine.

--
clive || http://about.me/cliveboulton

**Comment by mbostock** [comment]
Unfortunately, I haven’t yet setup HTTPS when using custom domains over GitHub Pages—I need to signup for Cloudflare or something similar. In the meantime, I recommend using a CDN that supports HTTPS, such as CDNJS:

https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js

**Comment by JohnGilmore100** [comment]
Thanks all.

Mike - same feedback: 
* cloudflare: the latency seems to be OK, downloads reliable.
* I would like to suggest to you to also consider deploying d3 in https://ajax.googleapis.com

**Comment by DatamineAnalytics** [comment]
This may or may not be related, but when developing on the file system in firefox (i.e. not using http-server or the like) the following (as recommended by https://d3js.org/) does not work for me:

    <script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>

However, using the following 

    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>

does work. @mbostock, is the exclusion of the `http:` from the recommendation on https://d3js.org/ intentional? If not, it might be helpful for a large number of users to add it in.

**Comment by ianhoolihan** [comment]
This may or may not be related, but when developing on the file system in firefox (i.e. not using http-server or the like) the following (as recommended by https://d3js.org/) does not work for me:

    <script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>

However, using the following

    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>

does work. @mbostock, is the exclusion of the http: from the recommendation on https://d3js.org/ intentional? If not, it might be helpful for a large number of users to add it in.

**Comment by mbostock** [comment]
The `//` is a protocol-less URL, so it inherits the protocol of the hosting page. That means if won’t work if the hosting page is `file:///…`.

**Comment by ianhoolihan** [comment]
Thanks. Would it make sense to prefix `http:` to the recommendation, as it'll possibly benefit all of the non-URL-savvy `file:///` users (like myself), without harming any others?

**Comment by mbostock** [comment]
Sure, I’ve updated d3js.org and the wiki to recommend HTTPS.
