### ISSUE TITLE
Allow nodeSize for trees to be dynamic [request]

### ISSUE THREAD

**Issue by Bertg** [d3/d3#1992]
In ticket #317 nodeSize for hierarchical layouts was introduced. 
I love this feature.

I was wondering could this be made dynamic, different sizes for different nodes?

I'm not to good with the entire layout engine, but I'd be happy to be useful where I can.

**Comment by CaitlinWeb** [comment]
+1 This would be amazing! D3 shouldn't be restricted to circular or locational shapes for all the cool things it can do--it could use regular divs, which are rectangular and dynamically sized. 

I have been struggling with making a tree layout work with divs, so I could really use an auto-nodeSize. (Best solution would be hierarchical layouts detect the size of each node and adjust accordingly--not sure how feasible that is, though.)

**Comment by maheshsenni** [comment]
+1 for this feature. I am not sure whether the algorithm used for tree layout, Reingold–Tilford “tidy” algorithm can be extended to support variable sized nodes.

**Comment by Bertg** [comment]
@maheshsenni I'm far from a Math wiz but [this paper on the subject](http://oai.cwi.nl/oai/asset/21856/21856B.pdf) seems to cover nodes of any shape and form.

**Comment by Klortho** [comment]
Hey, I just found this issue. I've been working on this for the past week or so, and I think I'm pretty close.  See [this demo](http://klortho.github.io/d3-flextree/).

I'm new to D3, so any code review would be fantastic. I started out writing it as a plugin, but then switched to try to modify layout/tree in the main library, with the idea that I'll submit it as a PR.  I'm working in [this branch](https://github.com/klortho/d3/tree/flextree).

I suspect that it would take a long time to get it accepted as a PR, so I think I can write a quick awk/sed script to pull out the needed pieces and create it as a plugin, as well.

I hadn't seen that paper, @bertg, I will check it out now.  I actually came up with my own modification to the "tidy" algorithm, that I describe in the comments, [here](https://github.com/Klortho/d3/blob/c402ed868d8f413d7f3ca6cb09a560a00d2ccbf9/src/layout/tree.js#L201). It still runs in linear time -- I'm very curious to see how it compares with what's in the paper. (And a little bummed that the paper exists -- I was thinking maybe I'd be able to publish!)

My to-do list is [here](https://github.com/Klortho/d3-flextree).  I hope to be able to finish in the next couple of days. Since I'm submitting it as a PR, I want to test the hell out of it.

**Comment by Klortho** [comment]
The difficulty I'm working on now is the separation function. The way it's defined now, it returns value for x, that is scaled to the fixed node size. So 1 means to separate the nodes 1 "node unit" apart. This is true whether or not size() or nodeSize() is used to size.

But if nodeSize() is variable, then what is a "node unit"? Intuitively, I think we'd want nodeSize() and separation() to return values in the same scale, but that would break backward-compatibility.

So I'm thinking of introducing a new configuration function, maybe named "margin" (but that's not quite right), that  is only used in the variable nodeSize case.

In summary, if you're using:

* size (which is the default) - separation() determines the x-coordinate placement, in arbitrary units (they are scaled to the size of the drawing at the end)
* fixed nodeSize - separation() determines x-coord, in units of the fixed nodeSize x value.
* variable nodeSize - margin() determines x-coord, in the same units as are returned by the nodeSize function.

margin() would behave a little bit differently, too. It would really determine the spacing between the edges of the nodes. In the existing tree implementation, there isn't really a concept of an x-size of a node - separation() determines distances center-to-center.

Thoughts?

**Comment by Klortho** [comment]
I finally finished this, see [this pull request](https://github.com/mbostock/d3/pull/2571) and [this plugin](https://github.com/klortho/d3-flextree).

I hope you guys who expressed interest in this get a chance to check it out, and please let me  know what you think!
