### ISSUE TITLE
Allow variable branch lengths in tree layout

### ISSUE THREAD

**Issue by jdidion** [d3/d3#213]
I would love to use D3 for creating phylogenetic trees. A phylogenetic tree is basically a hierarchical tree where each node specifies its distance from its parent, and this distance must be reflected by the length of the branch. If there is currently a way to do this with D3, I can't figure it out.

As a side note, the standard format for phylogenetic trees is Newick (http://en.wikipedia.org/wiki/Newick_format). I would be happy to write a function to transform a Newick tree to an appropriate JSON object that could then be used with D3. This would open up D3 to be used by the bioinformatics community and possibly get you some citations in scientific publications when people create trees using D3.

**Comment by Chris-Eisenhart** [comment]
Hmm this seems to be implemented with the d3 heirarchy class 'cluster' not the d3 heirarchy class 'tree'.  I am trying to do variable link lengths on the 'tree' layout, any suggestions?

**Comment by mbostock** [comment]
Here’s a newer example using the cluster layout:

[![screen shot 2015-11-30 at 2 38 17 pm](https://cloud.githubusercontent.com/assets/230541/11486762/0729b4fe-9770-11e5-8edd-f3ed1e847ac0.png)](http://bl.ocks.org/mbostock/c034d66572fd6bd6815a)

You can’t apply the same strategy with the “tidy” tree layout because that algorithm assumes that the tree is layered (i.e., each node at a given depth in the tree shares the same *y*-position in the resulting layout). See #2571 and [d3-flextree](https://github.com/klortho/d3-flextree) for an implementation of a non-layered trees, as in [Drawing Non-layered Tidy Trees in Linear Time](http://oai.cwi.nl/oai/asset/21856/21856B.pdf) by A.J. van der Ploeg.
