### ISSUE TITLE
"Let's make a map" clarification and bubble map typo.

### ISSUE THREAD

**Issue by ClashTheBunny** [d3/d3#2149]
On Let's make a map, it's not entirely clear where path.pointRadius should be added.  I ended up finding it in the step-6.html, but I couldn't figure it out from the linked documentation.  Just starting out though, so it may be that I'm just doing things in the wrong order.  I first tried doing it with CSS, and then I tried adding it various places near the creation of the points.  Either way, great tutorial.  It's so wonderful to have such a powerful library as d3.

There is also a typo on http://bost.ocks.org/mike/bubble-map/.

The Makefile has a space between -- and countries:

```
        -- counties=$<
```

it should be

```
        --counties=$<
```

Once again, thanks so much for making the web a better place, a place where it is easier to tell the truth and harder to deceive.  It's easy for me to mis missing justification in text, but it's harder when it's in a picture.

**Comment by roderickm** [comment]
I ran across this same problem. Topojson is perturbed by backslash-newlines that make passes due to the multi-line single-quoted string for the projection options. To resolve the trouble, join the projection options into a long single-quoted line:

        --projection='width = 960, height = 600, d3.geo.albersUsa() .scale(1280) .translate([width / 2, height / 2])' \

or wrap it in double quotes instead:

        --projection="width = 960, height = 600, d3.geo.albersUsa() \
                .scale(1280) \
                .translate([width / 2, height / 2])" \

or put the single-quoted, multi-line projection string into a make variable and then use the variable in the recipe as discussed in [Splitting Recipe Lines  with GNU Make](https://www.gnu.org/software/make/manual/html_node/Splitting-Recipe-Lines.html).

**Comment by atonb117** [comment]
Thanks for that @roderickm!
