### ISSUE TITLE
D3 Symbols radius accessor

### ISSUE THREAD

**Issue by bluong** [d3/d3#2250]
For D3 Symbols, currently the only way to set the size of a symbol is through the size accessor.  However we encountered that we much rather set the size of the symbol through the radius, since the size by itself is essentially the area of the constructed path, and one cannot know the dimensions of the path with just the area value.

We were wondering if there can be some form of radius accessor that can allow us to enforce a boundary box around the symbol so that we know the dimensions of the symbol?

**Comment by mbostock** [comment]
There could be, but the emphasis on size was intentional given that for visualization, we want the size of symbols to be proportional to the encoded value (rather than the square of the value, as would be the case if you naïvely mapped value to symbol radius).

You can use [element.getBBox](http://www.w3.org/TR/SVG/types.html#__svg__SVGLocatable__getBBox) to retrieve the computed bounding box of any SVG element. So one option to do this yourself is to make a first guess at the size, and then scale it to fit your desired bounding box:

```js
path.attr("d", symbol.size(64));
var error = Math.min(width / box.width, height / box.height);
path.attr("d", symbol.size(error * error * 64));
```

See [bl.ocks.org/3dd515e692504c92ab65](http://bl.ocks.org/mbostock/3dd515e692504c92ab65).
