### ISSUE TITLE
The classed operator should allow a single function parameter

### ISSUE THREAD

**Issue by NeonGraal** [d3/d3#2254]
This function would be called for each selection node similarly to the classed(string, function) variant, but the function would then return an object containing classname: truthy combinations to set/remove classes.

This allows the following code (from the clustered dependencies example):

  d3.selectAll('.node')
    .classed('target', function(n) { return n.target; })
    .classed('source', function(n) { return n.source; });

to be improved to:

  d3.selectAll('.node')
    .classed(function(n) { return { 'target': n.target, 'source': n.source}; });

**Comment by nhduc296** [comment]
I think this is a good idea, hope it available in 4.0

**Comment by mindrones** [comment]
+1!
Very often I start writing it exactly like you are proposing, just to remember it's not supposed to be used like that :)
Also, would it be more efficient than calling a function for each class we want to add?

**Comment by mgold** [comment]
I'm ambivalent about the proposal, but it would allow
````js
sel.classed("foo", function(d){return d.bool})
   .classed("bar", function(d){return !d.bool})
````
to be tightened into
````js
sel.classed(function(d){return d.bool ? "foo" : "bar"})
````
I'm not sure how often I encounter this pattern, however.

**Comment by mindrones** [comment]
I often want to toggle groups of classes; like, for a certain value of `d`, I want the element to be classed `higlighted`, `unclickable`, `pulsing`, `fixed` and for other values of `d` I want it `normal`, `floating`, `draggable`.

In this case, instead of this form:

    sel
    .classed('higlighted', function(d){ return d.foo })
    .classed('unclickable', function(d){ return d.bar })
    .classed('pulsing', function(d){ return d.foo })
    .classed('fixed', function(d){ return d.bar })
    .classed('normal', function(d){ return !d.foo })
    .classed('floating', function(d){ return !d.foo })
    .classed('draggable', function(d){ return !d.bar })

you could use this one, which is much more readable:

    sel.classed(function(d){
      return {
        higlighted: d.foo,
        unclickable: d.bar,
        pulsing: d.foo,
        fixed: d.bar,
        normal: !d.foo,
        floating: !d.foo,
        draggable: !d.bar,
      }
    })

**Comment by mindrones** [comment]
Also, if this gets accepted then it should also be possible to do:

    sel.attr(function(d, i) { return { foo: d.foo, bar: d.bar } })

**Comment by mindrones** [comment]
Just noticed that in #277 @mbostock mentions that this could be supported in 4.0 using `selection.attrs` ([here](https://github.com/mbostock/d3/pull/277#issuecomment-99571025))

**Comment by mbostock** [comment]
My current plan for 4.0 is that multi-value map methods should be distinct rather than using argument overloading. So, instead of passing a map to selection.attr, you call selection.attrs. The nice thing about this approach is you can either pass a map of functions (or a map of constants) or a function that returns a map (of constants).

For toggling classes, the methods would be selection.class and selection.classes, respectively. Well, or we stick with selection.classed and selection.classeds, but that’s a bit of an awkward name.

**Comment by mindrones** [comment]
+1 for distinct methods and `class`/`classes`!

It would be useful to have `selection.classes()` to return a list of class names (`['foo', 'bar', 'baz']`), as a substitute for calling `selection.attr('class')`, which returns a string of class names that we have to process anyway.

**Comment by Haikane** [comment]
+1 This helps a lot.

**Comment by kvcrawford** [comment]
I ran into the use-case @mindrones described. For me, the logic to that determined the classes was closely related, and I wanted to execute it all just 1 time in 1 function, rather than a function for each class.

Using `selection.each` + `d3.select(this)` works decently well enough:

```js
let lines = this.foreground.selectAll('.lines')
  .each(function(d) {
    d3.select(this).classed({
      higlighted: d.foo,
      unclickable: d.bar,
      pulsing: d.foo,
      fixed: d.bar,
      normal: !d.foo,
      floating: !d.foo,
      draggable: !d.bar,
    })
  })
```
