### ISSUE TITLE
Request for time zone support in d3.time.scale

### ISSUE THREAD

**Issue by caleeky** [d3/d3#2375]
By default, d3.time.scale uses the browser's local timezone, presumably as a side effect of using Javascript Date objects. It is a common requirement for visualizations to use a specified time zone, which may differ from the browser's local time zone. 

Workarounds found online, as of the date that this issue is being filed, focus on replacing parts of D3 functionality, or fudging input data to "re-imagine" it happening in UTC or in the browser's local time. These workarounds are complex.

D3's time scale should be configurable to use a specified time zone, so that when ms-since-unix-epoch are rendered, and when tick locations are created, this would done directly and appropriately. This functionality seems to be within the intended scope of the time scale's purpose and architectural context, and is only limited by the lack of good time zone support in Javascript.

Perhaps an optional dependency on moment/timezone.js would be reasonable? Perhaps an independent implementation of the time scale?

Thanks!
Mat

**Comment by caleeky** [comment]
To add a clarification - it is recognised that the formatting of time values is user-controllable. The main issue seems to be in the alignment of automatic interval ticks to a specified time zone.

As per https://github.com/mbostock/d3/wiki/Time-Intervals this issue is recognised as a desirable enhancement. 

"Local time is determined by the browser's JavaScript runtime; arbitrary time zone support would be nice, but requires access to the Olson zoneinfo files." 

Perhaps this issue (2375) should be adjusted to describe time zone support in a broader context than d3.time.scale.

**Comment by mtrias** [comment]
I'm facing this exact issue now.

As a workaround i'm using a custom formatter function that computes the formatted label, taking the timezone in account.

The problem with this approach is that the position of the ticks is pretty when using the browser's timezone, but not when using another timezone. For instance, this nicely formatted ticks:

![image](https://cloud.githubusercontent.com/assets/801752/8416062/68735802-1e79-11e5-932b-01988867761c.png)

turn into this after using my mentioned patch on a timezone with an offset of -3 hours.

![image](https://cloud.githubusercontent.com/assets/801752/8416072/7efc1dd4-1e79-11e5-96bd-35de1be7d06b.png)

This happens because the ticks don't fall in the correct locations for the converted timezone:

The workaround i would like to implement, would be to move the generated ticks by a number of hours determined by the timezone offset. But to do this i'd need a way to get those ticks generated by d3.

Is there a way to do this?

**Comment by mbostock** [comment]
In theory, you should be able to do this in 4.0 by creating your own [custom time interval](https://github.com/d3/d3-time#interval), and then passing that to [time.ticks](https://github.com/d3/d3-scale#time_ticks). You’d need to roll your own tick format, too, but it should be possible to use d3-time-format if you pass in a Date-like object that returns the appropriate values for local time methods, such as date.getHours.

It might be worth trying this approach with [TimezoneJS.Date](https://github.com/mde/timezone-js)…

**Comment by gtb104** [comment]
Are there any suggestions or examples on how to create a custom time interval?

**Comment by mbostock** [comment]
@gtb104 Take a look at how the standard time intervals are implemented, such as [d3.timeDay](https://github.com/d3/d3-time/blob/master/src/day.js).

**Comment by gtb104** [comment]
So I see that this was assigned the milestone `Icebox`. Does that mean it's not going to be worked? i.e. put on ice ;-)

If so, is creating your own time interval the best suggestion at the moment? Thanks!

**Comment by mbostock** [comment]
The icebox is the default state for any issue that hasn’t been touched in a while. There’s always a chance that I might work on something spontaneously, even if it’s on ice, but I don’t have any plans to here. Also, I think time zones are something I really want to stay away from—they are complicated, and it would be better to have more language support for them. And lastly, this would be tackled in [d3-time](https://github.com/d3/d3-time) (rather than here in d3, which represents just the default bundle and not the implementation), and as I said in earlier comments, you should be able to implement this using the existing functionality to define custom time intervals. So I’m going to close this issue.

**Comment by stevenleeg** [comment]
Did anyone ever come up with a solution or workaround to this bug? I'm running into the issue now and have been struggling to come up with an easy solution to getting axis ticks to be placed on day lines for arbitrary timezones (rather than just the user's).

**Comment by Pringels** [comment]
@stevenleeg here is my quick and dirty solution using Luxon:

```js
const customTimeZone = "Europe/Berlin"

const tickValuesForAxis = scale.ticks().map((d) => {
    const tzOffset = DateTime.fromJSDate(d).setZone(customTimeZone).offset; // minutes
    return new Date(t.getTime() - tzOffset * 60000);
});

// ...render axis with tickValuesForAxis
```
