### ISSUE TITLE
support for ordinal scales in d3.behavior.zoom.{x,y}

### ISSUE THREAD

**Issue by deanmalmgren** [d3/d3#2442]
I'm working on a project where the x- and y-axes are specified by a user and can be either linear or ordinal scales. d3.zoom works great with the linear scales [out of the box](http://bl.ocks.org/mbostock/3892919), but it requires a totally different approach if any of the scales are ordinal. It would be convenient if `d3.behavior.zoom` played nicely with ordinal scales and linear scales using the same functionality.

[Here's an example Stackoverflow question](http://stackoverflow.com/questions/22070367/d3-js-ordinal-scale-and-zoom-pan) that has a similar issue to what I'm facing. There's a good workaround solution, but it would be nice if the `d3.behavior.zoom.x` and `d3.behavior.zoom.y` methods automatically detected the use of ordinal scales.

I'd be happy to throw together a PR for this in the next few weeks, but before I do I thought I'd see if there was a design decision behind this functionality. I'd hate to dig into this issue only to realize there is an obvious problem with the approach that I'm missing. :)

**Comment by deanmalmgren** [comment]
After looking into this a bit more carefully using some unminified source, the error I'm getting is related to ordinal scales not having an `invert` function, which [is called here](https://github.com/mbostock/d3/blob/master/src/behavior/zoom.js#L171-L172). My current crappy little prototype for handling this in the `rescale` function looks something like this:

```javascript
      if (x1) {
          if (x1.rangeRoundBands) { // handle ordinal axes here
              x1.range(x0.range().map(function(x) {
                  return (x - view.x) * view.k
              }))
          }
          else { // handle non-ordinal axes here (current method)
              x1.domain(x0.range().map(function(x) {
                  return (x - view.x) / view.k;
              }).map(x0.invert));
          }
      }
```

This doesn't have the right behavior though and its somehow related to a misconception of what the `view` variable is supposed to entail. Since `rescale` is called when you pan and when you zoom, its proving to be a bit difficult to do the equivalent of an `x0.invert`. If you have any pointers on what `view` is supposed to be or any other suggestions for how to implement this, I'd love some pointers because I'm a little stuck at the moment.

**Comment by mbostock** [comment]
My guess is that this isn’t possible. The zoom behavior affects the attached scales’ domains, but it wouldn’t make sense to modify the ordinal scale’s domain when panning and zooming because the domain is discrete. Yes, you could approximate the effect by setting the scale’s range instead, but I think in that case it might make more sense to just use a geometric transform (like in [this example](http://bl.ocks.org/mbostock/3680958)) rather than trying to use semantic zoom.

**Comment by deanmalmgren** [comment]
Thanks for sharing. I'll give that a try next time around.

**Comment by nicgirault** [comment]
+1 I'm also missing this feature!

**Comment by mbostock** [comment]
The new [d3-zoom](https://github.com/d3/d3-zoom) API is not scale-specific (other than [*transform*.rescaleX](https://github.com/d3/d3-zoom#transform_rescaleX) and [*transform*.rescaleY](https://github.com/d3/d3-zoom#transform_rescaleY)), so you could use it to modify an ordinal scale’s range (rather than a continuous scale’s domain) if you wanted.

**Comment by medeirosrich** [comment]
> The new d3-zoom API is not scale-specific (other than transform.rescaleX and transform.rescaleY), so you could use it to modify an ordinal scale’s range (rather than a continuous scale’s domain) if you wanted.

@mbostock are there any example of how this can be done?

I'm trying to apply Zoom to [Grouped Bar Chart](https://bl.ocks.org/mbostock/3887051) along the xAxis

Thanks
