### ISSUE TITLE
Add page about JSON to wiki

### ISSUE THREAD

**Issue by M4urice** [d3/d3#2450]
There is a specific page about how to load CSV data but there is no such page for JSON.

Not a big deal. It's just that I am returning to work with d3 after a while and had to search via Google to find the page which briefly demonstrates the usage of `d3.json()`.

**Comment by mbostock** [comment]
There is an example of using d3.json on the [Requests page](https://github.com/mbostock/d3/wiki/Requests), but it could be improved.

**Comment by M4urice** [comment]
Yep. That's the page I meant. On the other hand there are also `text`, `html`, `xml` and `tsv`. The wiki might get bloated if these were also added.

**Comment by mbostock** [comment]
Right. And also, the CSV page necessarily exists because—unlike JSON, which is a native feature and unambiguous in how it is parsed—CSV parsing is implemented in D3 and configurable. So we need to document things like how to filter rows and convert untyped CSV (arrays of strings) to typed objects. And also the name “CSV” for that page is somewhat of a historical artifact because it covers all delimiter-separated values formats, including TSV.

**Comment by vanboom** [comment]
Also, the documentation for d3.json seems to be incorrect...
d3.json is making a GET request for text/html, not application/json

**Comment by mbostock** [comment]
@vanboom I don’t see that. I see it setting the request accept header as “application/json”:

![screen shot 2015-12-15 at 10 07 01 am](https://cloud.githubusercontent.com/assets/230541/11819235/9d74765c-a313-11e5-950e-ddaafcd555ee.png)

The mime type is set in [src/xhr/json.js](https://github.com/mbostock/d3/blob/master/src/xhr/json.js#L4), which then becomes the accept header and overrideMimeType in [src/xhr/xhr.js](https://github.com/mbostock/d3/blob/master/src/xhr/xhr.js#L95).
