### ISSUE TITLE
d3.nest output is not a valid d3.layout.partition input

### ISSUE THREAD

**Issue by int-ua** [d3/d3#2826]
What's the quickest way to adapt d3.nest output (`key`, `values`) for drawing with d3.layout.partition (`name`, `children`)?

**Comment by int-ua** [comment]
A lot of people had this problem:

https://www.reddit.com/r/javascript/comments/2mrhuv/help_getting_d3s_nest_function_to_work_with/

http://stackoverflow.com/questions/26866368/hierarchical-json-into-flare-json-format-for-use-in-bilevel-partition

http://stackoverflow.com/questions/20913689/complex-d3-nest-manipulation

**Comment by mbostock** [comment]
Here is an example using d3.nest, d3.hierarchy and d3.treemap using D3 4.0:

http://bl.ocks.org/mbostock/2838bf53e0e65f369f476afd653663a2

**Comment by syntagmatic** [comment]
@int-ua D3 4.0 just became the new master branch and uses `d3.hierarchy` as an intermediate data structure between the output of `d3.nest` and all the hierarchy layouts. More documentation here:

https://github.com/d3/d3-hierarchy

It seems like an extra step, but it gives you some nice functions for selecting parts of the tree, like all the `ascendents` (parents and their parents, etc) and `descendants` (children and their children, etc), as well as sorting/summing the hierarchy. The data bound to the layout elements will be the `d3.hierarchy` augmented with the layout properties.

**Comment by mbostock** [comment]
Some related improvements I’ve been considering:

d3/d3-collection#3 - *nest*.entries could return {key, children} objects instead of {key, values} objects, and *nest*.rollup could replace the leaf {key, children} objects with {key, value} objects. That would make it compatible with the default children accessor in d3.hierarchy, eliminating the need to specify a custom children accessor.

d3/d3-hierarchy#42 - *treemap* and the other layout functions could allow non d3.hierarchy instances as input, and automatically pass them to d3.hierarchy to create hierarchies using the default children accessor and if necessary a default value accessor (passed to *hierarchy*.sum), and possibly a default sort comparator.

Together this would mean you could pass the output of d3.nest directly to a hierarchy layout.
