### ISSUE TITLE
Best practices to organise/nest data for d3.js graph output.

### ISSUE THREAD

**Issue by alexc101** [d3/d3#2828]
Hi all,

I'm looking for some advice on how to properly use data with d3.js. Lets say for instance, I have this data set taken from a raw .csv file (converted from excel);

````
EA
Jan_2016,Feb_2016,Mar_2016
Netherlands,11.7999,15.0526,13.2411
Belgium,25.7713,24.1374
France,27.6033,23.6186,20.2142

EB
Jan_2016,Feb_2016,Mar_2016
Netherlands,1.9024,2.9456,4.0728
Belgium,-,6.5699,7.8894
France,5.3284,4.8213,1.471

EC
Jan_2016,Feb_2016,Mar_2016
Netherlands,3.1499,3.1139,3.3284
Belgium,3.0781,4.8349,5.1596
France,16.3458,12.6975,11.6196
````

Using csv would the best way to represent this data be something like;

````
Org,Country,Month,Score
EA,Netherlands,Jan,11.7999
EA,Belgium,Jan,27.6033
EA,France,Jan,20.2142
EA,Netherlands,Feb,15.0526
EA,Belgium,Feb,25.9374
EA,France,Feb,23.6186
EA,Netherlands,Mar,13.2411
EA,Belgium,Mar,24.1374
EA,France,Mar,20.2142
````
This seems very long winded to me, and would use up a lot of time. I was wondering if there was an easier way to do this?

From what I can think of, I assume that JSON may be the more logical choice?

And for context of what kind of chart this could go into, I would be looking to put them in a pie chart and update the data depending on the country/month and comparing the three organisations scores depending on the country/month selected.

(plnk to visualise)
http://plnkr.co/edit/P3loEGu4jMRpsvTOgCMM?p=preview

Thanks for any advice, I'm a bit lost here.

**Comment by mbostock** [comment]
Yes, the two most popular formats are DSV (typically CSV or TSV) and JSON. 

As a hierarchical format JSON may eliminate some redundancies in hierarchical data, but on the other hand, JSON is self-describing and so tends to introduce other redundant information. For example, in this case, you might say something like:

```json
[
  {
    "name": "EA",
    "countries": [
      {
        "name": "Netherlands",
        "dates": [
          {"date": "Jan_2016", "value": 11.7999},
          {"date": "Feb_2016", "value": 15.0526},
          {"date", "Mar_2016", "value": 13.2411}
        ]
      },
      {
        "name": "Belgium",
        "dates": [
          {"date": "Jan_2016", "value": 25.7713},
          {"date": "Feb_2016", "value": 24.1374}
        ]
      },
      {
        "name": "France",
        "dates": [
          {"date": "Jan_2016", "value": 27.6033},
          {"date": "Feb_2016", "value": 23.6186},
          {"date", "Mar_2016", "value": 20.2142}
        ]
      }
    ]
  },
{
    "name": "EB",
    "countries": [
      {
        "name": "Netherlands",
        "dates": [
          {"date": "Jan_2016", "value": 11.7999},
          {"date": "Feb_2016", "value": 15.0526},
          {"date", "Mar_2016", "value": 13.2411}
        ]
      },
      {
        "name": "Belgium",
        "dates": [
          {"date": "Jan_2016", "value": 25.7713},
          {"date": "Feb_2016", "value": 24.1374}
        ]
      },
      {
        "name": "France",
        "dates": [
          {"date": "Jan_2016", "value": 27.6033},
          {"date": "Feb_2016", "value": 23.6186},
          {"date", "Mar_2016", "value": 20.2142}
        ]
      }
    ]
  },
  …
]
```

I didn’t copy the data exactly or completely because I’m lazy, but you can see there’s a lot of redundancy here, even if you remove the whitespace. You could design a more concise format, say by requiring that the dates for all the time series are the same, and using null to represent missing data:

```json
{
  "dates": ["Jan_2016", "Feb_2016", "Mar_2016"],
  "organizations": [
    {
      "name": "EA",
      "countries": [
        {
          "name": "Netherlands",
          "values": [11.7999, 15.0526, 13.2411]
        },
        {
          "name": "Belgium",
          "values": [25.7713, 24.1374, null]
        },
        {
          "name": "France",
          "values": [27.6033, 23.6186, 20.2142]
        }
      ]
    },
  {
      "name": "EB",
      "countries": [
        {
          "name": "Netherlands",
          "values": [11.7999, 15.0526, 13.2411]
        },
        {
          "name": "Belgium",
          "values": [25.7713, 24.1374, null]
        },
        {
          "name": "France",
          "values": [27.6033, 23.6186, 20.2142]
        }
      ]
    },
    …
  ]
}
```

You could also use nested maps rather than arrays to eliminate some redundancy in the property names:

```json
{
  "dates": ["Jan_2016", "Feb_2016", "Mar_2016"],
  "organizations": {
    "EA": {
      "Netherlands": [11.7999, 15.0526, 13.2411],
      "Belgium": [25.7713, 24.1374, null],
      "France": [27.6033, 23.6186, 20.2142]
    },
    "EB": {
      "Netherlands": [11.7999, 15.0526, 13.2411],
      "Belgium": [25.7713, 24.1374, null],
      "France": [27.6033, 23.6186, 20.2142]
    },
    …
  }
}
```

Then you’d want to use [d3.entries](https://github.com/d3/d3-collection#entries) or similar to iterate over your data. (You might also be careful about relying on the order of iteration, since strictly speaking it’s not defined, although in practice when parsing JSON I believe most browsers will return it in-order.)

The previous format is pretty concise, only replicating the country names. If you really wanted to eliminate that, you could have a separate array of countries, and then require a two-dimensional array of values, similar to the trick used to avoid redundantly specifying the dates. In fact, you could just generalize it to an *n*-dimensional matrix of organizations, countries and dates:

```json
{
  "organizations": ["EA", "EB", "EC"],
  "countries": ["Netherlands", "Belgium", "France"],
  "dates": ["Jan_2016", "Feb_2016", "Mar_2016"],
  "values": [
    [
      [11.7999, 15.0526, 13.2411],
      [25.7713, 24.1374, null],
      [27.6033, 23.6186, 20.2142]
    ],
    [
      [11.7999, 15.0526, 13.2411],
      [25.7713, 24.1374, null],
      [27.6033, 23.6186, 20.2142]
    ]
  ]
}
```

That would be the most concise, I expect, but you’d have to remember the dimension order when accessing the data:

```js
var organization = "EA",
    country = "Netherlands",
    date = "Jan_2016",
    value = data.values[organization][country][date]; // 11.7999
```

Anyway. The point is, it’s entirely up to you what format you prefer, and there are tradeoffs to consider in terms of performance and convenience: the most convenient format may not be very efficient, and the most efficient format may not be very convenient. It’s the same when evaluating whether to use CSV or JSON.

Also keep in mind that most datasets are gzip-compressed when transmitted over the internet, so some redundancy in the data often isn’t a performance-killer, and attempts to design the most efficient format can sometimes produce counterintuitive results due to compression.

One of the nice things about CSV (or more generally DSV) is that tabular formats can easily constructed into different hierarchies on-the-fly, so you aren’t committing to a single, fixed hierarchy (as in this example of organization / country / date). You can use [d3.nest](https://github.com/d3/d3-collection#nest) to nest tabular data.

All that said… (and I hope it was helpful)… please use Stack Overflow tag d3.js or the d3-js Google group to ask for help. These issues are for feature requests and bug reports only. Thank you!

**Comment by pokeball99** [comment]
maybe you should have an question tag for issues like these

**Comment by mbostock** [comment]
@pokeball99 There’s no question tag because I don’t have the resources to answer all questions, and questions are fundamentally different in nature to bug reports and feature requests; the appropriate forum for questions is Stack Overflow or the d3-js Google group, not here.

**Comment by pokeball99** [comment]
@mbostock of course, but the ones you do awnser that are noteworthy enough to be useful to others should warrant such an tag

**Comment by mbostock** [comment]
@pokeball99 Fair point! Thank you.
