### ISSUE TITLE
Create function to generate y value from input x value to help dot on interpolated line

### ISSUE THREAD

**Issue by sphinxzhai** [d3/d3#2830]
Need to dot out input data for line interpolate. Some dotted points don't locate on interpolated line. Need a help function to do some calculation to generate y value from input x value.
![firefox_screenshot_2016-05-20t06-12-34 592z](https://cloud.githubusercontent.com/assets/4179759/15418869/f0d23d6e-1e94-11e6-81b6-00190519205c.png)

**Comment by mbostock** [comment]
Please use Stack Overflow tag d3.js or the d3-js Google group to ask for help. These issues are for feature requests and bug reports only. Thank you!

Hint: You might be able to use a binary search in conjunction with getPointAtLength to find the *y*-value at a given *x*-value. My [Closest Point on Path](http://bl.ocks.org/mbostock/8027637) example is closely related, although it performs a two-dimensional search rather than a one-dimensional search. If you assume that there’s only exactly one *y*-value for a given *x* (such as in the case of plotting a time series), then your problem is easier and can be guaranteed to find an accurate corresponding *y* quickly.

**Comment by curran** [comment]
Links for reference

 * [D3 Mailing list](https://groups.google.com/forum/#!forum/d3-js)
 * [D3 Stack Overflow](http://stackoverflow.com/questions/tagged/d3.js)

@sphinxzhai I think what you're after might be [d3-shape#curveCardinal](https://github.com/d3/d3-shape#curveCardinal). There are several [Curves](https://github.com/d3/d3-shape#curves) that meet your requirement that the dots must fall on the lines.

**Comment by sphinxzhai** [comment]
@mbostock @curran  thank you for the hint
