### ISSUE TITLE
Bundling D3 v4 using rollup

### ISSUE THREAD

**Issue by robinhouston** [d3/d3#2831]
I’m experimenting with using rollup to bundle the relevant parts of D3 v4 with my code. I was hoping it would be possible to use

    import * as d3 from "d3";

and then have rollup include just the code required to support the methods that it statically determined to be used in the app.

But this doesn’t work as I hoped it would. In particular, selections don’t have a `.transition()` method, apparently because this method is added as a side-effect of importing `d3-transition`, and rollup determined that none of the d3-transition functions are being used directly.

I also tried adding an explicit `import "d3-transition";` and that didn’t work either, presumably because rollup eliminated the import that statically seemed unused.

I’ve put an example at https://github.com/robinhouston/temp-d3-bundling.

Is it intended to be possible to bundle D3 applications in this way? If so, how can this be made to work? If not, how ought one to do it?

**Comment by mbostock** [comment]
I answered on Twitter already, but for the record, here are two examples demonstrating the recommended approach to creating custom D3 bundles with Rollup:

http://bl.ocks.org/mbostock/bb09af4c39c79cffcde4
http://bl.ocks.org/mbostock/97557a39b4bfc8229786c8bccb54074d

The particular gotcha to be aware of here is that Rollup’s detection of side-effects isn’t perfect, so sometimes you’ll have to give it some hints as to what code you want to include by explicitly importing it (such as importing `selection` from d3-selection so that its prototype can subsequently be modified when you import d3-transition).

**Comment by keeganstreet** [comment]
Hi @mbostock,

Would you mind explaining what the significance is of using `export` for "d3-selection" and `import` for "d3-transition" in your second example? Both features appear to be used equally in `index.html`, so I am unsure why they are imported/exported differently in `index.js`.
