### ISSUE TITLE
step-before/step-after adjacent to nulls

### ISSUE THREAD

**Issue by usethe4ce** [d3/d3#2832]
When drawing a line graph, the behavior when there is a break in the line (i.e., a point where it's undefined, say null) is to not interpolate before or after the null. This seems reasonable enough for something like a spline, but for the various step types (where part of the interpolation is independent of the missing point), it leads to unexpected and counter-intuitive behavior. For example, with "step-after" and [1, 2, null, 4, 5], you would expect a horizontal step line to follow 2 just as it does 1 and 4, but actually it's missing. 

I'm actually finding this by way of c3, but it seems to be an underlying problem in d3, as my workaround entailed monkey-patching d3_svg_line. Example of the problem: http://jsfiddle.net/crxw52r4/1/

**Comment by mbostock** [comment]
This behavior is a consequence of the design of [*line*.defined](https://github.com/d3/d3-shape#line_defined) and [*area*.defined](https://github.com/d3/d3-shape#area_defined): any undefined point is ignored when generating the curve. The point serves exclusively as a delimiter to separate the preceding and following curve segments.

Further, no horizontal line is drawn after *x* = 2 in your example because the step-after curve makes no assumption about how the points are distributed along the *x*-dimension, and thus can’t know how long to draw the additional horizontal line after the last point. (And by symmetry, the step-before curve doesn’t draw a horizontal line before the first point.) You could assume that the *x*-values are spaced uniformly, as in your example, but that’s not true in general. You could just repeat the previous *x*-distance (or half the previous *x*-distance?), but even that limited assumption could lead to overlapping lines if the *x*-values are not uniformly-distributed.

Perhaps a better solution would be to allow the step curve to accept undefined (or NaN) *y*-values, and then not use *line*.defined or *area*.defined to skip the missing data. (Use the default defined accessor which always returns true..) That way, the step-after curve could use *partially* defined points’ *x*-values to extend the following horizontal line, and the step-before curve could generate a preceding horizontal line, and the step curve could do both. Then the only discontinuity would be exactly at *x* = 3 and not all of (2, 4).

I’ll file a feature request over in [d3-shape](https://github.com/d3/d3-shape) for this.

**Comment by mbostock** [comment]
Moved to d3/d3-shape#65.
