### ISSUE TITLE
Week number ticks

### ISSUE THREAD

**Issue by Salma7amed** [d3/d3#2837]
The ISO week numbers are not right when trying to display them on the x-axis using tickformat.

```js
var parseDate = d3.time.format("%Y%W").parse;
var x = d3.time.scale().range([0, width]);
x.domain([parseDate(from_year_week), parseDate(to_year_week)]);

var xAxis = d3.svg.axis().scale(x)
        .orient("bottom")
        .ticks(d3.time.monday,1)
        .tickFormat(d3.time.format("%Y"))
```

This works fine with most of the scenario except when year has 53 weeks.
example: from week 201552 to week 201602. In this scenario it always skips week 53 so the the tick I get are [52, 01, 02]. although the expected output is [52,53,01,02]

Here is a [piece of the code](https://jsfiddle.net/rz0dm0pL/) demonstrating the issue.

**Comment by mbostock** [comment]
The `%W` directive used by [d3-time-format](https://github.com/d3/d3-time-format) is not the [ISO week date](https://en.wikipedia.org/wiki/ISO_week_date); it is the zero-based Monday-of-year in [00, 53]. This means that the first Monday in any given year is always number 1; any date prior to this first Monday in the same year is 0.

For example:

* 201500 is Monday, December 29, 2014.
* 201501 is Monday, January 5, 2015.
* 201552 and 201600 is Monday, December 28, 2015.
* 201553 and 201601 is Monday, January 4, 2016.

The ISO week date has a much more complicated definition of the [first week](https://en.wikipedia.org/wiki/ISO_week_date#First_week). D3 has no support for parsing ISO week dates, so you may need to use another library or another representation in order to parse them.
