### ISSUE TITLE
Random error when changing scales

### ISSUE THREAD

**Issue by Machiaweliczny** [d3/d3#2846]
`d3.js:5949 Error: <g> attribute transform: Trailing garbage, "translate(0,NaN)".`

I keep getting this error randomly with d3 when I'm changing scales in my application. 

Any idea what might cause it?
Just to sum up:
* I'm only switching between linear and logarithmic scales. 
* Data stays intact.
* Error shows randomly.
* All data points are positive.
* Can't google solution to this error.

**Comment by curran** [comment]
Can you please post a code example in [JSBin](https://jsbin.com)/[JSFiddle](https://jsfiddle.net/)/[bl.ocks.org](http://blockbuilder.org/) that reproduces the error? Without a code example, it's nearly impossible to debug and find the root cause. Thank you.

**Comment by mbostock** [comment]
Sounds like you’re trying to render a log scale with a domain that crosses zero.

**Comment by mbostock** [comment]
I tested some axis transitions between linear and log, and even in the case that you’re going to or from a linear scale that crosses zero, the negative ticks just fade-out or fade-in rather than transitioning from an undefined position in log space. 

The axis uses the [scale as the key for the join](https://github.com/d3/d3-axis/blob/master/src/axis.js#L50), so for example, when transitioning to a log scale with a positive domain, any zero or negative ticks would have the key “NaN” and are put in the exit selection rather than the update selection. Then when the axis computes the ending transform for the exiting ticks, the log scale’s position for the exiting ticks is likewise NaN, and so the exiting ticks simply fade-out in-place.

I’ll reopen this and investigate if you post an example demonstrating the issue. Thank you.

**Comment by dabwali** [comment]
So we can avoid this error in console when i am doing the switch from linear scale (having negative domain) to log scale with positive domain

<script>
		var data = [5, 10, 100], dim = 350, padding = 40;

var xScale = d3.scale.linear().domain([1, 100]).range([padding,dim-padding]),
    yScale = d3.scale.linear().domain([-100, 100]).range([dim-padding,padding]);

var xAxis = d3.svg.axis().scale(xScale).orient("bottom"),
    yAxis = d3.svg.axis().scale(yScale).orient("left")
                .tickFormat(d3.format(".2d"));

var svg = d3.select("body").append("svg").attr("width", dim).attr("height", dim);

svg.selectAll("circle").data(data).enter()
    .append("circle")
    .attr("cx", function(d) { return xScale(d); })
    .attr("cy", function(d) { return yScale(d); })
    .attr("r", 5);

svg.append("g").attr("class", "axis x")
	.attr("transform", "translate(0," + (dim - padding) + ")")
	.call(xAxis);
svg.append("g").attr("class", "axis y")
	.attr("transform", "translate(" + padding + ",0)")
	.call(yAxis);

// change to log scale...

yScale = d3.scale.log().domain([1, 100]).range([dim-padding,padding]);

svg.selectAll("circle").data(data)
    .transition().delay(1000).duration(1000)
    .attr("cx", function(d) { return xScale(d); })
    .attr("cy", function(d) { return yScale(d); });

svg.selectAll(".y")
    .transition().delay(1000).duration(1000)
    .call(yAxis.scale(yScale));

	</script>

**Comment by rogeralexmiller** [comment]
Also had this error while trying to convert a scatter plot with linear scale to a log scale. Thanks for clearing this up!
