### ISSUE TITLE
recent modules are broken

### ISSUE THREAD

**Issue by ericsoco** [d3/d3#2850]
Having trouble pinpointing the issues, but I've had to roll back to `d3-axis@0.3`, `d3-selection@0.7`, and `d3-scale@0.7` because more recent versions are not importing correctly.  When I do e.g.

```
import d3_selection from 'd3-selection`
console.log(d3_selection);
```

I see `undefined` for more recent versions of the above packages, but I see correctly-imported objects for the working (for me) versions above.

I'm using [this](https://github.com/ericsoco/es7-sass-boilerplate) as a starting point, and it's likely that there's something in my Babel/Browserify pipeline that is incompatible with module packaging for the recent versions of these d3 packages. I diffed `package.json`, `index.js`, and the `/build` files in these packages to try to track it down, but couldn't figure anything out.

Will report back if I figure anything out. Sorry I can't report a better description/cause of the problem.

**Comment by mbostock** [comment]
Unfortunately, this isn’t enough information for me to help investigate… If there’s something I can run to reproduce the error, then let me know.

The only thing that changed between d3-axis 0.3 and d3-axis 0.4 is that 0.4 exports to a shared `d3` global in a vanilla environment. If you are using Babel, then you should probably be importing from the ES6 modules directly ([index.js](https://github.com/d3/d3-axis/blob/master/index.js)) rather than using the generated UMD bundle ([d3-axis.js](https://npmcdn.com/d3-axis@0.4.1/build/d3-axis.js)). And I don’t think Babel observes jsnext:main by default.

**Comment by mbostock** [comment]
I cloned es7-sass-boilerplate and edited your index.js as follows:

```js
import 'babel-polyfill';
import {select} from 'd3-selection';

const init = () => {
  select(document.body).append('h1').text('Hello, world!');
}

init();
```

It all worked for me. Maybe the problem is you’re trying to use the default export from d3-selection, and there is no default export? It’s possible that behavior changed when Rollup added support for \_\_esModule; see rollup/rollup#650. But in any case you should be importing named symbols, not using the default export.

**Comment by ericsoco** [comment]
I didn't understand that the intent is to import named symbols; yes, I was using the default export.

When diffing the built file (in `build/`) i noticed a line added with `__esModule` in newer versions, so it must be related to that. I don't understand the ins and outs of `__esModule` (tho [this](http://www.2ality.com/2015/12/babel-commonjs.html) helped a bit), nor why its presence kept me from using the default export....but I guess it's moot if I shouldn't be using it anyway.

Thanks for looking into it and for the feedback!

**Comment by mbostock** [comment]
Actually maybe that wasn’t it… I think maybe it was using babel-plugin-module-alias in the .babelrc:

```
  "plugins": [
    ["module-alias", [
      { "src": "node_modules/d3-selection/index", "expose": "d3-selection" }
    ]]
  ],
```

At any rate this also works, though is ugly:

```js
import {select} from '../node_modules/d3-selection/index';
```

**Comment by slurmulon** [comment]
Hi there,

I'm encountering the same problem but have not been able to use the solutions that @mbostock has provided.

No matter which approach you use, either `babel-plugin-module-alias` or `import {select} from '../node_modules/d3-selection/index';`, you will receive the following error:

```Uncaught SyntaxError: Unexpected token export``` from `index.js:1

**Comment by slurmulon** [comment]
@mbostock I am experiencing the same problems trying to port over this drag + drop example (http://bl.ocks.org/mccannf/1629464) into my project using D3 v4, but the solutions you have provided do not seem to alleviate the problem.  I receive the following error:

```
Uncaught SyntaxError: Unexpected token export
```

on line 1 of `node_modules/d3-selection/index`

This is because Babel will not transpile packages under `node_modules` that are referenced in your `src` directory (still not sure why this has to be or if/how it can be configured, most likely exists as an optimization).

One solution as I see it is to have my libary use `webpack` (or something comperable) as you can manually pipe `d3-select` through a `babel-loader` (e.g. `require('babel-loader!../node_modules/d3-select/index')`), but this is less than ideal since my module would only be requiring `webpack` for exclusively patching this problem.

Have you experienced another way of working around this issue without introducing `browserify`, `babelify`, `webpack`, etc.? 

Here is the ES6-ified source of the drag + box example if you are interested:

```js
import * as d3 from 'd3'
import { drag } from 'd3-drag'
// import { select } from 'd3-selection' // BORKED :(

let width  = 800
    height = 600

let boxWidth  = width,
    boxHeight = height,
    barWidth  = 20

const dragElem   = drag()
const dragRect   = dragElem.on('drag', move)
const dragRight  = dragElem.on('drag', resizeRight)
const dragLeft   = dragElem.on('drag', leftResize)
const dragTop    = dragElem.on('drag', topResize)
const dragBottom = dragElem.on('drag', bottomResize)

const svg = d3.select('body')
  .append('svg')
  .attr('width', width)
  .attr('height', height)

const container = svg.append('g')
  .data([{ x: boxWidth / 2, y: boxHeight / 2 }])

const rectangle = container.append('rect')
  .attr('id', 'active')
  .attr('x', (d) => d.x)
  .attr('y', (d) => d.y)
  .attr('height', boxHeight)
  .attr('width', boxWidth)
  .attr('fill-opacity', .5)
  .attr('cursor', 'move')
  .call(dragRect)

const barLeft = container.append('rect')
  .attr('x', (d) => d.x - (barWidth / 2))
  .attr('y', (d) => d.y + (barWidth / 2))
  .attr('height', boxHeight - barWidth)
  .attr('id', 'dragLeft')
  .attr('width', barWidth)
  .attr('fill', 'lightblue')
  .attr('fill-opacity', .5)
  .attr('cursor', 'ew-resize')
  .call(dragLeft)

const barRight = container.append('rect')
  .attr('x', (d) => d.x + boxWidth - (barWidth / 2))
  .attr('y', (d) => d.y + (barWidth / 2))
  .attr('id', 'dragRight')
  .attr('height', boxHeight - barWidth) .attr('width', barWidth)
  .attr('fill', 'lightblue')
  .attr('fill-opacity', .5)
  .attr('cursor', 'ew-resize')
  .call(dragRight)

const barTop = container.append('rect')
  .attr('x', (d) => d.x + (barWidth / 2))
  .attr('y', (d) => d.y - (barWidth / 2))
  .attr('height', barWidth)
  .attr('id', 'dragLeft')
  .attr('width', boxWidth - barWidth)
  .attr('fill', 'lightgreen')
  .attr('fill-opacity', .5)
  .attr('cursor', 'ns-resize')
  .call(dragTop)

const barBottom = container.append('rect')
  .attr('x', (d) => d.x + (barWidth / 2))
  .attr('y', (d) => d.y + boxHeight - (barWidth / 2))
  .attr('id', 'dragRight')
  .attr('height', barWidth)
  .attr('width', boxWidth - barWidth)
  .attr('fill', 'lightgreen')
  .attr('fill-opacity', .5)
  .attr('cursor', 'ns-resize')
  .call(dragBottom)

const move = (data) => {
  console.log('moving', data)
  rectangle
    .attr('x', (d) => data.x = Math.max(0, Math.min(width - boxWidth, d3.event.x)))
  barLeft
    .attr('x', (d) => d.x - (barWidth / 2))
  barRight
    .attr('x', (d) => d.x + boxWidth - (barWidth / 2))
  barTop
    .attr('x', (d) => d.x + (barWidth / 2))
  barBottom
    .attr('x', (d) => d.x + (barWidth / 2))

  rectangle
    .attr('y', (d) => data.y = Math.max(0, Math.min(height - boxHeight, d3.event.y)))
  barLeft
    .attr('y', (d) => d.y + (barWidth / 2))
  barRight
    .attr('y', (d) => d.y + (barWidth / 2))
  barTop
    .attr('y', (d) => d.y - (barWidth / 2))
  barBottom
    .attr('y', (d) => d.y + boxHeight - (barWidth / 2))
}

const leftResize = (data) => {
  const oldX = data.x

  data.x = Math.max(0, Math.min(data.x + boxWidth - (barWidth / 2), d3.event.x))
  boxWidth = boxWidth + (oldX - data.x)

  barLeft
    .attr('x', (d) => d.x - (barWidth / 2))

  rectangle
    .attr('x', (d) => d.x)
    .attr('width', boxWidth)

  barTop
    .attr('x', (d) => d.x + (barWidth / 2))
    .attr('width', boxWidth - barWidth)

  barBottom
    .attr('x', (d) => d.x + (barWidth / 2))
    .attr('width', boxWidth - barWidth)
}

const resizeRight = (data) => {
  const dragX = Math.max(data.x + (barWidth / 2), Math.min(width, data.x + boxWidth + d3.event.dx))

  boxWidth = dragX - data.x

  barRight
    .attr('x', (d) => dragX - (barWidth / 2))

  rectangle
    .attr('width', boxWidth)

  barTop
    .attr('width', boxWidth - barWidth)

  barBottom
    .attr('width', boxWidth - barWidth)
}

const topResize = (data) => {
  const oldY = d.y

  data.y = Math.max(0, Math.min(data.y + boxHeight - (barWidth / 2), d3.event.y))
  boxHeight = boxHeight + (oldY - d.y)

  barTop
    .attr('y', (d) => d.y - (barWidth / 2))

  rectangle
    .attr('y', (d) => d.y)
    .attr('height', boxHeight)

  barLeft
    .attr('y', (d) => d.y + (barWidth / 2))
    .attr('height', boxHeight - barWidth)

  barRight
    .attr('y', (d) => d.y + (barWidth / 2))
    .attr('height', boxHeight - barWidth)
}

const bottomResize = (data) => {
  const dragY = Math.max(data.y + (barWidth / 2), Math.min(height, d.y + boxHeight + d3.event.dy))

  boxHeight = dragY - data.y

  barBottom
    .attr('y', (d) => dragY - (barWidth / 2))

  rectangle
    .attr('height', boxHeight)

  barLeft
    .attr('height', boxHeight - barWidth)

  barRight
    .attr('height', boxHeight - barWidth)
}
```

Versions:

```
"d3": "^4.1.0",
"d3-axis": "^1.0.0",
"d3-drag": "^1.0.0",
"d3-selection": "^1.0.0"
```

Even if you address the module packaging issues by manually transpiling `d3-selection/index`, you will start to receive additional errors regarding `event`s and `NaN` coordinates being unacceptable. The closest related issue I could find was this (same message, different problem): http://stackoverflow.com/questions/24783131/unexpected-value-nan-error-when-dragging-d3-objects-with-mouse

Thanks for taking the time to look into this, and please let me know if there's any other info I can provide as this is a big blocker for me.

**Comment by mbostock** [comment]
Why are you importing both d3 and the submodules such as d3-drag? Seems like you should just use all the d3 modules you need directly rather than depending on the default bundle.

**Comment by slurmulon** [comment]
Ah yeah, that's a bad snippet from experimenting with the new modules. Should be `import d3 from 'd3'`, but I believe I experienced some issue along the way that led me to using `import * from 'd3'` in the first place, probably just something related to `default`.

Anyways, I updated my snippet to use `import d3 from 'd3'` and it still suffers from the same problems. 
Do you have any thoughts on the issues I'm experiencing and proposed solutions? Mostly interested in avoiding Webpack in my module as it's a self-contained D3 module that will be depended on by a separate Webpack-based application

**Comment by mbostock** [comment]
There’s no default export from d3, so `import d3 from 'd3'` doesn’t make sense, but you can use `import * as d3 from 'd3'` to import every symbol as a namespace, similar to what is done in a vanilla environment. The gotcha when doing this is that it requires your environment (or bundler, such as Rollup) to be able to resolve the module names, such as 'd3-color'. Assuming you installed the modules with npm, you will need to look in node_modules to find them, and most importantly, observe the jsnext:main field in the package.json of each module to find the corresponding source file. This value is index.js for all D3 modules (and notably is different from the main entry, which points to the UMD bundle and not the ES2015 source). Unfortunately not all bundlers observe jsnext:main yet, so it may require some work on your part to deal with this underspecified aspect of the ES2015 modules standard.

**Comment by slurmulon** [comment]
Thanks, that was immensely helpful - I was not aware of the `jsnext:main` field consistency problems. My issues stem from a Babel design choice: http://stackoverflow.com/questions/31822593/import-a-module-from-node-modules-with-babel-but-failed

Going to try taking the `babel-register` approach, that should do the trick!
