### ISSUE TITLE
d3-calendar module?

### ISSUE THREAD

**Issue by curran** [d3/d3#2851]
This [Calendar View example](https://bl.ocks.org/mbostock/4063318) seems to be frequently emulated and re-mixed by various people. Might it make sense to encapsulate the calendar layout as a standalone module?

**Comment by mbostock** [comment]
Maybe. Related d3/d3#449.

**Comment by curran** [comment]
Yes, definitely. I was thinking the module could help with 2 things:

1. The rectangles for days.
2. The month outlines.

I wonder what the API could look like? Maybe something similar to [Pie](https://github.com/d3/d3-shape#pies):

```js
var calendar = d3.calendar()
  .cellSize(17)
  .value(accessor);

var days = calendar(data);
var months = calendar.months();
```

**Comment by curran** [comment]
<a name="calendar" href="#calendar">#</a> d3.<b>calendar</b>()

Constructs a new calendar generator with the default settings.

<a name="_calendar" href="#_calendar">#</a> <i>calendar</i>(<i>data</i>[, <i>arguments…</i>])

Generates a calendar for the given array of *data*, returning an array of objects representing each day. It is assumed that each datum represents a single day. Any additional *arguments* are arbitrary; they are simply propagated to the calendar generator’s accessor functions along with the `this` object. The length of the returned array is the same as *data*, and each element *i* in the returned array corresponds to the element *i* in the input data. Each object in the returned array has the following properties:

* `data` - the input datum; the corresponding element in the input data array.
* `x` - the X pixel coordinate of the upper left corner of the rectangle for this day.
* `y` - the Y pixel coordinate of the upper left corner of the rectangle for this day.

<a name="calendar_date" href="#calendar_date">#</a> <i>calendar</i>.<b>date</b>([<i>accessor</i>])

If *accessor* is specified, sets the date accessor to the specified function and returns this calendar generator. This accessor should return a JavaScript Date object.

<a name="cell_width" href="#cell_width">#</a> <i>calendar</i>.<b>cellWidth</b>([<i>width</i>])

If *width* is specified, sets this calendar layout’s cell width (in pixels) to the specified value and returns this calendar layout. If *width* is not specified, returns the current cell width, which defaults to 17.

<a name="cell_height" href="#cell_height">#</a> <i>calendar</i>.<b>cellWidth</b>([<i>height</i>])

If *height* is specified, sets this calendar layout’s cell height (in pixels) to the specified value and returns this calendar layout. If *height* is not specified, returns the current cell height, which defaults to 17.

**Comment by robermorales** [comment]
My two cents:

I think the API may allow to get the cells selection (an array of `<rect>`) but no explicit options to set width in pixels, or `height`, `color`, etc. since that options are already visible as styles/CSS in the `rect` and `d3` is intended to proxy `SVG`, not to hidden `SVG` behind it.

I do not think that `calendar` API call should return pixel coordenates since a lot of people use `d3` to build responsive graphics, so positioning in percent (or perhaps make calendar layout being supported by current `band` scales) are better options.

I have built some visualizations inspired by the cited layout, and some of thems are not week-vs-weekday, but hourofday-vs-week or some similar. I think the API should be more like 

```
d3.calendar( data )
  .x( function( d, i ){ return d3.time.weekOfYear( d.date ); } )
  .y( function( d, i ){ return d.getDay(); } )
...
```

The option to outline the months is really useful but can be generalized, I think, calling it `blocks` or `groups` and assuming it will return a monotonic integer:

```
d3.calendar( data )
  .x( function( d, i ){ return d3.time.weekOfYear( d.date ); } )
  .y( function( d, i ){ return d.date.getDay(); } )
  .groups( function( d, i ){ return d.date.getMonth(); } )
...
```

Thanks you in advance,

**Comment by mbostock** [comment]
I’m happy if someone wants to take a crack at a d3-calendar module (or #449) but I want to start pruning issues and use them exclusively to track things I (or we) are actively or committed to working on and not just potential ideas for future work.
