### ISSUE TITLE
Date Conversion wrong

### ISSUE THREAD

**Issue by CoderSquirrel** [d3/d3#2853]
i have:
```
var parseDate = d3.time.format("%Y").parse;

var x = d3.time.scale()
    .range([0, width]);
```

my date, at tsv/csv is 2009 / 2010, o0nly year.
But at apprearence has it with months, if i stop to parse it's appearin as .009, .010.
I'm following the http://bl.ocks.org/mbostock/3884955 example
with parse
![screenshot from 2016-06-15 13 44 05](https://cloud.githubusercontent.com/assets/6757777/16090910/6024f93a-32ff-11e6-95e2-f5e89c35d5ae.png)
without parse
![screenshot from 2016-06-15 13 45 41](https://cloud.githubusercontent.com/assets/6757777/16090933/7cd98ac8-32ff-11e6-8edb-b54361488df7.png)

i wat it to be only the year, i started at 3d today

**Comment by mbostock** [comment]
Sorry, but there’s not enough information here to help you debug, and I’m not even sure what the problem is (what do you mean by “apprearence has it with months”?). Maybe post your code to http://bl.ocks.org?

I don’t see any issue parsing dates specified as full years:

```js
var parseDate = d3.time.format("%Y").parse;
parseDate("2009"); // Thu Jan 01 2009 00:00:00 GMT-0800 (PST)
```

In the second example it looks like maybe you are specifying dates as milliseconds after the UNIX epoch rather than years.

```js
new Date(2009); // Wed Dec 31 1969 16:00:02 GMT-0800 (PST)
```

If the issue is that you don’t want to render ticks at the months between years, then you probably want to configure your axis to use year ticks rather than to pick the ticks automatically. Something like this should work:

```js
axis.ticks(d3.time.years);
```

**Comment by CoderSquirrel** [comment]
okay.
I have the date only with year, 2009, 2010, 2011, 2012, 2013. And i used the var `parseDate = d3.time.format("%Y").parse;`, at docummentation it says 

> %Y - year with century as a decimal number.

i thought that i would only show the year. Am i wrong?


I don't have the month, but at the chart the months are appearing, i want to take it off;
I tried your solution
```

var parseDate = d3.time.format("%Y").parse;
var x = d3.time.scale()
    .range([0, width]);
x.ticks(d3.time.years);
```

But at the chart the months still there.

**Comment by mbostock** [comment]
> i thought that i would only show the year. Am i wrong?

Yes, because you are confusing parsing and formatting. Parsing converts a string into a JavaScript Date object. You can construct an equivalent JavaScript Date object myriad other ways, such as by using the Date constructor. Formatting means to convert a JavaScript Date back into a string, say so that a human can read it.

In your code snippet, you can calling *scale*.ticks, not *axis*.ticks, because `x` is your time scale and not your axis.

**Comment by CoderSquirrel** [comment]
Thanks @mbostock for the clarification, and sorry for bother you with my silly doubt.
