### ISSUE TITLE
d3-selection enter() selection/Enter Nodes changes

### ISSUE THREAD

**Issue by tomwanzek** [d3/d3#2854]
@mbostock I know you are extremely busy finalizing the major release of the modules and the related documentation.

As I was drawing up some typescript definition files to go along with your new and wonderful modules, I noticed the following.

In the [documentation for changes](https://github.com/d3/d3/blob/master/CHANGES.md#selections-d3-selection) to how [d3-selection](https://github.com/d3/d3-selection) selections now work, you point out that, `enter()` selections are now full selections of _Enter Nodes_:

> There is now only one class of selection. 3.x implemented enter selections using a special class with different behavior for enter.append and enter.select; a consequence of this design was that enter selections in 3.x lacked certain methods. In 4.0, enter selections are simply normal selections; they have the same methods and the same behavior. Enter nodes now implement node.appendChild, node.insertBefore, node.querySelector, and node.querySelectorAll.

Some of the methods defined on general selections (of existing nodes), e.g. `.on(...)` would, it appears, create errors if called on an `enter()` selection, prior to appending materialized elements. E.g. the required `.addEventListener(...)` method would not yet be defined on the `this` context.

So, from your perspective, would it be worthwhile to simply add some comments to the documentation?

As far as the [related draft typescript definitions for d3-selection](https://github.com/tomwanzek/d3-v4-definitelytyped/blob/master/src/d3-selection/index.d.ts) are concerned, I could simply create a separate _interface_ to describe the limited scope of 'viable' methods on the `enter()` selection. This was the previous practice for the [D3 3.x typescript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/adfe4a9c78f885426cfdf4298f0b33763f3cbe08/d3/d3.d.ts).

Your insight would be most appreciated.

**Comment by mbostock** [comment]
I think it’s sufficient to explicitly list the methods that enter nodes implement; adding caveats on *selection*.on and other methods that are nonsensical on enter nodes would be distracting. And I don’t think it’s a good idea to imply there is a separate interface for the enter selection. That would have made sense for 3.x, but unlike 3.x, 4.0’s enter selection is the same class as selection; the only difference is that it contains enter nodes (placeholders) rather than elements. A better analogy is in terms of generics, as in Java; say Selection\<Element\> *vs.* Selection\<EnterNode\>.

More generally, you’re allowed to create selections of things (Selection\<T\>) that are *not* elements using d3.select(T) and d3.selectAll(Array\<T\>). As long as you don’t try to treat non-elements as elements, the selection and any operations on it are valid. For example [OMG Particles II](https://bl.ocks.org/mbostock/9539958) selects a plain object for the purpose of creating a transition that is then rendered to Canvas. That’s a bit of an edge case, and rarely needed, but I don’t want to strictly limit selections to DOM elements.
