### ISSUE TITLE
Variant of Bar Chart

### ISSUE THREAD

**Issue by jamestwiggle** [d3/d3#2857]
I'm a bit new to D3 and trying to understand exactly how to make something like what is described in the SoF post below. I tried looking through `bl.ocks.org` but hadn't had much luck finding something simple to get started with. Any help is appreciated.

http://stackoverflow.com/questions/37842879/how-to-make-a-radial-bar-chart-d3-js

**Comment by curran** [comment]
You can start from a [Donut Chart](http://bl.ocks.org/curran/8f7f5a72faff9ecc5088)
![image](https://cloud.githubusercontent.com/assets/68416/16124798/2bcea360-340e-11e6-90a3-aa1d8cdbe80b.png)

Modifying it to stagger the innerRadius and outerRadius, you can get this [intermediate result](http://bl.ocks.org/curran/76c077c3f779fe4534c6fdf4ff100158):

![image](https://cloud.githubusercontent.com/assets/68416/16124824/563a94ba-340e-11e6-9acc-cd3350014d63.png)

From there you can modify the startAngle and endAngle of each slice such that the startAngle is fixed, and the endAngle varies from 0 to 2PI. The result is this [Radial Bar Chart](bl.ocks.org/curran/71399f6bc86fe25b6eae71fe1a545b09).

![image](https://cloud.githubusercontent.com/assets/68416/16125187/1e842a70-3410-11e6-96ed-126a689f3953.png)

This is possible with D3, but I'm not sure it's a good visualization technique. The values for each slice to not correspond to the area they occupy on the screen. The slices that are farther from the center will occupy more area per unit of value, so perceptually it actually distorts the data, rather than presenting it clearly.

**Comment by mbostock** [comment]
Please use Stack Overflow tag d3.js or the d3-js Google group to ask for help. These issues are for feature requests and bug reports only. Thank you!
