### ISSUE TITLE
d3.scale.ordinal().range[Round]Bands() not consistent

### ISSUE THREAD

**Issue by p-hebert** [d3/d3#2859]
Hey guys!
As I was developing a chart, I stumbled on a weird behaviour, and I would like to know if it's intended or if it is a bug.

So the thing is, I'm trying to do rangeRoundBands of the same height, no matter the number of entries in the data. In order to do so, I specified a constant number to use for the line height, and multiply it by the length of the range generated for the domain of the ordinal scale. Normally I would have expected that the rangeRoundBands return always the same value, cause, you know, `cx / x = c(x+1)/(x+1) = c` (c being the line height constant and x being the number of elements in the range).

I attached a screenshot of the console to show the behaviour.
Let me know what you think!

![selection_047](https://cloud.githubusercontent.com/assets/6445451/16133303/0d9ae094-33e5-11e6-8c3d-44396c8e951c.png)

**Comment by mbostock** [comment]
Sorry, but can you be more specific as to what you expect to happen here? I don’t understand the bug. (And my guess is that you aren’t accounting for padding when specifying the upper bound of the range…)

**Comment by p-hebert** [comment]
No problem! Thanks for the quick response.

In the screenshot above, I specify a domain of *n* elements, which resolves to *[0, ... n-1]*.
I also specify a range for the `rangeBands` which is from *[0 to n\*c]*, where *c* is the expected line height.
Lastly I specify a fixed value *k* for the padding.
My assumption is that the s.rangeBand() function should return a height of *c\*(1-k)* since the domain provided is of length *n* and the padding is supposed to be *c\*k*.

I'm not to sure how to put it otherwise, but let me know if that didn't clarify it.

**Comment by mbostock** [comment]
You’re currently specifying a padding ratio of 0.9. The resulting *step* between bands is computed as:

```
step = (stop - start) / Math.max(1, n - paddingInner + paddingOuter * 2);
step = (stop - start) / Math.max(1, n - padding + padding * 2); // If inner and outer padding are equal.
step = (stop - start) / Math.max(1, n + padding); // Simplify.
step = (stop - start) / Math.max(1, n + 0.9); // Given padding = 0.9.
step = (4 * 56 - 0) / Math.max(1, 4 + 0.9); // 45.71428571428571
```

Where the *step* is illustrated in this diagram:

![](https://raw.githubusercontent.com/d3/d3-scale/master/img/band.png)

The resulting bandwidth (rangeBand in 3.x terminology) is *step* × (1 - *paddingInner*) = 4.571428571428569. If you want the step to be 56 pixels, then you need to specify a different upper bound that accounts for the padding, like this:

```js
var s = d3.scale.ordinal()
    .domain(d3.range(4))
    .rangeBands([0, (4 + 0.9) * 56], 0.9);

s.rangeBand(); // 5.6
```

But, if you also want to use rounding and 0.9 padding, then 56 isn’t a good choice for the *step* because the corresponding bandwidth is 5.6, which isn’t an integer. Better to use 60:

```js
var s = d3.scale.ordinal()
    .domain(d3.range(4))
    .rangeRoundBands([0, (4 + 0.9) * 60], 0.9);

s.rangeBand(); // 6
```

**Comment by p-hebert** [comment]
Sounds great, thanks a lot for the thorough answer!
