### ISSUE TITLE
Dynamic Data Scales

### ISSUE THREAD

**Issue by kennetpostigo** [d3/d3#2860]
It's often we find ourselves writing code to use the correct scales based on data being passed into the chart/graph/etc. I've seen my past coworkers write data transformers or use CSV schema generators to get around this. However when making reusable charts most times you want the chart to be dynamic and adapt to whatever the user/developer want to run through it. 

It would be helpful if there was a utility function that can determine what scale to use based on the data input. In the simplest case the _typeof_ data being passed into the axis of a barchart, using a util like this could help reduce boilerplate code for determining how to map data on an axis.

I hope you are willing to consider something like this.

**Comment by curran** [comment]
I have also wanted to make this, and found that the biggest barrier is not having any standard for representing the column types in terms of data visualization concepts (ordinal, linear, temporal). One tricky case is when you have a field that is an integer, but it should actually be treated as an ordinal identifier. 

There is also the common case where data is already aggregated, and the visualization needs to know what interval is used for each column. For example in this example [Heatmap (2D Histogram, CSV)](http://bl.ocks.org/mbostock/3202354), the step size is in the code, rather than in the data.

Related:

 * [Datalib](https://github.com/vega/datalib) - [dl.type.inferAll](https://github.com/vega/datalib/wiki/Import#dl_type_inferAll) Infers types from values.
 * [Vega-lite/](https://github.com/vega/vega-lite/) - [types](https://github.com/vega/vega-lite/blob/c0bd61fd45f64a31c4fb733cc560c1384cb19330/src/type.ts) QUANTITATIVE, ORDINAL, TEMPORAL, NOMINAL - These are the kinds of types that visualizations need, which are difficult to infer accurately all the time.
 * [chiasm-charts](https://github.com/chiasm-project/chiasm-charts) - see [mixins/scale](https://github.com/chiasm-project/chiasm-charts/tree/master/src/mixins/scale), [autoScaleType.js](https://github.com/chiasm-project/chiasm-charts/blob/master/src/mixins/scale/autoScaleType.js) - My attempt at dynamic scale types.
 * [chiasm-dataset](https://github.com/chiasm-project/chiasm-dataset) A representation of column metadata that includes types and intervals.

**Comment by mbostock** [comment]
Tangentially related to d3/d3-dsv#6.

I have no immediate plans to tackle this, so I am closing this issue. It’s a nice idea, although I’m not sure it fits so well with D3’s level of abstraction, which is pretty low. It might make more sense as a higher-level API on top of D3.
