### ISSUE TITLE
Web-based custom bundle generator.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#2861]
From d3/d3-selection#79, @curran has prototyped a custom bundler:

https://github.com/curran/d3-bundler-ui

Here’s what I’d like to see for a custom bundler:
- Completely static so that we can host it on d3js.org (in [d3/d3.github.com](https://github.com/d3/d3.github.com)), preferably with UI implemented in D3.
- Has a known list of D3 modules, probably starting with the list in [d3’s package.json](https://github.com/d3/d3/blob/master/package.json) but also including a few optional modules such as d3-scale-chromatic.
- For each known module, loads the corresponding package.json from npmcdn to discover dependencies (_e.g._, [d3-time-format](https://npmcdn.com/d3-time-format@1.0.0/package.json) depends on [d3-time](https://npmcdn.com/d3-time@1.0.0/package.json)); it’ll need to observe version ranges, too, but npmcdn mostly resolves that through redirects.
- For each module, it loads and parses the corresponding index.js from npmcdn to discover the exported symbols (_e.g._, [d3-time-format](https://npmcdn.com/d3-time@1.0.0/index.js)). Probably it should use Esprima to parse.
- For each symbol you check, a resulting custom index.js is generated and then passed through to Rollup to generate the custom bundle in the browser. Somehow you’ll have to load all the source files, too… Probably from npmcdn as well.

**Comment by datummm** [comment]
I had a hard time searching for a prebuilt version of rollup that runs in browser, but a kind soul pointed me towards one: https://npmcdn.com/rollup@0.31.2/dist/rollup.browser.js

Also, am I understanding correctly that if everything is completely static, everything should be run client side (loading modules, parsing them, rolling up, etc.)?

**Comment by tungs** [comment]
I had a hard time searching for a prebuilt version of rollup that runs in browser, but a kind soul pointed me towards one: https://npmcdn.com/rollup@0.31.2/dist/rollup.browser.js

Also, am I understanding correctly that if everything is completely static, everything should be run client side (loading modules, parsing them, rolling up, etc.)?

**Comment by biovisualize** [comment]
Here is a Node.js script to extract D3v4 module dependencies using Github API and Acorn.js. Getting the dependencies from npmcdn is probably better, but maybe the Acorn part can be useful. 
https://github.com/biovisualize/d3-dependencies

**Comment by tungs** [comment]
I did some tinkering over the weekend at https://github.com/tungs/browser-roller and it turns out that rollup is pretty flexible in letting you overwrite how it loads and identifies modules. Consequently, you can load modules on-demand from npmcdn. [Here's an example (click the "Roll" button)](https://tungs.github.io/browser-roller/browserRoller.html#{%22mainjs%22%3A%22export%20{%20select%20}%20from%20\%22d3-selection\%22%3B\nexport%20{%20transition%20}%20from%20\%22d3-transition\%22%3B%22%2C%22otherOptions%22%3A%22{\n}%22%2C%22moduleName%22%3A%22d3%22%2C%22exportType%22%3A%22umd%22}).

I also put together some code (in /js/npmloader.js) that extracts package information and export symbols from a module. From there I've made a quick, messy d3 builder [(viewable here)](https://tungs.github.io/browser-roller/d3Roller.html). I haven't quite figured out how to determine which version number of modules to use, so currently it's loading the latest versions.

I haven't tested it out extensively, and there are most likely bugs.

**Comment by tungs** [comment]
After thinking about it, I guess for now, I'll use the version numbers in d3's package.json, but beyond that I'm not sure how to resolve differing version numbers from dependencies.

**Comment by mbostock** [comment]
Nice work, @tungs!

As far as versioning goes, I guess you’d want to be able to specify the versions in the UI, ideally. I’m tempted to say it could default to the latest versions, though that risks incompatibilities (and Rollup pulling in multiple versions of the same module?). Alternatively it could use the versions defined in the d3 package, but that would only cover the modules included in the default bundle, and not optional extras. A third option would be to have the bundler define its own list of default versions, but that’s additional overhead to maintain and would likely lead to things getting out-of-date quickly.

Maybe best to default to latest, and either show an error if there are incompatibilities in dependencies?

**Comment by mbostock** [comment]
Also, it might be nice to run this in a web worker.

**Comment by tungs** [comment]
I've been pretty busy recently, but I've added webworkers and changed the UI to include versions of modules in the [prototype d3roller](https://tungs.github.io/browser-roller/d3Roller.html).

Rollup using multiple versions of modules as dependencies sounded pretty gnarly to me too, so instead, it's currently passed a set of preferred versions that are used for all lookups. Under this setup, dependency conflicts would have to be determined before rolling up.

Also note that the current bundler is fetching d3 package information of export symbols and dependencies on load (instead of using a predownloaded version). This delays initializing the builder for a few seconds as the information is loaded (there's two files per module), but the package information is current. The previous version of the bundler used a node script to fetch the information beforehand and saved to a single .json file, that was then served to the bundler. This is harder to maintain, but faster to load; though conceivably, the collected information could be served by another server that caches that information.
