### ISSUE TITLE
axis.ticks doc confusing

### ISSUE THREAD

**Issue by cmal** [d3/d3#2872]
What does the argument of axis.ticks() really mean? i've studied the api doc of axis.ticks and axis.tickArguments for two days, it is so confusing.

**Comment by mbostock** [comment]
I’m sorry you found the documentation confusing. I’ve attempted to make them clearer; please see [*axis*.ticks](https://github.com/d3/d3-axis#axis_ticks) and [*axis*.tickArguments](https://github.com/d3/d3-axis#axis_tickArguments). If that didn’t help, please elaborate on which parts you find confusing or what questions you have, and I will try to make it clearer. Thank you!

**Comment by cmal** [comment]
If you wouldn't mind, what if put an example of every kind of usage, or at least, every kind of common usage of axis.ticks and axis.tickArguments to show what it can do? I've finished several of my jobs correctly, but still feel confusing about how to set the axis correctly, just try and fail or success, not having a concept in mind about what kind of method I should use. But am I saying this makes you confusing, too? I'm confusing, too. haha... Thank you!

**Comment by cmal** [comment]
For example, what is the relationship of `tick values` and `x` data set? or tick values is just some independent values that I can set as I wish? and what about the relationship of tick interval(the length between x axis ticks) and `x` axis data set? and what is the relationship of tick interval and tick values? This kind of things drive me crazy. Thanks for your help

**Comment by mbostock** [comment]
There are really only two common ways to use *axis*.ticks (and *axis*.tickArguments or *axis*.tickValues), and they are already documented in the README.

The first is to specify a suggested number of ticks rather than using the default suggestion of 10:

```js
axis.ticks(20);
```

A slight variation of this is to also give a tick format specifier, such as `s` for SI-prefix formatting (see [d3-format](https://github.com/d3/d3-format)): 

```js
axis.ticks(20, "s");
```

The reason that *axis*.ticks also takes an optional format specifier is that this method lets the scale automatically set the precision of the format based on the generated ticks, whereas using *axis*.tickFormat requires you to specify the precision manually.

The second way of using *axis*.ticks is with a [time scale](https://github.com/d3/d3-scale#time-scales), where you might want to pass a [time interval](https://github.com/d3/d3-time) instead of specifying the desired number of ticks:

```js
axis.ticks(d3.timeHours);
```

You can only use a time interval with a time scale; there’s no equivalent way of specifying a fixed tick interval for numeric scales, since it is computed automatically from the desired number of ticks.

(Note that any optional format specifier to *axis*.ticks when using a time scale is ignored, per [*time*.ticks](https://github.com/d3/d3-scale#time_ticks), as time scales always use the same format specifier. You *can* however use *axis*.tickFormat to specify a custom tick format for any scale, including time scales.)

The *axis*.tickArguments method is almost never used, but is useful if you want to retrieve arguments previously set by *axis*.ticks and apply them to a secondary axis. For example:

```js
axis1.ticks(20);
axis2.tickArguments(axis1.tickArguments());
```

(The *axis*.ticks method can’t be called in “getter” mode because it would be asymmetric; D3’s getter-setter methods always take one argument and return one value.)

Lastly, *axis*.tickValues can be used instead of *axis*.ticks if you want to hard-code specific tick values rather than relying on the scale (see [*continuous*.ticks](https://github.com/d3/d3-scale#continuous_ticks), for example) to generate those ticks automatically from the scale’s domain and the desired number of ticks. For example, if you wanted ticks at 0, 5 and 10:

```js
axis.tickValues([0, 5, 10]);
```

**Comment by cmal** [comment]
Thanks very much for your help, so I feel standing on the shoulders of you. haha

**Comment by cmal** [comment]
So after specifying the tickvalues, how does d3 know what to show up on the tick? I want to specify the exact string on the tick. For example, If I what a fibonacci array to draw on the x axis but with the format of roman numerals. (II ... III ... V ... ...)  What should I do? Should I first generate a fibonacci array `fibArr = [2,3,5...]` and then pass it to tickValues `axis.tickValues(fibArr)`? If so, what should I do next?
Intuitively, there should be a way to map the tickValues array to the string I really need to show up on the axis. Sorry to bother you. Hope for your reply. Thank you very much!

**Comment by mbostock** [comment]
The tick values determine the position of the tick, by being passed through
the scale.

To control how the tick values are formatted as labels (strings), specify a
tick format. You could example implement your Roman numeral for formatter
by passing a function to axis.tickFormat that returns a string for the
given number.

Please use Stack Overflow if you more questions. I can’t always reply to
these issues, which are intended for bug reports and discussions around
feature requests. Thank you for your understanding.

**Comment by cmal** [comment]
OK. Thank you for your help.
