### ISSUE TITLE
call ignores return value of function

### ISSUE THREAD

**Issue by gordonbrander** [d3/d3#2875]
Hey, new user here. I thought I would mention something I found surprising.

The [documentation for `selection.call()`](https://github.com/d3/d3-selection/blob/master/README.md#selection_call) states:

>     d3.selectAll("div").call(name, "John", "Snow");
> 
> This is equivalent to:
> 
>     name(d3.selectAll("div"), "John", "Snow");

However, this isn't exactly true. [`selection.call` always returns `this` regardless of function return value](https://github.com/d3/d3-selection/blob/master/src/selection/call.js), whereas `name(d3.selectAll("div"), "John", "Snow")` will return whatever `name` returns.

I was hoping to use `selection.call` to make little composable control-flow functions (for example, returning a sub-selection from a function), but this doesn't work given the current behavior.

PS: thanks for a truly excellent library with truly excellent documentation!

**Comment by mbostock** [comment]
It’s true; I glossed over that detail. I’ll fix the documentation rather than change the behavior of *selection*.call. In retrospect it might have been nice to observe the return value of the called function (especially in the case of sub-selection as you mentioned), but that would absolutely require a breaking change and I just released 4.0 yesterday.
