### ISSUE TITLE
Date Interpolation in v4

### ISSUE THREAD

**Issue by gregvenech** [d3/d3#2878]
The following block of code worked fine in v3 but seems to have issues in v4:

    ...
    domain = scales.x.domain(),
    updated = this._getXBounds(points, padding),
    interp = d3.interpolate(domain, updated)
    ...
    t => { 
        interp(t)
    }

I checked my `domain` and `updated` variables to make sure they're actually arrays of dates, which they are. I figured maybe I there was just an API change in v4 with d3-interpolators but I looked through the docs and issues and don't see anything on interpolating dates. `interp(t)` just returns an array of empty objects... Here's a look at the output:

![screen shot 2016-06-30 at 11 55 09 am](https://cloud.githubusercontent.com/assets/8988697/16495055/bf792eea-3eb9-11e6-9367-9fe1fd3ebce5.png)

Any advice would be greatly appreciated, hope I'm not missing something silly.

**Comment by mbostock** [comment]
This is an oversight. The new implementation of d3.interpolate does not special-case objects that are coercible to numbers (such as dates), so the behavior changed relative to 3.x.

I’ve opened d3/d3-interpolate#24 to track this. Either we should special-case dates, adding a new d3.interpolateDate method, and having d3.interpolate(…, *date*) use it. Or we should special-case objects that are coercible to numbers (as 3.x did) so that you can generically interpolate number-like objects as numbers. Or both.
