### ISSUE TITLE
reinstate .fix .unfix for V4

### ISSUE THREAD

**Issue by musesum** [d3/d3#2881]
var forces = d3.forceSimulation() ... 
 forces.fix(d3.event.subject); ...
 force.unfix(d3.event.subject);

working in d3.v4.0.0-alpha.44.js
exception in d3.v4.js and  d3.v4.min.js

**Comment by mbostock** [comment]
These methods were removed in alpha. Please read the [release notes](https://github.com/d3/d3-force/releases).

**Comment by musesum** [comment]
Yes, I saw the release notes. Had implemented fx, fy, but wasn't sure how to undefined them. This may be obvious to a JS expert; took a while to figure "delete d3.event.subjec.fx/fy . Moreover this breaks a lot of V3 and V4.beta examples. Suggest adding .fix and .unfix as convenience functions that add and delete fx, fy for backward compatibility.

**Comment by mbostock** [comment]
Sorry, but I’m not adding them back. I will add some additional documentation. You can also set these values to NaN in lieu of deleting them.

**Comment by musesum** [comment]
Cool. I see you updated your comment to replace NaN with null; yep that works. Thanks.

**Comment by dschwank** [comment]
Just my 5 cents - thanks for the change! :-) ... The previous implementation in the alpha caused some problems, especially if you change the dataset. In that case the internal reference caused an exception, because the node was _maybe_ fixed, but not available in the set anymore. Now the _fix_ is bounded to the node itself again! :-)
Thank you! :-)
