### ISSUE TITLE
v4.0 - d3.zoom() works differently on FF and Chrome

### ISSUE THREAD

**Issue by yairEO** [d3/d3#2888]
### [Demo page](https://jsfiddle.net/fqq6g8ms/6/)

Trying to zoom with the mouse wheel in and out will look differently on Firefox and Chrome.

    svg.call(d3.zoom()
         .scaleExtent([1, 40])
         .translateExtent([[-100, -100], [width + 90, height + 100]])
         .on("zoom", zoomed));

    function zoomed() {
        svg.attr("transform", d3.event.transform);
        gX.call(xAxis.scale(d3.event.transform.rescaleX(x)));
        gY.call(yAxis.scale(d3.event.transform.rescaleY(y)));
    }

**Comment by mbostock** [comment]
Your example is applying the zoom transform to the same SVG element that is receiving the zoom event, causing a feedback loop. Furthermore, the transform attribute is not supported on SVG elements; it must be used on children of SVG elements, such as G elements. Firefox happens to observe a transform attribute that you set on the root SVG element, but Chrome does not, but you shouldn’t rely on Firefox’s behavior because it’s not supported by the standard.

You should assign the zoom behavior to an element that is not transformed so that the mouse coordinates are not affected by the zoom. For example, in the [Pan & Zoom Axes example](http://bl.ocks.org/mbostock/db6b4335bf1662b413e7968910104f0f), an overlay rect element is used:

```js
svg.append("rect")
    .attr("class", "zoom")
    .attr("width", width)
    .attr("height", height)
    .call(d3.zoom()
        .scaleExtent([1, 40])
        .translateExtent([[-100, -100], [width + 90, height + 100]])
        .on("zoom", zoomed));
```

And the zoom behavior is applied to a child G element (view) rather than the SVG element:

```js
var view = svg.append("rect")
    .attr("class", "view")
    .attr("x", 0.5)
    .attr("y", 0.5)
    .attr("width", width - 1)
    .attr("height", height - 1);
```
