### ISSUE TITLE
v4 how to properly scale SVG line graph with zoom

### ISSUE THREAD

**Issue by deandob** [d3/d3#2897]
Hi,

I'm porting a D3 v3 graph widget that uses x-axis panning and zooming to v4. I posted at stackoverflow but couldn't get my problem resolved. I'm unsure if I'm using the v4 zoom APIs correctly as I've tried several approaches and re-read the zoom APIs and changelog.

I have a lot of datapoints that get plotted on a timescale that initially intentionally clumps the datapoints very close to each other, and the user can use zooming to drill deeper into the data for more detail. In v3 when zooming in, the svg line automatically adjusted with the new scale however in v4 when applying zoom scaling on the svg line I get an increases the thickness of the svg line elements rather than resolving more detail (and keeping the line thickness constant). I have no problems with scaling the x or y axis.

This behavior is expected with a scale function but not what I want. I've read the new API for zoom and can't work out what zoom function to use that would give me v3 behaviour where zooming in shows more detail in the line graph and doesn't scale up the line thickness.

In v3 D3 would zoom the svg line with the following in the zoom event handler, however this won't work in v4.

`chart.select("#seriesLine" + i).attr("d", series[i].d3Line(series[i].data))`

Its been a while since I wrote the original graphing widget so possibly I'm just not remembering how to setup D3 correctly, but I think I'm just not groking the new zoom function, and there are no similar zoom examples to learn from. I can't use svg vector-effect non-scaling-stroke as I have to support IE, and I can't inversely scale the line thickness as I am zooming only on the x-axis and svg stroke-width would compress the y-axis thickness.

Apart from this v4 is much nicer to work with - however zooming is a critical feature of my app and I'll have to jump back to v3 if I can't get x-axis zooming to work for line graphs (this is a common use case so I assume I'm just doing something wrong).

Any help / pointers appreciated.

**Comment by mbostock** [comment]
Sorry you didn’t get a response at Stack Overflow, but there or the d3-js Google group is the right place to ask for help. These issues are for feature requests and bug reports only. Thank you for your understanding!

I’ll give a little hint, but can’t offer much more: it sounds like you are transforming the line by using an SVG transform attribute, rather than redrawing the line (updating the `d` attribute) after updating the scale’s domains. You didn’t post your code, so I can’t say where the problem is, but you should be able to use the same technique you used previous in V4 as in V3:

```js
chart.select("#seriesLine" + i).attr("d", series[i].d3Line(series[i].data))
```
