### ISSUE TITLE
D3 v4 resources

### ISSUE THREAD

**Issue by Vaibhavs10** [d3/d3#2898]
Hey! 

I don't really know if this is the right place to ask this question or not, but I'll ask anyway!

I am new to D3 and I am looking for resources to study and understand it, there are a lot of resources for the previous version but not for this one.

What does one suggest?

**Comment by mbostock** [comment]
D3 4.0 came out 12 days ago; D3 3.0 came out 1,297 days ago (December 12, 2012) and D3 2.0, which is only slightly different than D3 3.0, came out 1,783 days ago (August 23, 2011). My point is that there will be more resources for D3 4.0 in the future, after more time has passed after its release.

Also, the tutorials that predate D3 4.0 are hardly irrelevant now. Even though there are a lot of changes in D3 4.0, many of these changes are superficial (such as the renamings). Reading tutorials written for D3 3.x is still an excellent use of your time for learning D3 if you also read them in conjunction with the detailed [release notes](https://github.com/d3/d3/blob/master/CHANGES.md) and [release summary](https://github.com/d3/d3/releases).

The [D3 wiki](https://github.com/d3/d3/wiki) is publicly-editable and you are welcome to contribute to its organization. I noticed someone has created a category for [4.x-specific tutorials](https://github.com/d3/d3/wiki/Tutorials#d3-v4), which might be helpful, though as I said, I wouldn’t discount tutorials that predate 3.x because many of them are still extremely relevant and may only need minor updates, if anything.

**Comment by curran** [comment]
Here are [all the D3 v4 Blocks](http://blockbuilder.org/search#d3version=v4).

Kudos to @enjalot for releasing the new "search by version" feature to Blockbuilder.org, which makes the above link possible.
