### ISSUE TITLE
Docs Improvement Request: npm & module imports

### ISSUE THREAD

**Issue by joshburgess** [d3/d3#2899]
Can we get some more thorough documentation on how to use the new microlibraries with npm? It says very little about how they should be imported and used (defaults vs named exports, where exactly the top level 'd3' object comes from, etc.). 

The documentation only lists the name of the npm package and then shows all examples using script tags instead of imports via require() or ES6 modules.

It would be nice to see some examples centered around building something with a few of these microlibraries using only npm & a module loader like Webpack.

**Comment by mbostock** [comment]
I’m not really sure what you’re asking for. As far as the npm part goes,
it’s just `npm install d3-foo`. The rest depends on your runtime
environment.

If you’re using Node, you require the package, and it returns an object
with all of the symbols exposed by that package. That should be
self-explanatory.

If you’re using ES2015, you need to import from the jsnext:main file
defined in the package.json file, which is typically the index.js file.
Some bundlers support node_modules and jsnext:main automatically (such as
Rollup), but it’s not feasible for me to write bundler-specific
documentation for all bundlers. (And since this part of the ES2015 module
spec is left up to the implementing system.) I have provided a couple
examples of using Rollup linked from the README.

Assuming you figure out how to import the ES2015 bundle in your
environment, again it should be pretty self-explanatory, especially if you
look at the index.js file you imported. None of the modules currently
export default; they export named symbols, with the same names that are
decorated on the global `d3` object in a vanilla environment.

**Comment by joshburgess** [comment]
Yeah, sorry. Nevermind about this. Part of my confusion was just that a lot of methods I was expecting to be in certain packages have been either renamed or rethought out and weren't where I assumed they would be... or they just no longer exist. I'm going to have to spend quite a while going over the changes before I can pick and choose the individual microlibraries, I think. For now I'm just importing the entire library and aliasing it as "d3" like so:

import * as d3 from 'd3'

I'm probably going to wait until I've figured out the new APIs before moving away from the full full d3 npm package.

**Comment by mbostock** [comment]
That sounds reasonable… The default bundle is provided for convenience, after all.

The best place to find which package exports which symbol is the [API Reference](https://github.com/d3/d3/blob/master/API.md). You could also look directly at d3’s [index.js](https://github.com/d3/d3/blob/master/index.js). And if you want to look for something that was renamed from 3.x, it’s in the detailed [Release Notes](https://github.com/d3/d3/blob/master/CHANGES.md).
