### ISSUE TITLE
Zoom behaviour offset by parent container transform - FF

### ISSUE THREAD

**Issue by mwdchang** [d3/d3#2903]
Occurs in Firefox only, when there is a transform on the parent container and a zoom is applied to the children elements, the resulting `d3.event.transform` seems to have an offset proportional to container's transform values.

Example:
http://bl.ocks.org/mwdchang/a88aa3f61f5a2243d15bb8a264aa432e

Observed in both v3 and v4.

**Comment by mbostock** [comment]
Sounds like it might be a bug in Firefox’s implementation of getScreenCTM, possibly related to d3/d3-selection#67 or d3/d3-selection#68. It’s unlikely that I will attempt to workaround this browser bug as D3 is not a compatibility layer.

**Comment by mbostock** [comment]
I’ve confirmed this is a Firefox bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=972041

You might want to comment on that thread to add your test case and give the issue a little prodding if you want it to be fixed.

I’ve filed (and closed) d3/d3-selection#81 to track this issue, but I’m not planning on implementing a workaround for browser bugs in getScreenCTM since it would be a lot of work and likely introduce new bugs. Sorry!
