### ISSUE TITLE
d3.extent() not returning true maximum and minimum of set for strings

### ISSUE THREAD

**Issue by RobertFr0st** [d3/d3#2912]
Hello, it took me a little while to isolate it, but I'm pretty confident the bug is to do with this method.  Here is my test:

function extent_test()
{
  test_set_numeric = [2.43, 12.113, 2.564, 6.9, 4.237, 1.779, 1.446, 1.526, 3.401, 11.204];
  console.log(test_set_numeric);
  console.log(d3.extent(test_set_numeric, function(d) { return d; }));
  console.log("end test");

  test_set_string = ["2.43", "12.113", "2.564", "6.9", "4.237", "1.779", "1.446", "1.526", "3.401", "11.204"];
  console.log(test_set_string);
  console.log(d3.extent(test_set_string, function(d) { return d; }));
  console.log("end test");
}

  And here is the console output through chrome's debugger on version 51.0.2704.63:
![output_test](https://cloud.githubusercontent.com/assets/7746411/16960284/c43944ae-4db6-11e6-8d84-07880b2d6df0.png)

This behavior seems just quirky enough to be looked into as it appears not to follow the normal logic for sorting a string and seems like a potential pitfall for people reading their data in from jsons which have a tendency to stringify everything.

**Comment by mbostock** [comment]
This is the expected and [documented](https://github.com/d3/d3-array#extent) behavior and specifically what is meant by “natural order”. When computing the minimum, maximum or extent, the values are compared using JavaScript’s `<` and `>` operators. For strings this results in a lexicographic ordering:

```js
"6.9" < "12.113" // false
6.9 < 12.113 // true
```

If you want numbers, you must coerce your values to numbers first:

```js
var values = ["2.43", "12.113", "2.564", "6.9", "4.237", "1.779", "1.446", "1.526", "3.401", "11.204"];
d3.max(values); // "6.9"
values = values.map(function(d) { return +d; });
d3.max(values); // 12.113
```

You could use an accessor to do this, too, but it’s not recommended:

```js
var values = ["2.43", "12.113", "2.564", "6.9", "4.237", "1.779", "1.446", "1.526", "3.401", "11.204"];
d3.max(values, function(d) { return +d; }); // 12.113
```

If you have JSON data, then you should probably be storing your values as numbers rather than strings, since JSON is typed. If you are using another format, such as [CSV](https://github.com/d3/d3-dsv), then the best thing to do is using a row accessor to coerce the data as it is loaded. That way you won’t forget to do it later and cause problems downstream. Use a typed format or coerce to types as early as possible!

**Comment by RobertFr0st** [comment]
Alrighty!  My apologies for bringing up a documented behavior.  Thank you for the clarification.

**Comment by mbostock** [comment]
No problem. Also forgot to mention that another reason it is implemented this way is to allow computing the min and max of objects that implement object.valueOf, such as Date objects.
