### ISSUE TITLE
v4.0: One-dimensional `brush.extent()` should accept single pair of values

### ISSUE THREAD

**Issue by ericsoco** [d3/d3#2927]
Took me a bit of stepping through the debugger to figure out why I was getting invalid attribute values for a `<rect>` when setting up a `brushY()` -- I incorrectly assumed that one-dimensional `brush`es only required a single pair of values for `extent()`.

If it's possible/logical, seems like it would be simpler to allow just a single pair of values in this case. In fact, I'm not even clear on what the values for the cross axis are for...I supplied `[0, width]` for my vertical slider and I think it's ok.

Also, better error reporting would be helpful -- maybe just param validation in `extent()`.

**Comment by mbostock** [comment]
The brush’s *selection* can be one-dimensional, but the user interface is always two-dimensional, and so a brush always requires a two-dimensional extent. It defines the brush’s interactive region on-screen.

In most cases, you shouldn’t need to specify the extent because it can be computed using the default definition to cover the entire element:

```js
function extent() {
  var svg = this.ownerSVGElement || this;
  return [[0, 0], [svg.width.baseVal.value, svg.height.baseVal.value]];
}
```

While I do some input validation in D3, it’s impossible to do input validation exhaustively, and so I do it based on a combination of how easy it is to check and how common the error is. The weakly-typed nature of JavaScript also makes this hard: types are typically implicitly coerced, and often objects are allowed in place of arrays (e.g., `{0: "0", 1: "42"}` in place of `[0, 42]`). TypeScript, for example, makes it much easier.

**Comment by ericsoco** [comment]
Ah ok, makes sense, and good tip re: default `extent()`. Still wrapping my head around the semantic changes in `brush` between v3 & v4 -- `extent()` is a particularly tricky one since it went from meaning "extent of the selection" to "selection bounds". I think the new semantics are clearer but I'm still getting used to it.

**Comment by mbostock** [comment]
Yeah, sorry about that. “Extent” is kind of a generic word, like “selection”, which also has a double meaning. :(
