### ISSUE TITLE
Custom shapes/paths not changing after domain is changed from zoom

### ISSUE THREAD

**Issue by neuquen** [d3/d3#2935]
I'm trying to implement zoom functionality for a timeline, but when I zoom in only the y-axis itself changes.  I am expecting the custom path elements which I draw on the right to also change.  So when I zoom in/out on the chart, I expect the shapes on the right to increase/decrease in length.

**EXAMPLE**: https://jsfiddle.net/jgjcz78w/

My zoom function uses the `d3.event.transform` to grab the context which allows me to change the domain:

    function zoomed() {
      var t = d3.event.transform;
      timeline.y.domain(t.rescaleY(timeline.y).domain());

      timeline.updateVis();
    }

You'll notice I call `timeline.updateVis();` which should then go through and update the visualization, but nothing is happening.  It makes me think my Enter, Update, Exit logic could be broken, but can't track down why.

**NOTE**: This is v4 of D3.

I used this block from Mike Bostock as a guide: https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172

**Comment by mbostock** [comment]
Haven't looked at the rest of your code but you can't use transform.rescaleY like that: you'll be repeatedly applying the transform to the same scale. You need to keep an untransformed copy of the scale, and then use transform.rescaleY to derive a transformed copy of the scale, rather than repeatedly applying it to the same scale.

**Comment by neuquen** [comment]
Hey thanks for the quick reply.  It's interesting that you say that because in your own example it doesn't look like you create a copy:

    function zoomed() {
      if (d3.event.sourceEvent && d3.event.sourceEvent.type === "brush") return; // ignore zoom-by-brush
      var t = d3.event.transform;
      x.domain(t.rescaleX(x2).domain());  <----- I copied this line from your code
      focus.select(".area").attr("d", area);
      focus.select(".axis--x").call(xAxis);
      context.select(".brush").call(brush.move, x.range().map(t.invertX, t));
    }

**Comment by mbostock** [comment]
I wrote a longer response and then GitHub’s mobile interface dropped my reply, so unfortunately this will be a shorter response. (That teaches me for trying to use my phone…)

Looking at the rest of your code and *timeline*.updateVis in particular it’s pretty clear that this is a bug in your code rather than d3-zoom, and that’s not surprising given the nature of this bug: d3-zoom doesn’t know anything about shapes, so it’s your code that’s responsible for redrawing. It looks like you’ve defined `vis.group` as the enter selection, which means that on update, it will probably be the empty selection (since the elements already exist) and so it looks like you’re not redrawing anything.

**Comment by mbostock** [comment]
> in your own example it doesn't look like you create a copy

There are two scales there: `x` and `x2`. The `x2` is the untransformed scale, while `x` is the transformed scale.

**Comment by neuquen** [comment]
I appreciate the input @mbostock.  I was able to get it working here: https://jsfiddle.net/bschxdjb/1/, but only by (IMO) hacking it and basically negating the update/exit logic.

At the beginning of `timeline.updateVis` I removed the `vis.group` elements:

    document.getElementById("clip-path").innerHTML = "";

Thus, forcing the data join below to generate new elements each time, rather than updating them:

    var dataJoin = vis.clipPath.selectAll(".group")
       .data(vis.displayData);

I guess that's what I interpreted when you said:

>so it’s your code that’s responsible for redrawing

But that seems like a hack.  Is there no way to use the Enter/Update logic to handle redrawing custom shapes?

**Comment by mbostock** [comment]
Haven't looked at the rest of your code but you can't use transform.rescaleY like that: you'll be repeatedly applying the transform to the same scale. You need to keep an untrannsformed copy of the scale, and then use transform.rescaleY to derive a transformed copy of the scale, rather than repeatedly applying it to the same scale.

**Comment by mbostock** [comment]
[Sorry for the repeated comment; again the GitHub mobile interface got into a weird state and reposted a draft of my earlier comment.]

> Is there no way to use the Enter/Update logic to handle redrawing custom shapes?

There absolutely is! You should use the *update* selection to update existing elements, rather than just the *enter* selection as you are doing currently. Your hack to blow everything away before the data-join is just a correction for the real issue, which is that you’re only handling *enter*: by removing all elements before the join, you’re forcing everything into *enter*.

Unfortunately I can’t afford to dissect your code further and walk you through the data-join. I recommend you study the [General Update Pattern](https://bl.ocks.org/mbostock/3808218) thread. (The [How Selections Work](https://bost.ocks.org/mike/selection/) tutorial might also be relevant, albeit it’s slightly out-of-date for v4 since it doesn’t cover *selection*.merge, and there are a few more join-related tutorials linked from the wiki.)

More generally, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you. Also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/). Thank you! 🤗

**Comment by neuquen** [comment]
Thanks @mbostock!  I really appreciate your help.  Keep up the great work with D3!
