### ISSUE TITLE
Browserify/CommonJS Support

### ISSUE THREAD

**Issue by seonixx** [d3/d3#2940]
What is the current situation regarding browserify/commonJS support? I know this was mentioned in several issues, including #2220 however I'm unsure as to whether this has been, or is going to be, implemented. Please excuse my current lack of in-depth knowledge on JS ES6 modularisation etc.

I've attempted to import D3 via browserify, however I get an error (cannot read property ordinal of undefined) which I assume is related to d3 not binding to the window globally.

NOTE: I'm using nvd3 and angular-nvd3 via browserify successfully.

**Comment by mbostock** [comment]
It sounds like you’re trying to access d3.scale.ordinal and the error is that d3.scale doesn’t exist anymore in v4; it was renamed to d3.scaleOrdinal as part of the great namespace flattening described in the [release notes](https://github.com/d3/d3/blob/master/CHANGES.md).

But to answer the broader question, per the [README](https://github.com/d3/d3/blob/master/README.md), the [released bundle](https://d3js.org/d3.v4.js) supports AMD, CommonJS and vanilla environments. So, one option is to download the d3.zip attached to [the latest release](https://github.com/d3/d3/releases/latest) and then `require("./d3")` to load this released bundle ([d3.js](https://npmcdn.com/d3/build/d3.js)) directly.

More commonly, I’d expect you to use `npm install d3` and then `require("d3")` to load D3 from node_modules using the entry point defined in the [package.json](https://github.com/d3/d3/blob/master/package.json). Due to the fragmented nature of modern JavaScript development, there are several viable entry points that could be used by browserify:

* The `main` entry point is [d3.node.js](https://npmcdn.com/d3@4.2.1/build/d3.node.js), and is intended for a CommonJS/Node environment. It is simply a pass-through to require the [individual D3 modules](https://github.com/d3). The main difference between this and the `browser` entry point is that it guarantees that the symbols resolve to the same references, rather than inlined copies, if you also require the individual modules (e.g., d3-shape) directly. (In the case of [d3-request](https://npmcdn.com/d3-request@1.0.2/build/d3-request.node.js), it also enables a polyfill for XMLHttpRequest which isn’t available in Node.)

* The `browser` entry point is [d3.js](https://npmcdn.com/d3@4.2.1/build/d3.js); this is the same as the [released UMD bundle](https://d3js.org/d3.v4.js) hosted on d3js.org and in the d3.zip release attachment. This bundle has the dependent D3 modules inlined, rather than using pass-through requires, and is intended for a browser environment so you can load everything with a single script tag. I believe this is also the entry point that browserify will chose by default, per [browser-resolve](https://github.com/defunctzombie/node-browser-resolve).

* The `module` (formerly `jsnext:main`) entry point is [index.js](https://npmcdn.com/d3@4.2.1/index.js), and is intended for an ES2015 environments. You’ll want to use this if you are using ES2015, for example with [babelify](https://github.com/babel/babelify), [webpack](https://webpack.github.io/) or [Rollup](http://rollupjs.org/).

**Comment by seonixx** [comment]
@mbostock thanks for such a detailed response. Very helpful.

**Comment by kidsit** [comment]
@mbostock , why in the package.json, there is no "browser" entry point? I use webpack to bundle app. I found transition() is not defined, and i try to include whole d3.min.js but no way to tell webpack how to use. I manually change jsdelivr to browser, it works fine. I do not know why we have no 'browser' key in the package.json file? 
` "main": "dist/d3.node.js",
  "unpkg": "dist/d3.min.js",
  "browser": "dist/d3.min.js",
  "module": "index",`

**Comment by mbostock** [comment]
@kidsit The `browser` entry isn’t standardized and means different things to different tools.

D3 previously supplied a `browser` entry for use by unpkg to determine which file it served by default; from unpkg’s perspective, the `browser` entry meant “intended to be consumed by a browser directly”, such as a UMD. However the meaning of the `browser` entry from Browserify’s perspective was a CommonJS module intended to be transformed by Browserify into a bundle to be consumed by browsers. See https://github.com/unpkg/unpkg/issues/63 for context.

I’m not sure how Webpack interprets the `browser` entry or what sort of file it expects to consume, but your best bet is pointing Webpack at the `module` entry point and consuming D3’s source as ES modules, which should be the default behavior of [resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolve-mainfields), since D3 provides a `module` entry point. Having Webpack consume the Rollup-generated UMD is not recommended.
