### ISSUE TITLE
Is it possible to restrict selection scope to some local DOM element(s)?

### ISSUE THREAD

**Issue by ResidentMario** [d3/d3#2947]
Howdy, there are a few shims floating around for enabling `D3.JS` use from within individual cells of a [Jupyter notebook](http://jupyter.org/) (I wrote one myself).

These aren't very durable, however, because `D3.JS` have access to everything in the DOM, which includes the elements which make up the notebook interface itself. This means that if you, for example, call `d3.selectAll("div").remove();`, the entire page blows up!

It'd be nice if we could enforce idempotence in such embedded scenarios by somehow limiting `D3.JS` DOM scope to just the cell currently in question.

Is this something that's possible to do somehow?

**Comment by mbostock** [comment]
Are you trying to introduce a restriction for security restrictions, or are you simply trying to remove a footgun (i.e., make it less likely that a user accidentally does something overly destructive)?

For security, a JavaScript library is the wrong place to introduce a security layer, since even if you changed the behavior of d3.select and d3.selectAll, it’s always possible to crawl up the DOM using *node*.parentNode, *node*.ownerDocument, and the like. You should probably use a [sandboxed IFRAME](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox).

For usability, yes, you could fork or redefine d3.select and d3.selectAll to search from a different root element (your cell element) rather than using *document*.querySelector and *document.querySelectorAll, respectively. See the implementation in d3-selection’s [select.js](https://github.com/d3/d3-selection/blob/master/src/select.js) and [selectAll.js](https://github.com/d3/d3-selection/blob/master/src/selectAll.js). You could either create a [custom bundle using Rollup](https://bl.ocks.org/mbostock/bb09af4c39c79cffcde4), replacing the `select` and `selectAll` exports in d3’s [index.js](https://github.com/d3/d3/blob/master/index.js#L355-L356), or monkey-patch the pre-built [UMD bundle](https://d3js.org/d3.v4.js).

**Comment by ResidentMario** [comment]
Restrictions of the footgun variety, yes. Good ideas; I particularly like the idea of monkey-patching the selectors. Will try and test them out. Thanks!

**Comment by ResidentMario** [comment]
I have an [early working prototype](https://github.com/ResidentMario/py-d3). I implemented a handful of charts inside Jupyter, including the [D3 Show Reel](https://bl.ocks.org/mbostock/1256572). I need to keep fiddling with it, but it looks promising so far.
