### ISSUE TITLE
D3 line zoom function in v4, issue

### ISSUE THREAD

**Issue by sintylapse** [d3/d3#2956]
Hi, Mike. 
I have an issue with d3 zoom function of chart in v4. In v3 it was okay, it worked like this:

`d3.selectAll('svg').call(d3.zoom().scaleExtent([0.2, 10]).on("zoom", () => {
        d3MainChartRender(self)
    }));`

where "d3MainChartRender" - contains all d3 line render functions like 

`
let chartValue = d3.line().x(data => mainScaleX(data.d3Date)).y(data => mainScaleY(data.close))
d3.selectAll('#prediction-path').attr('d', chartValue(predictionPath))
`

where "mainScaleX" and "mainScaleY" are states of the component, because the App is on React

`mainScaleX: d3.scaleTime().domain(d3.extent(data,(d) => d.d3Date)).range([this.props.rangeMin, this.props.rangeMax])
`

`
mainScaleY: d3.scaleLinear().domain([d3.min(data, (d) => d.close), d3.max(data, (d) => d.close)]).range([this.props.heightMax, this.props.heightMin])
`

The issue is - when i am using the same method with v4, it doesn't work, it calls my callback render func, but mainScaleX , Y functions remain the same as previous, so zoom doesn't zoom anything, even drag doesn't work. But also there is no errors in console log.

How can i make zoom work with line (chart) in d4 version?

**Comment by mbostock** [comment]
Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

I’d recommend including not just a few snippets of your code but a standalone live example, such as on bl.ocks.org. It’s hard to tell from your description where the problem is. It looks like you aren’t do anything with the zoom event when you receive it, so it’s not particularly surprising that the zoom behavior isn’t doing anything. (Perhaps you were reliant on binding scales to the zoom behavior in v3? In which case you’ll need to use *transform*.rescaleX and/or *transform*.rescaleY to derive transformed scales in v4, as in the [third example in the README](https://github.com/d3/d3-zoom/blob/master/README.md).)

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by sintylapse** [comment]
Thanks for the answer, i will use stackoverflow next time.

Solution found here:
https://github.com/d3/d3/blob/master/CHANGES.md#zooming-d3-zoom
https://github.com/d3/d3-zoom#transform_rescaleX

Because zoom no longer changes original scales, need to create clones of the main scales in zoom callback via transform.rescaleX and Y, and use them to draw new axes and line
