### ISSUE TITLE
Number of Ticks in Time Axis is Not Predictable

### ISSUE THREAD

**Issue by tlee13** [d3/d3#2958]
I created a d3 time scale, and used a loop with an iterator to set different tick amount in my d3 axis:

```js
var date1 = "Sun Jan 01 2016 00:00:00 GMT-0800 (PST)";
var date2 = "Fri Jan 01 2020 00:00:00 GMT-0800 (PST)";
var scale = d3.scaleTime()
              .domain([new Date(date1), new Date(date2)])
              .range([0, 100]);
for(var x = 0; x < 20; x++) {
  var x_axis = d3.axisBottom()
                 .scale(scale)
                 .ticks(x);

  d3.select("#test_canvas")
    .append("svg")
    .append("g")
    .call(x_axis);
  
  console.log(x + ": " +d3.selectAll(".tick").size());
  d3.selectAll("svg").remove();
}
```

I print out the number of ticks plotted, and I noticed that it is not always equal to the number that is set in d3.axisBottom().ticks. The number of ticks also varies with the date. This happens to axes created with timescales in both v4 and v3. Is there anything I can do to get reproducible # of ticks? 

Here's a full pen with the above code: http://codepen.io/tlee13/pen/VjooJb?editors=1012

Any thoughts are greatly appreciated.

**Comment by mbostock** [comment]
This is the expected behavior. Per [*time*.ticks](https://github.com/d3/d3-scale/blob/master/README.md#time_ticks) (and similarly see [*continuous*.ticks](https://github.com/d3/d3-scale/blob/master/README.md#continuous_ticks)):

> The specified count is only a hint; the scale may return more or fewer values depending on the domain.

The documentation goes to to list the specific time intervals that are considered:

* 1-, 5-, 15- and 30-second.
* 1-, 5-, 15- and 30-minute.
* 1-, 3-, 6- and 12-hour.
* 1- and 2-day.
* 1-week.
* 1- and 3-month.
* 1-year.

See [d3.ticks](https://github.com/d3/d3-array/blob/master/README.md#ticks) for more on how numeric ticks are generated, and see the [source for time.js](https://github.com/d3/d3-scale/blob/master/src/time.js#L39-L58) for the supported time intervals that are considered for *time*.ticks.

**Comment by mbostock** [comment]
If you want further assistance, you might try [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
