### ISSUE TITLE
d3 v4 force layout: size? on start?

### ISSUE THREAD

**Issue by ramtob** [d3/d3#2971]
Hello.

I'm trying to upgrade a d3 v3 based force simulation to d3 v4, and is facing many issues.

Initial questions: 

1. Where has layout.size (or simulation.size) disappeared to?

2. Why is layout.on('start') (or simulation.on('start')) not supported? What can I use instead?

TIA

**Comment by mbostock** [comment]
I’ve added a couple clarifying notes to the [d3-force 1.0 release notes](https://github.com/d3/d3-force/releases/tag/v1.0.0). To answer your questions:

1. The only effect of *layout*.size in 3.x was to set the focal point of the “gravity” force. This force has been replaced by the positioning forces [d3.forceX](https://github.com/d3/d3-force/blob/master/README.md#forceX) and [d3.forceY](https://github.com/d3/d3-force/blob/master/README.md#forceY), and you can set the focal point using [*x*.x](https://github.com/d3/d3-force/blob/master/README.md#x_x) and [*y*.y](https://github.com/d3/d3-force/blob/master/README.md#y_y), respectively. Or if you prefer, you can use [d3.forceCenter](https://github.com/d3/d3-force/blob/master/README.md#forceCenter) to keep the view centered on a given point, set via [*center*.x](https://github.com/d3/d3-force/blob/master/README.md#center_x) and [*center*.y](https://github.com/d3/d3-force/blob/master/README.md#center_y).

2. There’s no *start* event because the only way to start the simulation’s internal timer is by creating a new [d3.forceSimulation](https://github.com/d3/d3-force/blob/master/README.md#forceSimulation) or by calling [*simulation*.restart](https://github.com/d3/d3-force/blob/master/README.md#simulation_restart). So, if you want to do something on start, just call your code after doing one of the above.

**Comment by ramtob** [comment]
+1

**Comment by syntagmatic** [comment]
Here's an example of running the force layout for 10 ticks before triggering rendering on tick:

http://bl.ocks.org/syntagmatic/6f30a2d719871d041c6eace2193b9f33

```javascript
 simulation.force("link")
      .links(graph.links);

  d3.range(10).forEach(simulation.tick);

  simulation
      .on("tick", ticked);
```

A few more examples of tweaking forces to get things centered and laid out reasonably. The second two are large and CPU-intensive.

http://bl.ocks.org/syntagmatic/954b31aa8b8beb91b30ccb0c9e57f6ce
http://bl.ocks.org/syntagmatic/c334d4293b72a2d1b8827c70e88d4d4f
http://bl.ocks.org/syntagmatic/75c5ca501200b0cf7a5958b4e404f777 (this one goes offscreen)

**Comment by ramtob** [comment]
@syntagmatic Thanks!

@mbostock Concerning your (2) above: if I'm not mistaken, _dragging a node_ was also a way to restart the simulation internal timer. Has this changed?

**Comment by mbostock** [comment]
There is no *force*.drag in v4, though see d3/d3-force#44 for a possible future enhancement.

So, it’s entirely up to you whether you want to restart the simulation’s timer on drag. The [first example linked](http://bl.ocks.org/mbostock/ad70335eeef6d167bc36fd3c04378048) from the [d3-force README](https://github.com/d3/d3-force/blob/master/README.md) demonstrates one technique for implementing dragging. The [d3-drag README](https://github.com/d3/d3-drag/blob/master/README.md) links to more examples.

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by ramtob** [comment]
@mbostock Of course, I'm sorry, you must be super busy.

Just one more question, if I may, specifically for you. Why the bl.ocks.org site? It bothers me that the code there cannot be _edited_. Why not use codepen, or a similar playground site?

Thanks again, and sorry to take from your time.

**Comment by mbostock** [comment]
You edit the code on https://gist.github.com or on the command-line using git commands (see [Let’s Make a Block](https://bost.ocks.org/mike/block/) and [gistup](https://github.com/mbostock/gistup).

**Comment by mbostock** [comment]
The other sites are okay, but I don’t like them as much because they introduce additional code and structure that makes it harder to run the debugger and browser developer tools.

**Comment by vrupesh** [comment]
@mbostock : set the focal point using x.x and y.y, could provide any example pls thanks you

**Comment by mbostock** [comment]
@vrupesh Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

**Comment by baaxten** [comment]
Enviado desde mi smartphone BlackBerry 10.                                                                                                                                                                                                                De: Rupesh VitekarEnviado: lunes, 29 de mayo de 2017 03:31 a.m.Para: d3/d3Responder a: d3/d3CC: SubscribedAsunto: Re: [d3/d3] d3 v4 force layout: size? on start? (#2971)@mbostock : set the focal point using x.x and y.y, could provide any example pls thanks you

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/d3/d3","title":"d3/d3","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/d3/d3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vrupesh in #2971: @mbostock : set the focal point using x.x and y.y, could provide any example pls thanks you\r\n"}],"action":{"name":"View Issue","url":"https://github.com/d3/d3/issues/2971#issuecomment-304604579"}}}
