### ISSUE TITLE
call(d3.axisBottom(d3.scaleTime()) fails in Firefox for particular domains

### ISSUE THREAD

**Issue by ZenGhost** [d3/d3#2986]
Using Windows 10, Firefox 49.0.1, Chrome 53.0.2785.116 m (64-bit) and d3 v. 4.2.6.
The code below works in Chrome but fails in Firefox. If I change the first date to "2015-10-12" then works in both browsers.
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<script src="https://d3js.org/d3.v4.js"></script>
</head>
<body>
<div id="chart"></div>
<script type="text/javascript">
var dates = ["2015-10-11","2015-10-14","2015-10-15","2015-10-16","2015-10-19"];
var w = 600;
var parseDate = d3.timeParse("%Y-%m-%d");
dates.forEach(function(d,i) {dates[i]=parseDate(d)});
console.log(dates);
var svg = d3.select("#chart").append("svg").attr("width", w);
var x = d3.scaleTime().range([0, 500]).domain(d3.extent(dates, function(d) { return d; }));
var xAxis = d3.axisBottom(x);
svg.append("g").attr("transform", "translate(50,50)").call(xAxis);
</script>        
</body>
</html>
```

**Comment by mbostock** [comment]
Sorry, but I’m not able to reproduce this error in Firefox on macOS, and you have not provided enough information to investigate further. Some questions you need to answer if you want me to look again:

* What was the expected behavior?
* What was the actual behavior?
* What time zone are you in?
* Do you see the same error if you use d3.utcParse and d3.scaleUtc?
* Is the problem in date parsing, or in rendering? Can you reduce the example further (e.g., to just date parsing, or just axis rendering, say by using [*interval*.range](https://github.com/d3/d3-time/blob/master/README.md#interval_range)?

I did notice that your SVG element is missing a height attribute, which could cause the SVG to not display on some browsers.

The only other thing this might be related to is d3/d3#1197 d3/d3-time#1 d3/d3-time#1 d3/d3-time#2 d3/d3-time#3. If that’s the issue here, it could be a browser bug which is not feasible to workaround in d3-time.

When reporting an issue, please include a link to a live example, preferably on [bl.ocks.org](http://bl.ocks.org) or [RunKit](https://runkit.com/npm/d3), or as a pull request in the [appropriate repository](https://github.com/d3) with new unit tests, that demonstrates that the described behavior is not the [expected behavior](https://github.com/d3/d3/blob/master/API.md). Use only the minimum amount of code necessary to reproduce the unexpected behavior.

A good bug report should **isolate specific methods** that exhibit unexpected behavior and precisely define how expectations were violated. What did you expect the method or methods to do, and how did the observed behavior differ? The more precisely you isolate the issue, the faster I can investigate.

Non-actionable bugs may be temporarily closed until you provide additional information. If you can’t isolate the bug any further, please let me know and I will try to help. However, I beg your patience: I must balance your request against many other responsibilities—fixing other bugs, answering other questions, new features, new documentation, *etc.* Please also consider asking for help on [Stack Overflow](https://stackoverflow.com/tags/d3.js).

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by ZenGhost** [comment]
Thank you very much for taking the time to give this important orientation. I perfectly understand and I appreciate that. I'll put more work on this issue and if I find something worth of note I'll get back here.

**Comment by ZenGhost** [comment]
@mbostock , your suggestion to use d3.utcParse and d3.scaleUtc did the trick. Now Firefox is working as expected. Thank you.
