### ISSUE TITLE
attr('propName', function(d){}.bind(this)) error

### ISSUE THREAD

**Issue by lanyuechen** [d3/d3#2987]
```js
xxx.attr('x', d => (d))
```

or

```js
xxx.attr('x', function(d) { return d; }.bind(this));
```

both is error, so how can I bind this;

**Comment by curran** [comment]
How is xxx defined here? What is the error exactly?

**Comment by mbostock** [comment]
If the first is an error, it’s probably because the browser you are using doesn’t support ES2015 fat arrow functions.

The second is a syntax error. You need to wrap the function in parentheses to use *function*.bind in that way:

```js
xxx.attr('x', (function(d) { return d; }).bind(this));
```

Of course, if you’re not planning on using the bound *this*, then there’s no reason to use *function*.bind.

If you have further questions, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
