### ISSUE TITLE
Reorganise d3/d3 issues

### ISSUE THREAD

**Issue by Fil** [d3/d3#2994]
(This is going to be self-referential).

Can we help reorganise the open issues in https://github.com/d3/d3/issues ? they should follow the new d3 way of separating topics.

Browsing through the list of currently 87 open issues, I see several types:
- General questions that are more or less well answered, but stay opened for some reason (for example, because they contain a nice idea to contemplate for a future development; or maybe just because no one pushed the "close" button). I would recommend to close them, possibly writing down the idea in an idea list.
- Issues that have been solved with v4 — and can be closed. Often this means, when there is a test case, adapting the d3v3 test case to v4.
- Issues that haven't been solved with v4, but would need to be transferred to the relevant d3-xxxx repo. We could close them and create a reference issue in d3-xxxx.
- Issues that belong to d3 “core” and are not solved. Usually these are tough nuts to crack and they may benefit from a little more explanations or test cases. They should be kept open, and could be tagged “core”; they also include "meta" issues such as this very issue.
- Issues that belong to d3 “project” and are not solved. Usually they are requests for new features, which should now be treated as ideas for new plugins. They could be kept and tagged “plugins”, or regrouped in some other repo, and added to the idea list.

**Comment by Fil** [comment]
Additionally I think it would help to add an [issue template](https://github.com/blog/2111-issue-and-pull-request-templates).

**Comment by mbostock** [comment]
I’ve added an issue template. Thank you for the suggestion.

I’ve closed all the open pull requests, since none of them can be merged now that the code has been moved to different repositories.

Perhaps this my frustration speaking, but I’m partly inclined to turn off issues on this repository, since the vast majority of issues filed here are invalid: they would be better handled as questions on Stack Overflow or as issues filed in the appropriate repository. The main downside of this is that past (closed) issues would no longer be searchable. Unfortunately GitHub doesn’t allow issues to be read-only.

**Comment by AyanGhatak** [comment]
@Fil It would also be good if we also have labels `good first bug` tagged to help the newbie d3 developers, like me to start contributing.
