### ISSUE TITLE
keyPrefix + key means we cannot use true Symbol for key.

### ISSUE THREAD

**Issue by WORMSS** [d3/d3#2995]
I was hoping to use 
```javascript
const guid$ = Symbol("guid");
....
svg.selectAll("g.node")
    .data(nodes.decendants(), data => data[guid$] || data[guid$] = Symbol());
```

but sadly the line below stops such guid's from happening.
```javascript
keyValue = keyPrefix + key.call(parent, data[i], i, data);
```

I didn't know if it would be possible to test what comes back to see if the type is of type `symbol` and if it is, not append the protosafe keyPrefix to keyValue ?

**Comment by mbostock** [comment]
Data-join keys are currently defined to be strings, and equality is defined as string equality. This is in part because the API predates ES collections. I don’t think it’d be appropriate to special-case Symbol here, but perhaps a future major version could make key equality adopt the same convention as ES collections. By the same measure, data could be defined as an iterable rather than an array of values… I have no immediate plans to implement this, so I’m going to close this issue, but feel free to open a new issue over at d3-selection if you want to work on it, or if you want to encourage others to work on it.

**Comment by WORMSS** [comment]
thank you.
