### ISSUE TITLE
D3.js

### ISSUE THREAD

**Issue by jmbut** [d3/d3#3028]
PLEASE READ THIS BEFORE SUBMITTING A NEW ISSUE.

ARE YOU ASKING FOR HELP? Please use Stack Overflow tag d3.js and include a link to a live, minimal example, preferably on bl.ocks.org. If you have a question, consider the d3-js Google Group or the d3-js Slack.

For more: https://gist.github.com/mbostock/7f063e44c57ecb5828dd5643e61f92d3

ARE YOU REPORTING AN ISSUE? Please file an issue on the relevant D3 module, not here; see https://github.com/d3. Please isolate the specific methods that exhibit unexpected behavior and precisely describe how your expectations were not met.

For more: https://gist.github.com/mbostock/370b737ce71bed0749e103b01ce1bfaf

**Comment by jmbut** [comment]
En activant mon fichier html avec mon projet C# de visualStudio, j'ai une erreur à la ligne 3171 du fichier D3.js (Object.create : Object est null)
Si je contourne cette erreur, j'ai une erreur en 6010 : map n'est pas déclaré
function formatRe(names) {
  return new RegExp("^(?:" + names.map(requote).join("|") + ")", "i");
}

Si j'active mon fichier html directement par un double-clic cela fonctionne avec chrome et edge.

Ci-dessous mon fichier html:


<html>
  <head>
  

<link rel="stylesheet" href="leaflet.css" /> 
 
	<script src="d3.js" charset="utf-8"></script>

	  <script type="text/javascript" src="leaflet-src.js"></script>
	  <script type="text/javascript" src="gpx.js"></script>


  </head>
  <body>
    <div id="map" style="height: 100%"></div>

    <script type="text/javascript">
.../...
    </script>
  </body>

</html>

**Comment by mbostock** [comment]
If [Object.create](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create) is null, it might be because you are running in a very old browser; I’m not familiar with the Visual Studio development environment.

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by Ledragon** [comment]
Il serait probablement préférable de poster une issue en anglais, je ne suis pas sur que Mike Bostock parle français; ce serait de toutes façons plus profitable pour les autres utilisateurs.

*Issues should preferably be reported in English, as I am unsure if @mbostock speacks French. In any case, an English question would make it understandable by anyone.*

As you are using Visual Studio, I guess IE is being launched by default, whiche is most liekly the cause of your problem. As mentionned in previous reply, this looks more like a use-case problem and not a bug in d3 itself. If your question is asked on [StackOverflow](http://stackoverflow.com/), could you update this issue to refer it? I would gladly help you, as I am a VS user myself.
