### ISSUE TITLE
Request: I suggest adding a feature which would reveal text on zoom in and truncate on zoom out

### ISSUE THREAD

**Issue by similiarforce** [d3/d3#3031]
Request: I suggest adding a feature which would reveal text on zoom in and truncate on zoom out.

To elaborate more on this I created this JSFiddle - https://jsfiddle.net/qko5dq64/6/

As you can see I have 250 characters long text but I am truncating it using d3 plus. However I suggest it would be nice to have something which would reveal more text just based on zooming if that makes any sense.

Thank you

**Comment by mbostock** [comment]
Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by yoonghm** [comment]
Since it is already closed, i do not know if the email would reach you.
I suggest a more generic feature
- Every object should have a max_zf and min_zf attributes which stand for
maximum zoom factor and minimum zoom factor.
- When user zooms in and out of any d3 canvas,  the whole system zoom
factor will change. If the system zon factor is within an object's zoom
factor [min_zf, max_zf], the object will appear and scale accordingly.

This is a big change and developer need to align objects correctly as
objects, which align or connect in a particular zoom factor,  may not align
or connect in other zoom factor.
