### ISSUE TITLE
D3 zoom not working with mousewheel in safari Version 10.0 (Mac)

### ISSUE THREAD

**Issue by vbabenko** [d3/d3#3035]
This is the same issue that was created before #2626 but no one could reproduced and as result the ticket was closed.
The issue is reproduced only in Safari (FireFox, Chrome works as expected).
I'm using last version of D3 (4.2.2 and 4.4)
The problem that D3 wheel zoom works only on `g` element and doesn't work over `svg` element. Note `dbClick` zoom works over svg.

- Simple fiddle: https://jsfiddle.net/vbabenko/zq0v1rta/1/
- More details + illustration: http://stackoverflow.com/questions/40887193/d3-js-zoom-is-not-working-with-mousewheel-in-safari

Steps of reproduce (Safari):
1. Mouse over on red rect  and start wheel zoom
>> zoom works
2. Mouse over on svg element near of red rect
>> zoom doesn't work

Note: there is exists some zones in svg (left and top) where zoom works. This illustration described in stackoverflow link.

One of possible work around is to insert transparent rect with full width and heigh before our rect and zoom will work for Safari. For example:
`<svg>`
     `<rect></rect> --------> this is transparent rect with full width and height`
     `<g>`
        `<rect></rect> --------> this is our red rect`
     `</g>`
`</svg>`

If someone can explain this behavior in Safari and especially explain 'magic' zones it would be great.

**Comment by powersparks** [comment]
iPhone safari zoom works as well. Checking the wheel.

**Comment by powersparks** [comment]
added a cursor so you could see where the mouse is, background color, and
if the mouse is very near the rect the zoom event is picked up and works
a little further away it stops working... but Vladyslav is right it's buggy
on safari..FF and chrome seems fine.
putting the events on geometry seems like a good practice anyway.. the svg
and wheel events gets a little hard to control

https://jsfiddle.net/powersparks/5shshq97/2/

**Comment by vbabenko** [comment]
@powersparks Thanks for debugging. You have provided really good example. But, I can not explain to myself how is it possible? One element has different behavior depends on zones...

**Comment by powersparks** [comment]
@vbabenko  looking on other issues related to svg and safari there seems to be an issue with the webkit... something to do with scrolling... this forum was in 2013.. so may not be relevant, but if it is still true today, then this may be a bug in safari and webkit:
https://bugs.chromium.org/p/chromium/issues/detail?id=227454

**Comment by mbostock** [comment]
1. As stated in the [ISSUE TEMPLATE](https://github.com/d3/d3/blob/master/ISSUE_TEMPLATE.md) you saw when you filed this issue, please file issues in the appropriate repository (in this case [d3-zoom](https://github.com/d3/d3-zoom/issues)) not here.

2. To make debugging easier, I ported the JSFiddle test case to [bl.ocks.org](https://bl.ocks.org/-/about): https://bl.ocks.org/mbostock/91b75091873d06add0666f35c2e6afb4. 

   I’ve also updated the [Reporting an Issue](https://gist.github.com/mbostock/370b737ce71bed0749e103b01ce1bfaf) instructions to explicitly discourage the use of sites such as JSFiddle since the boilerplate makes debugging more difficult.

3. As shown in the [updated test case](https://bl.ocks.org/mbostock/91b75091873d06add0666f35c2e6afb4), this is a Safari bug (or if you like, an alternative interpretation of the specification). Safari does not dispatch wheel events to the SVG when there is no SVG content under the pointer; the events get sent to whatever is *underneath* the SVG element (the body in this case). In contrast other browsers dispatch wheel events to the SVG element anywhere inside its bounding rect.

    If you want the SVG to receive the event on all browsers, you must put some content in the SVG to capture the wheel event. Here is a fixed test case: https://bl.ocks.org/mbostock/9e3fed7a5904991e7973a87628d9f84d

**Comment by vbabenko** [comment]
@mbostock @powersparks 
Thanks a lot for detailed clarification and your help!

**Comment by karlcow** [comment]
See https://bugs.webkit.org/show_bug.cgi?id=226683

**Comment by vincerubinetti** [comment]
> If you want the SVG to receive the event on all browsers, you must put some content in the SVG to capture the wheel event.

I believe this bug still happens in some cases even when there is content in the wheeled element, as soon in the bug report linked above by @karlcow. Definitely still a Safari bug though. The [Stack Overflow post linked in the bug report](https://stackoverflow.com/questions/67836886/wheel-event-is-not-fired-on-a-svg-group-element-in-safari) shows a workaround.

As usual, Safari having awful SVG handling.
