### ISSUE TITLE
More D3 4.0+ Bower

### ISSUE THREAD

**Issue by eriksunsol** [d3/d3#3041]
Related to https://github.com/d3/d3/issues/2874, which is about publishing the default set of D3 modules on Bower as `d3`, I was looking for Bower packages for some of the other modules, some of which seem to be published on Bower, but not all. I was specifically looking for `d3-selection-multi`.

May I suggest that all the modules be published on Bower?

**Comment by miyconst** [comment]
>May I suggest that all the modules be published on Bower?

Or at least compatible with bower, so it is possible to install by providing full path to the GitHub URL.

**Comment by mbostock** [comment]
No, a million times, no. Sorry. Bower is a huge burden for developers because typical practice requires storing generated files in git. I’ve begrudgingly maintained legacy support for a few Bower projects by creating dedicated git repositories in a dedicated [mbostock-bower organization](https://github.com/mbostock-bower) but there is absolutely no way I am willing to add more to the list. ([Related](https://github.com/unpkg/npm-http-server#bower-support), [related](https://medium.com/@kentcdodds/why-i-don-t-commit-generated-files-to-master-a4d76382564#.zby7reuws).)

The publishing systems I support are:

* npm (*e.g.*, <https://www.npmjs.com/package/d3-shape>)
* GitHub releases (*e.g.*, <https://github.com/d3/d3-shape/releases/latest>)
* d3js.org (*e.g.*, <https://d3js.org/d3-shape.v1.js>)

I strongly urge you to use npm to download releases. npm does a reasonable job ensuring immutability of releases, so that you can generally guarantee that a version you are using will not change or disappear in the future. And npm supports the publishing of generated files, obviously. And there’s [unpkg](https://unpkg.com/) built on top of npm for convenient direct access to individual published files.

I don’t think Bower has built-in support for installing from the npm registry; that would be nice. But I know that it at least can install a file from an arbitrary URL, so here are some possible URLs you could use:

* https://unpkg.com/d3-shape
* https://unpkg.com/d3-shape@1.0.4/build/d3-shape.js
* https://registry.npmjs.org/d3-shape/-/d3-shape-1.0.4.tgz

**Comment by eriksunsol** [comment]
Ouch. Anyway, thanks for explaining the lack of Bower support. Respect.
