### ISSUE TITLE
In D3 'enter' sequence 'selectAll' accepts any non-empty string. Could design be improved?

### ISSUE THREAD

**Issue by quantbo** [d3/d3#3042]
In the D3 'enter' sequence the 'selectAll' method accepts any non-empty string. See the following example:

https://bl.ocks.org/quantbo/45b98a10e42aa6656d0aa3aaaaf1a971

This suggests that 1) a method with an empty signature might be more appropriate for use at this point; or 2) the selectAll could be completely eliminated.

**Comment by jdylanstewart** [comment]
Interesting. I would have expected the selection would return empty since there are no children which would match the string.

On Dec 23, 2016, at 6:30 AM, quantbo <notifications@github.com<mailto:notifications@github.com>> wrote:


In the D3 'enter' sequence the 'selectAll' method accepts any non-empty string. See the following example:

https://bl.ocks.org/quantbo/45b98a10e42aa6656d0aa3aaaaf1a971

This suggests that 1) a method with an empty signature might be more appropriate for use at this point; or 2) the selectAll could be completely eliminated.

**Comment by joshua-golub** [comment]
The selection returned by `selectAll` ***is*** empty (since nothing matches the string). Then, the `data/enter/append` combo creates three new `circle` elements, one for each row in the data set.

**Comment by quantbo** [comment]
I'm not arguing about the functionality, which is fine. The syntax, though, is peculiar and potentially misleading. If a function with a string argument does not care which string is submitted then a better syntax would utilize a function with an empty signature or fold the function into another function. In the present case the elegant solution might be to fold selectAll into the <code>data</code> function.

To be clear, this is a user interface issue. Most of the examples that I have seen concerning the paradigm under discussion provide an argument to selectAll that *appears* meaningful. If circles are being generated then the author will provide selectAll with an argument such 'circle' or 'dot' or something similar. This conveys the impression that the argument has some meaning and  will have some effect on the execution of the program. In fact, the argument is completely irrelevant. If an argument is completely irrelevant then the function taking said argument should be rewritten or eliminated so as not to cause programmers to struggle with it.

**Comment by mbostock** [comment]
I would prefer if you discuss D3’s API on the d3js Slack or the d3-js Google group. I use these issues to tract bugs and active feature requests. As noted in the [issue template](https://github.com/d3/d3/blob/master/ISSUE_TEMPLATE.md), no new issues should be filed in this repository; issues should be filed in an appropriate submodule instead. (See the [D3 organization](https://github.com/d3).)

That said, to attempt a quick answer to your question, consider an analogy with the W3C Selector API’s [*element*.querySelectorAll](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll). Your argument suggests that if the *element* is empty, it is pointless for *element*.querySelectorAll to take an argument, because the return value will always be an empty NodeList.

```html
<body></body>
```

But obviously *element*.querySelectorAll takes a *selector* argument because if the *element* *does* have descendants, then *element*.querySelectorAll can return a non-empty NodeList. So *element*.querySelectorAll is a general-purpose method.

The *selection*.selectAll method functions similarly. You’ve constructed a situation (admittedly a common one!) where the `svg` selection is empty, so you know that calling `svg.selectAll(…)` will always return an empty selection. **Yet** if the `svg` selection were *not* empty, then it would not return an empty selection. And that is why *selection*.selectAll always takes a *selector*.

If you wanted, you could special-case an idiom like [*selection*.appendMany](https://github.com/gka/d3-jetpack/blob/master/README.md#selectionappendmany) from [d3-jetpack](https://github.com/gka/d3-jetpack). But D3 instead encourages you to implement a data-join that is **independent of the current state of the DOM**. That is, one that works regardless of whether you are starting from an empty empty or a non-empty empty, and one that should make the document match your current data regardless of its initial state.

To learn more about the design of the API, I suggest reading the [General Update Pattern](https://bl.ocks.org/mbostock/3808218) example thread, [Thinking with Joins](https://bost.ocks.org/mike/join/), and [How Selections Work](https://bost.ocks.org/mike/selection/) for more on selections.

Thanks for the feedback!
