### ISSUE TITLE
Circle packing layout seems to break down with large numbers of elements

### ISSUE THREAD

**Issue by sheldon-white** [d3/d3#3045]
I've reproduced this with a couple of large datasets; there's some unexpected overlaps in some of the circles. I haven't been able to recreate this with a small dataset so far. I've attached a screenshot, a datafile and example page that shows the issue.

![](https://cloud.githubusercontent.com/assets/1130768/21513920/08da21ec-cc73-11e6-8c39-169ac069a0e7.png)

[bugreport.zip](https://github.com/d3/d3/files/675039/bugreport.zip)

**Comment by mbostock** [comment]
There is a bug in d3.pack here, but it is being triggered by a bug in your code. Specifically here, where you say:

```js
root.sort(function(a, b) { return b.lines - a.lines; });
```

Unlike [*node*.sum](https://github.com/d3/d3-hierarchy/blob/master/README.md#node_sum), which passes the accessor function the node’s data, [*node*.sort](https://github.com/d3/d3-hierarchy/blob/master/README.md#node_sort) passes the comparator function two nodes (not two data!). This is because *node*.sort typically operates on the sum computed by *node*.sum. So your comparator returns NaN when sorting two non-leaf nodes, and that means that the behavior of *array*.sort (and by extension *node*.sort) is undefined and may vary across browsers.

You should instead say:

```js
root.sort(function(a, b) { return b.value - a.value; });
```

And this indeed fixes the problem. Before:

<img width="1264" alt="screen shot 2016-12-28 at 10 14 19 am" src="https://cloud.githubusercontent.com/assets/230541/21528305/746c84c2-cce6-11e6-8915-61305ca7cf40.png">

After:

<img width="1268" alt="screen shot 2016-12-28 at 10 10 49 am" src="https://cloud.githubusercontent.com/assets/230541/21528307/7b6ba456-cce6-11e6-89ee-809fad2cd526.png">

I think the problem here is that the circle-packing layout is initially placing a few very small circles and there is numerical instability because the circles are so small. It’s possible that this is impractical to fix in the library, or that we’ll need a cludgy workaround like treating all circles smaller than ε as zero.

I reduced your test case here: http://bl.ocks.org/mbostock/1eb59d8139b3bea5c71e46afee440f9e

**Comment by mbostock** [comment]
Reduced to the following input:

```json
{"path":"/","children":[
  {"path":"/a","value":3},
  {"path":"/b","value":30},
  {"path":"/d","value":50},
  {"path":"/c","value":400},
  {"path":"/e","value":600}
]}
```

Which fails like so:

<img width="402" alt="screen shot 2016-12-28 at 10 57 19 am" src="https://cloud.githubusercontent.com/assets/230541/21529159/736d13f6-ccec-11e6-9f13-f3dd5d53ed51.png">

**Comment by mbostock** [comment]
This one also fails, in a different way:

```json
{"path": "/", "children":[
  {"path": "/a", "value": 3},
  {"path": "/b", "value": 70},
  {"path": "/d", "value": 100},
  {"path": "/c", "value": 200},
  {"path": "/e", "value": 500}
]}
```

<img width="555" alt="screen shot 2016-12-28 at 11 00 30 am" src="https://cloud.githubusercontent.com/assets/230541/21529237/e9229328-ccec-11e6-8c2d-a9eed128199b.png">

**Comment by sheldon-white** [comment]
Thanks so much for your quick response! I'm having a lot of fun trying to get familiar with D3 and I'm very impressed with what you've created.

**Comment by mbostock** [comment]
Moved to d3/d3-hierarchy#74.
