### ISSUE TITLE
Error evaluating file /node_modules/d3/d3.js Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by frank-dspeed** [d3/d3#3067]
```
Error evaluating file:/Users/marcgodard/CloudStation/Projects/YOURICO/site/node_modules/d3/d3.js
Cannot read property 'prototype' of undefined
```
As an error. And d3.js is what is underlining bit-c3

I also updated the issue: 
https://github.com/bitovi-components/bit-c3#30

**Comment by mbostock** [comment]
When reporting an issue, please include a link to a live example, preferably on [bl.ocks.org](http://bl.ocks.org) or [RunKit](https://runkit.com/npm/d3), or as a pull request in the [appropriate repository](https://github.com/d3) with new unit tests, that demonstrates that the described behavior is not the [expected behavior](https://github.com/d3/d3/blob/master/API.md). Use only the minimum amount of code necessary to reproduce the unexpected behavior.

A good bug report should **isolate specific methods** that exhibit unexpected behavior and precisely define how expectations were violated. What did you expect the method or methods to do, and how did the observed behavior differ? The more precisely you isolate the issue, the faster I can investigate.

Non-actionable bugs may be temporarily closed until you provide additional information. If you can’t isolate the bug any further, please let me know and I will try to help. However, I beg your patience: I must balance your request against many other responsibilities—fixing other bugs, answering other questions, new features, new documentation, *etc.* Please also consider asking for help on [Stack Overflow](https://stackoverflow.com/tags/d3.js).

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
