### ISSUE TITLE
Pie chart showing incorrectly in d3 v4 and d3 v3 in chrome browser

### ISSUE THREAD

**Issue by bgth** [d3/d3#3069]
Hi,

Please see the below fiddle in chrome browser. This works fine in mozilla firefox. The color and tooltip in pie chart is shown of the smaller value. Instead it should be shown of the bigger value.  Can you please help for how it can be fixed? This issue occurs when in the pie chart dataset, one of the data is very big. This issue is there in both d3js v3 and d3js v4.

[d3js v3 pie chart ]( http://jsfiddle.net/bgth/1ttfkf0k/1/)

[d3js v4 pie chart](https://jsfiddle.net/bgth/hw7a835d/8/)

It was found when using nvd3 which uses d3js v3.

[nvd3 issue](https://github.com/novus/nvd3/issues/1958)

Thanks.

**Comment by mbostock** [comment]
I am not able to reproduce this issue. It appears to work as expected here, with a large blue arc representing the first data value (257,236,622,683) and a very small green arc representing the second (1,200):

https://bl.ocks.org/mbostock/64cf2b345eea199a2364dadc7c47ce68

The v4 example you linked had no tooltips. The v3 example has a tooltip, which functioned as expected, showing the larger value over most of the pie and the smaller value when you mouseover the label of the smaller wedge (which was basically invisible). Both linked examples rendered a large and small arc as expected.

(You probably should consider hiding arc labels if the arc is extremely small, or moving the label outside of the arc, and giving the arc a stroke so that at least some part of it is visible.)

If you have an issue with NVD3, I suggest you report it to NVD3 or use their help forums as appropriate.

Otherwise, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by jerryz1982** [comment]
![image](https://cloud.githubusercontent.com/assets/1919098/23491080/f09af406-feb0-11e6-949d-054cad680d00.png)

**Comment by mbostock** [comment]
I am not able to reproduce this issue, so unfortunately I’m not able to investigate. What browser version and operating system are you using?

<img width="953" alt="screen shot 2017-03-02 at 7 18 35 am" src="https://cloud.githubusercontent.com/assets/230541/23513408/cb2be758-ff18-11e6-9b6b-116c3a4f6dd2.png">

**Comment by jerryz1982** [comment]
Hi
I was using Chrome Version 56.0.2924.76 (64-bit) on Ubuntu Xenial and it has the issue.
I just tested on a windows8 Chrome 56.0.2924.87 32 bit without the issue.

**Comment by bgth** [comment]
Hi @mbostock,
Thanks for checking.
I am using Chrome Version Version 56.0.2924.87 (64-bit) on Ubuntu 16.04 x86_64 Xenial and the issue is present.

**Comment by mbostock** [comment]
Since I can’t reproduce this locally, I would appreciate your help debugging. My guess is that this is a Chrome browser bug rendering small arcs. I’ve reduced the test case and added a debugger statement, so if you load this URL with the developer tools open, you should be able to step through the code and see where it goes wrong:

https://bl.ocks.org/mbostock/raw/64cf2b345eea199a2364dadc7c47ce68/23f4ae4aa535e93eaf781f828e9ae845118de5b5/

On my machine, I see the following sequence of calls:

```js
context.moveTo(-0.000007034602278144558, -239.9999999999999);
context.arc(0, 0, 240, 4.712388951073847, 4.712388980384691, false);
context.lineTo(0, 0);
context.closePath();
```

So, we can first test whether this sequence of calls renders correctly on Ubuntu with Canvas. And we can also test if there’s a problem converting this to SVG, which is done by [d3-path](https://github.com/d3/d3-path). If you open this:

https://bl.ocks.org/mbostock/raw/491076c4efac7aff7fd3dba4c068f231/

You should see two small arcs that appear as lines:

<img width="962" alt="screen shot 2017-03-02 at 10 22 08 am" src="https://cloud.githubusercontent.com/assets/230541/23521026/292ec46a-ff32-11e6-9a94-72f30c6329ac.png">
<img width="962" alt="screen shot 2017-03-02 at 10 22 17 am" src="https://cloud.githubusercontent.com/assets/230541/23521033/2d0acb6a-ff32-11e6-8424-a18a4663c255.png">

The blue one is native canvas, and the red one is SVG using d3-path.

If the blue Canvas is busted, then it’s almost certainly a browser bug and you should file it at https://bugs.chromium.org using this test case. If the red SVG is busted, it could be a problem with d3-path. If they are both busted, it could be a problem with d3-shape.

Please let me know what you find.

**Comment by jerryz1982** [comment]
Hi @mbostock 
thanks for the test case. I also confirmed on a windows 64 bit machine and the issue persists. so could be 64bit issue independent of windows or linux.
As for the test case you provided, the blue canvas is busted.
![image](https://cloud.githubusercontent.com/assets/1919098/23521229/f0016156-ff32-11e6-9725-b3df6eb331d4.png)

**Comment by mbostock** [comment]
You said the blue canvas is busted but from your screenshot the blue canvas appears to be correct, rendering a small arc, while the red SVG is incorrect, rendering a large arc.

**Comment by jerryz1982** [comment]
sorry. i correct myself, the red one is busted as appears in the screenshot.

**Comment by mbostock** [comment]
Okay, I’ve added one more test:

https://bl.ocks.org/mbostock/raw/491076c4efac7aff7fd3dba4c068f231/71fd363835689e3a3dad23fcd7d642730968fa51/

If you scroll down you should see a green test:

<img width="962" alt="screen shot 2017-03-02 at 10 32 42 am" src="https://cloud.githubusercontent.com/assets/230541/23521387/9b8e2838-ff33-11e6-84ea-c639778f5b45.png">

This is a static SVG that I generated using d3-path on my computer. If this appears correct (as a small arc) on Ubuntu, then the issue is in d3-path. Please confirm.

**Comment by jerryz1982** [comment]
![image](https://cloud.githubusercontent.com/assets/1919098/23521499/23bbb374-ff34-11e6-8d7a-6d2e37689027.png)

**Comment by mbostock** [comment]
Thanks. That means this is an SVG rendering bug, and not a bug with D3.

**Comment by jerryz1982** [comment]
sorry i am not familiar with svg rendering but i could not reproduce this with highcharts, which also renders svg.
http://jsfiddle.net/dahoo1/p8kLzte0/1/

**Comment by mbostock** [comment]
The green test case above is just static SVG. If it renders differently on Ubuntu that on other platforms and browsers, that means there’s a bug with Chrome’s SVG renderer, and the best thing you can do to fix this problem (for you and for everyone else that uses Chrome on Ubuntu) is to file a bug with the browser vendor.

**Comment by mbostock** [comment]
I’ve release [d3-path@1.0.4](https://github.com/d3/d3-path/releases/tag/v1.0.4) which introduces a workaround for this issue. (I still recommend filing a browser bug, however, as this sort of thing is likely to reoccur.)

**Comment by jerryz1982** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=698007
I filed a bug on chromium
