### ISSUE TITLE
line.interpolate("cardinal") in version 4

### ISSUE THREAD

**Issue by winder520** [d3/d3#3070]
In version 3 I have this section of code:
```javascript
var loopFunction = d3.svg.line ()
.x (function (d) {
return d.x;
})
.y (function (d) {
return d.y
})
.interpolate ("cardinal")
.tension (-1);
```
In version 4 I modified to:

```javascript
var loopFunction = d3.line ()
.x (function (d) {
return d.x;
})
.y (function (d) {
return d.y
})
.curve (d3.curveCardinal.tension (-1));
```

When I call the method loopFunction passed a parameter:
`[{"x": 70.31797611050145, "y": 237.061601527101}, {"index": 88, "x": 114.03468800110291, "y": 273.2449708855732, "vy": 0.0019068901105323065 , "Vx": - 0.00017607654513037712}, {"x": 57.84059504012937, "y": 265.33225751082347}]`
The results in version 3 are:

"M70.31797611050145, 237.061601527101Q122.35294204801762,254.3978668964249,114.03468800110291,273.2449708855732Q105.71643395418819,292.0920748747215,57.84059504012937,265.33225751082347"

But the result in version 4 is:

"M70.31797611050145,237.061601527101C70.31797611050145,237.061601527101,118.19381502456027,263.82141889099904,114.03468800110291,273.2449708855732C109.87556097764555,282.66852288014735,57.84059504012937,265.33225751082347,57.84059504012937,265.33225751082347"

I would like to get version 3 in the version of the results of how to write?

**Comment by mbostock** [comment]
Per the [Release Notes](https://github.com/d3/d3/blob/master/CHANGES.md#shapes-d3-shape), the interpretation of Cardinal spline tension was fixed in 4.0:

> 4.0 fixes the interpretation of the cardinal spline tension parameter, which is now specified as *cardinal*.tension and defaults to zero for a uniform Catmull–Rom spline; a tension of one produces a linear curve.

Tension should typically specified in the range [0,1], so even with the broken interpretation used by 3.x, a tension of -1 is a bit unusual. It looks like you can approximate your old result using a tension of about -3.5.

https://bl.ocks.org/mbostock/58d4fa2e26c0ec32197c27d4cef837e2

An exact match for the interior segments of the spline would be a new tension value of -5, because the length of the tangents was changed from (1 - *tension*) / 2 to  (1 - *tension*) / 6: (1 - -1) / 2 = 1 = (1 - -5) / 6.

However, v4 also fixed the first and last segment of Cardinal splines; in v3 Cardinal splines used a quadratic Bézier for the first and last segment, which… well, which didn’t really make sense, and so there’s no equivalent.

**Comment by winder520** [comment]
The effect is almost, but the arrow can not follow the change?

**Comment by winder520** [comment]
@mbostock  The effect is almost, but the arrow can not follow the change?

**Comment by mbostock** [comment]
Sorry, I don’t understand the question.

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
