### ISSUE TITLE
Rollup not tree-shaking from "d3" package

### ISSUE THREAD

**Issue by curran** [d3/d3#3076]
When creating a custom bundle with ES6 modules from the `d3` package, Rollup includes unnecessary JavaScript in the build.

In the original example [D3 Custom Bundle](http://bl.ocks.org/mbostock/bb09af4c39c79cffcde4), the non-minified bundle `d3.js` is 23.4 Kb, using the following source:

```js
export {
  event,
  select,
  selectAll
} from "d3-selection";
```

In the fork I made [D3 Custom Bundle from "d3" package](https://bl.ocks.org/curran/6d6f1f63d0345e24d4e673ca5ef79019), the non-minified bundle `d3.js` is 185.7 Kb, using the following source:

```js
export {
  event,
  select,
  selectAll
} from "d3";
```

My understanding is that the resulting bundle size should be the same, regardless of whether the modules are exported from packages "d3" or "d3-selection".

This is with package "d3" at version 4.7.2 and Rollup version 0.41.

I thought this might be related to this [change which makes exports implicit](https://github.com/d3/d3/commit/72556dad257c906f5e9da76b1dc2a6475e9c464c#diff-168726dbe96b3ce427e7fedce31bb0bc), which affects versions 4.4.2 and above. As an experiment, I tried the same build using version 4.4.1, which is the most recent version that uses explicit exports. The same problem appears, the resulting non-minified bundle is 181.3 Kb.

FWIW, I also tried setting the Rollup NPM plugin flags explicitly, to try to get it to use `module` only, like this `plugins: [node({module: true, jsnext: false, main: false})],` , to no avail:

Also possibly related to [StackOverflow: Webpack 2 Not Tree Shaking D3.js Properly](http://stackoverflow.com/questions/42143240/webpack-2-not-tree-shaking-d3-js-properly).

I'm not sure if the source of this issue lies with the D3 packages, or with Rollup. I went through all the issues currently in Rollup, and didn't see anything that might be a duplicate of this.

/cc @Rich-Harris

**Comment by Rich-Harris** [comment]
See [this section of the Rollup wiki](https://github.com/rollup/rollup/wiki/Troubleshooting#tree-shaking-doesnt-seem-to-be-working) — `d3` imports from its various submodules, and those `import` declarations are followed even for non-exported bindings because a module might have side-effects. Unfortunately, some things that *look* like side-effects to Rollup actually aren't, but it has to err on the side of caution to guarantee program correctness.

The tree-shaking will hopefully improve over time, but importing directly from submodules is recommended if possible.

**Comment by curran** [comment]
>those `import` declarations are followed even for non-exported bindings

@Rich-Harris Ahhh I see. Interesting. I suppose this is the crux of the issue, and this policy of Rollup prevents using the `d3` package as the "convenience" module it was intended to be.

Closing, as this seems to be the expected behavior with Rollup.

**Comment by mbostock** [comment]
Related rollup/rollup#305. Part of me wonders whether hint annotations could help Rollup in this case, *e.g.*, you’d declare that an import is “pure”, that is considered to not have any side-effects, and thus can be ignored unless directly referenced by the importing module. Yeah, it’s a bit of a pain for library authors to annotate their code this way, and it could be error prone… but on the other hand having library users depend on the internal module structure (or worse, file layout!) is bad too.

**Comment by Rich-Harris** [comment]
Yeah, there's no silver bullet. I've resisted hints thus far for the reasons you described, but it might not be the worst thing to throw into the mix.

If we *did* do something along those lines I'd prefer it not to be tool-specific, so that Webpack users could benefit from it too. (CC @TheLarkInn — Hi Sean, we're talking about adding a comment next to `import` declarations so that bundlers can ignore unused submodules from an 'index module' without having to worry about missing side-effects.) Maybe something like this:

```js
// node_modules/tool/index.js
export { default as foo } from './foo.js'; /*esm pure*/
export { default as bar } from './bar.js'; /*esm pure*/
export { default as baz } from './baz.js'; /*esm pure*/

// my-custom-build.js
export { foo } from 'tool'; // bar and baz are not followed
```

I've been working on a new approach to tree-shaking in a separate Rollup branch, but unfortunately I got sidetracked by other projects and haven't been able to get it into shape, and it's probably diverged quite far from `master` now. But if it eventually pans out it should do a much better job of eliminating false positives. Hopefully I can get back on that soon.

**Comment by TheLarkInn** [comment]
Oh hi Rich. Going to pull in @sokra @jhnns also so they have a bit of context when I bring it up with them. I think this approach could work. What would be happening behind the scenes vs w/o the comment for the statements in that example?

**Comment by Rich-Harris** [comment]
> What would be happening behind the scenes

Good question! At a high level, something like 'only import this module if one of its imported bindings is referenced in the bundle' — so imported modules would be dormant unless

* they were also imported by a declaration that *didn't* have the hint, or
* an 'active' module referenced one of the module's exports

I'm glossing over the gory details and will freely confess I haven't thought about this in any depth at all yet.

**Comment by curran** [comment]
Thrilled that this issue sparked this discussion.

Of the 31 modules exported from d3's [index.js](https://github.com/d3/d3/blob/master/index.js), I believe only one of them, `d3-transition` has a side effect. Perhaps possible to hint for the *existence* of side effects, rather than their *non-existence*?

**Comment by sokra** [comment]
We had a similar discussion in the uglify-js repo on lower level. I would go with the same annotation (even if it's ugly).

``` js
/*#__PURE__*/import { something } from "module";
//#__PURE__ importing my magic module
import { something } from "module2";
```

**Comment by curran** [comment]
>What would be happening behind the scenes

@Rich-Harris I may be naiive here, but it seems like there already exists a [subroutine for side effect detection in Rollup - [hasEffect](https://github.com/rollup/rollup/blob/a53555d213203a17519bcc08eb711b7f94394221/src/ast/Node.js#L45). Wouldn't these hints be implementable by just having that subroutine return `false` if the annotation is present? I suppose the problem would be that the AST node for the import  expression may not have access to the AST node with the hint comment in it...

**Comment by jhnns** [comment]
> Perhaps possible to hint for the existence of side effects, rather than their non-existence

The problem here is that you have to cover the worst case: There is a side-effect in the module and the author does not know about this annotation. So it's probably safer to hint their non-existence.

But I think that the annotation should be in the imported module, not the importing one (as @sokra suggested).

However, why are we talking about introducing a custom annotation instead of teaching library authors to write modules without side-effects? I haven't come across a single instance where modules with side-effects are actually useful. Even polyfills are often better applied explicitly.

In any case, the library author must make the library tree-shakable...

**Comment by mbostock** [comment]
> However, why are we talking about introducing a custom annotation instead of teaching library authors to write modules without side-effects?

In D3’s case, there’s only one import I can think of that has an intentional side-effect, and it’s d3-transition adding *selection*.transition and *selection*.interrupt to the selection prototype. It is also the only import written obviously as a side-effect:

```js
import "./src/selection/index";
```
https://github.com/d3/d3-transition/blob/v1.0.4/index.js#L1

The export from d3-transition in the d3 bundle could (and should?) still be considered pure, though it’s a little bit of a stretch:

```js
export * from "d3-transition";
```
https://github.com/d3/d3/blob/v4.7.2/index.js#L29

Yes, this still has the side-effect of decorating the selection prototype, but the idea is you only want to do that if you explicitly imported a symbol from d3-transition, such as d3.transition. That way the side-effects are not applied unless you specifically opt-in to using d3-transition’s features.

Most of the unused code that ends up in the D3 bundle above is not because that code has a side-effect, but because Rollup can’t positively assert that it doesn’t, and thus conservatively includes it. Making tools smarter is always welcome, but I think annotation hints could be a practical short-term solution since static analysis of side-effects can be challenging.

**Comment by curran** [comment]
I miss the days when Rollup would only include what you need :disappointed: 

>However, why are we talking about introducing a custom annotation instead of teaching library authors to write modules without side-effects?

I strongly agree with this sentiment. Can we add an `assumePure` flag to Rollup and Webpack and banish this whole notion of conservatively including modules because they *might* have side effects? Any function *might* have a side effect. Trying to detect side effects seems like a bad road to go down, especially if detecting whether a module has side effects turns out to be an NP-Complete problem (which I believe it is).

Then we'd be left with the issue of how to tell the bundler to make exceptions for modules that *do* have side effects, like d3-transition. I'd be more than happy to put a list of modules with intentional side effects to "hard-include" in my Rollup or Webpack configuration, because modules with intentional side effects are few and far between (as far as I've seen at least - this would be interesting to get real data on).

Even in the case of d3-transition, the side effect is surprising. Maybe there's a little *hidden dependency* 🌶 going on there. It would be great if the side effect could be eliminated. I'm not sure what form this would take, nor have I thought through if it's even possible to get the same features without the side effect of mutating the *selection* prototype. Maybe it could look something like this in our custom D3 bundle index:

```js
export {
  selectWithTransition as select,
  selectAllWithTransition as selectAll
} from "d3-transition";
```

**Comment by 1wheel** [comment]
> However, why are we talking about introducing a custom annotation instead of teaching library authors to write modules without side-effects?

I'm not sure how to do that when modifying how d3 selections work. [jetpack](https://github.com/gka/d3-jetpack/blob/v2/index.js), for example, adds a translate function: 

```
import {selection} from "d3-selection";
import {transition} from "d3-transition";

import translateSelection from "./src/translate-selection";

selection.prototype.translate = translateSelection;
transition.prototype.translate = translateSelection;
```

Just trying to grab one function from jetpack makes a huge bundle - `export {nestBy} from "d3-jetpack-module"` is 139Kb since all the `selection` and `transitions` is included but not exported. I guess we could get around that by making a separate `selection` and `transition` package for each function we've added, but that seems quite unwieldy (the [original package](https://github.com/gka/d3-jetpack/blob/d3v3/d3-jetpack.js) fit in one file!). Custom annotations or a strict mode might work instead.

**Comment by Rich-Harris** [comment]
@1wheel in the jetpack case, I *think* you probably want to add the following to the Rollup config:

```js
external: [ 'd3-selection', 'd3-transition' ],
global: {
  'd3-selection': 'd3',
  'd3-transition': 'd3'
}
```

That way, a bundler will only include one copy of each, and for `<script>` tag users it should modify the prototypes declared in the main D3 UMD bundle.

**Comment by 1wheel** [comment]
Thanks @Rich-Harris - I think the UMD bundling is set up [correctly](https://github.com/gka/d3-jetpack/blob/v2/build/d3-jetpack.js). 

We were looking to generate a custom d3 build for [each graphic](https://twitter.com/Rich_Harris/status/839593910930456578), but aren't seeing super huge drops in bundle sizes. Just bringing in [scaleLinear](https://github.com/d3/d3-scale/blob/master/src/linear.js) with `export {scaleLinear} from "d3"` makes a 67Kb bundle with what looks like lots of unused code from `d3-array`.  Importing a couple more functions gets us past the AMP approved 50Kb bundle size pretty fast even with minification. 

Totally possible I set something up wrong - I was using this `rollup.config.js`: 

```
import npm from "rollup-plugin-node-resolve";

export default {
  entry: "index.js",
  format: "umd",
  moduleName: "d3",
  plugins: [npm({jsnext: true})],
  dest: "d3.js"
};
```

**Comment by nathancahill** [comment]
Glad to hear this is being discussed, although it might be better if the discussion was happening on the Rollup repo. I updated the proposal I had opened earlier to pure annotations, now that UglifyJS supports marking functions as pure with this annotation: `/*#__PURE__*/`. The proposal is here: https://github.com/rollup/rollup/issues/1293

**Comment by coolcorexix** [comment]
Erm, any final concensus on this? It been three years and we have not had any update on how to mark module as pure. I think this is an essential feature though.

**Comment by sokra** [comment]
Webpack and rollup added a `sideEffects` flag for the package.json to support this case.

https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by SpechtacularDave** [comment]
Sorry to revive this dead issue, but I can't seem to get rollup to treeshake d3 properly even with the sideEffects flag set to false in package.json. I tried asking about it on stackoverflow [here](https://stackoverflow.com/questions/75190142/rollup-not-tree-shaking-d3-js-correctly-even-with-sideeffects-flag-set-to-false) but haven't gotten any responses. For example, if I have a js module file that only consists of:
`import {select} from "d3-selection";
select('#someid');`
when I package with rollup, I'm getting almost 1000 lines of code from d3-selection that is not necessary. Is there any other config that rollup needs? I also tried setting moduleSideEffects to false in rollup.config, but no change. I've got a git repo showing the example above with the output bundle [here](https://github.com/SpechtacularDave/rollupd3treeshake). Thanks for any advice.

**Comment by SpechtacularDave** [comment]
@curran did you ever get treeshaking to work properly? (Please see my previous comment on this issue).

**Comment by curran** [comment]
I looked briefly at your reproduction.

All that code seems necessary to me, to provide all the various methods on selections. Tree shaking just uses the import statements, so it can't possibly know that your code doesn't invoke any methods on the selection you instantiated.

See this line here which shows why your `import { select } from 'd3-selection';` includes all that code: https://github.com/SpechtacularDave/rollupd3treeshake/blob/master/index.bundle.js#L879 It attaches all the methods.

What would you expect to get as output? How do you determine what is necessary and what is not necessary, and how does that differ from what Rollup does?

**Comment by SpechtacularDave** [comment]
Ah I see. Thank you for that explanation. I was thinking that since my code didn't call those methods that they wouldn't be included if using treeshaking. I didn't realize that's not how treeshaking in js works, at least currently. I'm pretty new to d3 and js bundling, so I appreciate you taking the time to explain this to me.

**Comment by curran** [comment]
My pleasure!

I think the term for what you're describing is "dead code elimination", which is in the realm of optimizing compilers.

If you feed the bundle generated by Rollup into Google Closure, which is an optimizing compiler, it _might_ be able to remove unused methods, but I'm not 100% sure it could catch it.

https://developers.google.com/closure/compiler

Good luck!

**Comment by SpechtacularDave** [comment]
Thanks for the Google Closure Rollup plugin suggestion. I just tried it, but it doesn't seem to be removing unused methods (at least with the stock options). I'm getting the same output file size as when I use Terser. I looked through the flags and options for the plugin, but nothing is jumping out to me as something that would enable it to remove unused methods in my example.

Thanks for all your help!
