### ISSUE TITLE
make sure of the public npm org

### ISSUE THREAD

**Issue by c0b** [d3/d3#3086]
there just came in the announcement of free npm Orgs unlimited for open source projects, So I think the d3 can also be a good use case take advantage of it, at least you may register this one  https://www.npmjs.com/org/d3 before anyone else register it for non-d3 related

I have been using some public organized code for a while (like `@google-cloud/bigquery`), pretty appreciate this kind of code organizing, so the d3 modules can also be `@d3/scale` `@d3/format` `@d3/geo` ... then after npm install, it put all code under `./node_modules/@d3/...`

**Comment by mbostock** [comment]
I’ve already registered the [d3 user](https://www.npmjs.com/~d3) with npm, and no one is allowed (at least currently) to create an organization with the same name as an existing user. I could convert the d3 user to an organization, but the current workflow requires that I then rename the d3 user to something else, and since this is not of immediate pressing concern I do not plan on doing this. But thank you for the reminder.
