### ISSUE TITLE
Hard versioning leads to huge list of forks

### ISSUE THREAD

**Issue by DaSchTour** [d3/d3#3088]
I would like to suggest using semver ranges in package.json instead of specific versions. I currently have a lot of forks installed through jspm and a lot duplication in my bundle because JSPM can't resolve the dependencies properly.

The list currently looks like this and all this dependencies are included into my bundle. Even just including patch level through ~ would allow to clean this up a lot. Only d3-array and d3-format would need works because they have a difference in major version.
             npm:d3-array 1.0.2 1.1.1
        npm:d3-collection 1.0.2 1.0.3
             npm:d3-color 1.0.2 1.0.3
          npm:d3-dispatch 1.0.2 1.0.3
              npm:d3-drag 1.0.2 1.0.4
               npm:d3-dsv 1.0.3 1.0.5
              npm:d3-ease 1.0.2 1.0.3
            npm:d3-format 1.0.2 1.1.1
       npm:d3-interpolate 1.1.3 1.1.4
              npm:d3-path 1.0.3 1.0.5
          npm:d3-quadtree 1.0.2 1.0.3
         npm:d3-selection 1.0.3 1.0.5
              npm:d3-time 1.0.4 1.0.6
       npm:d3-time-format 2.0.3 2.0.5
             npm:d3-timer 1.0.4 1.0.5
        npm:d3-transition 1.0.3 1.0.4

**Comment by mbostock** [comment]
My intuition is that this would be a bad idea, but I’m open to a discussion on this topic.

The heart of the problem is that the `d3` module is simply the concatentation of the D3 micromodules. If `d3`’s dependencies are specified as version ranges, then the version of `d3` is essentially meaningless because it says nothing about what it contains: unlike a “normal” npm package, there is no code in `d3` itself (other than the [index.js](https://github.com/d3/d3/blob/master/index.js) which is just a bunch of `export * from "d3-foo";`). 

If you have multiple copies of D3 modules in your node_modules, that suggests that you have multiple copies of the `d3` module at different versions. If D3 were not modular (as in v3 days), each copy of `d3` would have its own code, which is worse than what happens in v4, since many version bumps in `d3` v4 do not bump the version of every dependent D3 module. So, having multiple copies of D3 in v3 looks better than it does in v4 (since you only see that the `d3` module is duplicated), but in fact it’s worse because it’s equivalent to having all 30 D3 micromodules duplicated. In v4 you now see just the micromodules that are duplicated.

Anyway, all this is to say that if you have multiple versions of `d3`, then you should expect to see multiple versions of the D3 micromodules in your npm tree. If you don’t want multiple versions, you must either make sure you always use the same exact version of `d3`, or better, you should switch from using the `d3` default bundle and instead use only the D3 micromodules.

Changing `d3` to specify a version range for its dependencies would mean that installing an exact version of `d3` would be meaningless, because an exact version of `d3` would no longer specify an exact version of its constituent micromodules.

**Comment by DaSchTour** [comment]
@mbostock I guess you missunderstood how this happends. Most important is to see, that in my application D3 is bundled with JSPM which means that I ship all lot the modules listed above more than once to every client accessing my application. That's a total no-go.
The big question is, why does d3 depend on exactly d3-array@1.0.2 and on d3-chord@1.0.3 which depends exactly on d3-array@1.1.1 and d3-path@1.0.5 while d3 depends on  exactly d3-path@1.0.3 and so on. There are a lot of such version conflicts between d3 and dependencies of it's submodules. So well I would agree, that d3 as a container may have absolut versions. But there shouldn't be any submodule that conflict with versions defined by d3 itself, because that's where all the mess is coming from.

**Comment by mbostock** [comment]
The reason for `d3`’s exact dependencies is described in my previous comment.

Contrary to your statemnet, d3-chord’s dependencies, along with all other dependencies in the D3 micromodules, are *not* specified as exact versions: they are specified as version ranges, typically depending only on the major version number. (There might be some that use `^` to depend on a minor feature, but I don’t recall any offhand.) You can verify this by looking at the [package.json](https://github.com/d3/d3-chord/blob/v1.0.4/package.json#L32-L35).

**Comment by DaSchTour** [comment]
Well, this would mean that JSPM's module resolution is broken, but only with D3 🤔 
That's very very very strange. So I'll have to choose to use D3 or JSPM cause both together don't play well. I'm getting really tired of this versioning, moduling and bundeling, it just don't works.

**Comment by mbostock** [comment]
Here are some options that come to mind:

1. Use a single version of `d3` in your application.

2. Use the D3 micromodules instead of `d3` in your application.

3. Investigate whether this is a bug in JSPM and if it is, report it.

4. Create your own `d3` package (by forking this repository) and specify the dependencies using version ranges.
