### ISSUE TITLE
Anonymous function exports causing problems

### ISSUE THREAD

**Issue by TomiS** [d3/d3#3089]
I'm using `d3.js` through `Victory.js` and bundling my app with `Webpack 2` and `Babel 6`. I'm also using babel preset `["es2015", { "modules": false }]` to enable tree shaking. Everything builds fine in webpack-dev-server but the production build fails only because d3 modules cannot be resolved. Production build works if I remove `{ "modules": false }` flag and thus stop using native ES2015 modules. I finally understood the build fails because there are anonymous exports in d3 code and for some reason the build process doesn't like that. I managed to prove this and fix errors temporarily by manipulating d3 source like this:
```
export default function() {
```
=>
```
export default function voronoi() {
```
The example is from this line:
https://github.com/d3/d3-voronoi/blob/master/src/voronoi.js#L5

But of course, solving my problem this way would require forking d3 and changing all exports in every sub module.

My questions are: Is this by design? Should ES2015 native modules work with anonymous exports like this? Or more specifically, do ES2015 native modules support re-exporting anonymous exports as named exports. I tried to research this topic but didn't find anything about that exact case of re-exporting anonymous functions as named exports. Am I doing something wrong with my babel/webpack config or is this an issue in d3 that could be improved by naming all exports explicitly?

**Comment by mbostock** [comment]
Those aren’t anonymous exports. They are default exports, which is a basic feature of ES2015 modules. See:

http://2ality.com/2014/09/es6-modules-final.html#default-exports-one-per-module

Naming the function doesn’t change the name of the export; it’s still the default export. The only effect that should have is if you were to look at a reference to the function at runtime, *function*.name would be “voronoi”. However, even this often goes away due to minification; UglifyJS for example will strip function names. That’s because setting the function name does not affect its symbol, which is determined by the name you use when you import the default export. For example, this import will refer to the default export from voronoi.js as `foo`:

```js
import foo from "./voronoi";
```

All this is to say that if default exports are causing you trouble, something is wrong with your bundler (Webpack / Babel). I’m not familiar enough with your toolchain to identify precisely where the problem is. My guess is the problem is with [resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolve-mainfields). I believe that Webpack 2 prefers the `browser` entry point to the `module` entry point if your target is `web`, and this would be bad in D3’s case because importing from `d3` would use the pre-built browser bundle rather than the ES2015 modules.

Anyhow, you’ll need to either ask in a suitable Webpack forum or on Stack Overflow or elsewhere if you require further assistance. I’m afraid that’s about all I know.

**Comment by TomiS** [comment]
Thank you for your response @mbostock. It was really helpful. I still haven't got my build working with `module` as a primary mainField but at least I managed to make some kind of a successful build by setting mainField to `['browser', 'main']`.

ps. Thanks for the fine library.

**Comment by curran** [comment]
FWIW, this might be helpful [D3 Custom Bundle with Webpack](https://bl.ocks.org/curran/3b0ab871cffe021aa972680c3f4f62d3)
