### ISSUE TITLE
Chrome 57.0.2987.133 (64-bit) breaks charts

### ISSUE THREAD

**Issue by stripathix** [d3/d3#3091]
Updating chrome to latest version 57.0.2987.133, suddenly my charts are broken.
Ref: http://ec2.buser.net/bnforecast/meteogramv2/#!/app/dashboard?start=KBTP&product=MAV

Reason being this always give 0px in return.

d3.select('#bntextrefmeteo').style("height") 

This gives correct results though
d3.select('#bntextrefmeteo').style("height") 

D3 version used is:
  "d3": "4.7.3",

**Comment by mbostock** [comment]
Your two code snippets are identical, so I can’t speculate what the problem is here. In any event, your code likely depends on some browser quirk, or you have discovered a bug in Chrome 57; the behavior you describe is not likely to be a bug in D3, as [the implementation](https://github.com/d3/d3-selection/blob/v1.0.5/src/selection/style.js#L30-L32) of [*selection*.style](https://github.com/d3/d3-selection/blob/master/README.md#selection_style) is simply to return the computed value of whatever style property you specify.

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by stripathix** [comment]
Roger that I'll ask this on stackoverflow with more information.

Correction:
This gives correct results though
d3.select('#bntextrefmeteo').style("width")

Thank You!
:-)

**Comment by mattspaulding** [comment]
I was having the same issue. A newer version of chrome fixed it.
