### ISSUE TITLE
if i use zoom.translateExtent i get NaN for event.transform.x and event.transform.y 

### ISSUE THREAD

**Issue by ghyatzo** [d3/d3#3100]
Hello,

I tried to wrap my head around this even looking at the d3 code to try to understand if i've been doing something wrong.
But i couldn't find any cause of such behaviour.

```
this.zoom = d3.zoom()
        .scaleExtent([1, Infinity])
        .translateExtent([0, 0], [this.width, this.chartHeight])
        .on('zoom', () => { this.zoomed(); });

this.svg.append('rect')
        .attr('class', 'zoom')
        .attr('width', this.width)
        .attr('height', this.chartHeight)
        .attr('transform', 'translate(' + this.margin.left + ',' + this.margin.top + ')')
        .style('fill', 'none')
        .style('pointer-events', 'all')
        .call(this.zoom);

zoomed () {
    var transform = d3.event.transform;
    this.x.domain(transform.rescaleX(this.x2).domain());
    this.brushOverlay.call(this.brush.move, this.x.range().map(transform.invertX, transform));

    this.render();
  }
```
If i comment out the `.translateExtent([0, 0], [this.width, this.chartHeight])` everything works except for the panning constraints, of course.
The same thing happens if i use `.extent()` method.

If instead i keep that line of code, if i try to log the `transform` variable i get the scale right as usual, but the _transform_.x and _transform_.y values as `NaN` which then triggers all sorts of errors.

I've tried this with both a numerical linear scale and a time scale.

**Comment by mbostock** [comment]
When reporting an issue, please include a link to a live example, preferably on [bl.ocks.org](http://bl.ocks.org) or [RunKit](https://runkit.com/npm/d3), or as a pull request in the [appropriate repository](https://github.com/d3) with new unit tests, that demonstrates that the described behavior is not the [expected behavior](https://github.com/d3/d3/blob/master/API.md). Use only the minimum amount of code necessary to reproduce the unexpected behavior.

Non-actionable bugs may be temporarily closed until you provide additional information. If you can’t isolate the bug any further, please let me know and I will try to help. However, I beg your patience: I must balance your request against many other responsibilities—fixing other bugs, answering other questions, new features, new documentation, *etc.* Please also consider asking for help on [Stack Overflow](https://stackoverflow.com/tags/d3.js).

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by mbostock** [comment]
The problem is your call to *zoom*.translateExtent:

```js
zoom.translateExtent([0, 0], [this.width, this.chartHeight])
```

You are passing two arguments when you should be passing one:

```js
zoom.translateExtent([[0, 0], [this.width, this.chartHeight]])
```

**Comment by ghyatzo** [comment]
I guess the time has come to finally take a pause, since i've spent the last 2 hours trying to understand what was going on...

Next time i'll check the docs 5 more time before wasting anyone's time...
Thank you so much!
