### ISSUE TITLE
Zoom jumps with Firefox

### ISSUE THREAD

**Issue by jcorreia** [d3/d3#3118]
Hi,
I will try to explain what I´ve discovered using d3 v4, and zooming in and out in Firefox.
You can check this in this example: https://bl.ocks.org/iamkevinv/0a24e9126cd2fa6b283c6f2d774b69a2

I´ve noticed that when we try to zoom in with firefox, the transition are not smooth. It seems that it has only 3 or 4 possible views, with the zoom "jumps" being to big.
With Chrome and Edge everything looks ok, zooming in and out is smooth, and the transitions with 8 possible views.

I hope you understand my explanation. Is this a Firefox bug ?

Thanks :)

**Comment by mbostock** [comment]
I tried it, and the rendering did seem a little choppy in Firefox, but that’s not a D3 bug—that’s just Firefox being slower to render than other browsers. A few things you can try that might improve performance (in some browsers):

* Use the [vector-effect: non-scaling-stroke](https://www.w3.org/TR/SVGTiny12/painting.html#NonScalingStroke) style property rather than changing the stroke-width dynamically.
* [Re-project the path](https://bl.ocks.org/mbostock/eec4a6cda2f573574a11) rather than changing the transform, preferably with [pre-projected planar geometry](https://bl.ocks.org/mbostock/09dd5ad7d6bfd40187e0).
* Apply [dynamic simplification and clipping](https://bl.ocks.org/mbostock/c1c0426d50ca8a9f4c97).
* Use Canvas instead of SVG.

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by jcorreia** [comment]
Hi,
thanks for your kick reply and explanation.
I was pretty sure that it was a Firefox problem, but wanted to be sure.

I´m pretty new to D3, but I´m loving it already and will be checking your advices.I
n the future I will post in Stack Overflow instead ;)

Thanks :)
