### ISSUE TITLE
Transform output is inconsistent with developer experience.

### ISSUE THREAD

**Issue by trusktr** [d3/d3#3119]
For example, if I apply a transform like

```js
    this.selection
      .call(this.zoom.transform, d3
        .zoomIdentity
        .scale(2)
        .translate(3, 4)
      );
```

I would expect to see in the DOM:

```html
<g transform="scale(2) translate(3, 4)"></g>
```

but instead d3 applies in a different order with different values:

```html
<g transform="translate(6, 8) scale(2)"></g>
```

When inspecting the DOM, this makes it more difficult to inspect/debug what is happening.

The HTML should be

```html
<g transform="translate(6, 8) scale(2)"></g>
```

only if the user wrote

```js
    this.selection
      .call(this.zoom.transform, d3
        .zoomIdentity
        .translate(6, 8)
        .scale(2)
      );
```

**Comment by trusktr** [comment]
I am guessing this is because the transform output internals are designed to output transform in only one format, regardless of the way it was created through d3 API. Would be cool to have consistency!

**Comment by mbostock** [comment]
Right, that’s not how the [Zoom Transforms](https://github.com/d3/d3-zoom/blob/master/README.md#zoom-transforms) are designed; it does not record the individual transforms you apply (in order). Instead, transforms are [represented as a matrix](https://en.wikipedia.org/wiki/Transformation_matrix), and transform operations derive a new matrix. So, the two operations you describe result in identical transforms which are formatted identically by *transform*.toString:

```js
var t1 = d3.zoomIdentity.scale(2).translate(3, 4);
var t2 = d3.zoomIdentity.translate(6, 8).scale(2);
```

Both result in the same internal state:

```js
Transform {k: 2, x: 6, y: 8}
```

And thus the same stringified form, `translate(6, 8) scale(2)`.

**Comment by mbostock** [comment]
As noted in the issue template, please file issues in the appropriate repository, such as [d3-zoom](https://github.com/d3/d3-zoom),  rather than here.

If you have a question about D3’s behavior and want to discuss it with other users, also consider [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js), the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
