### ISSUE TITLE
can we tell d3.stack() to use a minimized stack height for zero value?

### ISSUE THREAD

**Issue by cnweibo** [d3/d3#3121]
@mbostock ,
thanks for your great data visualization library, i come from hightcharts.
Sorry for write question here , no stack overflow help on this point.

Can D3Js V4 support something similar with minPointLength from highcharts? 
The requirement is: when there are some chart segments whose height is 0(returned by the stack layout call), we should be able to  give a minimized value, say, 1px, for example. 
Currently,always zero value returned which will cause the bar chart segment is 0 and no visual feedback. 

If i use something like following: 
```
 .attr("height", function(d) {
      var h = height - y(d.frequency);
      return (h <= 0) ? 3 : h;//you can give your min pixel replace 3 with whatever minpixel you wish to give.
  });
```
It is ok for the pure bar chart, but for stacked bar chart, successive segments may override the minimized zero bar segment. 
Can you give some advise or consider give a new feature into d3js stack library?

**Comment by mbostock** [comment]
You could change [*stack*.value](https://github.com/d3/d3-shape/blob/master/README.md#stack_value) to return some small epsilon value rather than zero, or similarly, you could pre-process your data to replace the zeroes with some small positive value. Alternatively, it might be less misleading to have an annotation on columns that are missing data or have zero value, rather than pretending that the values are non-zero.

I appreciate that you’ve already looked on Stack Overflow, but as a reminder, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by Arkadiy292** [comment]
Thank you! 🤗 

--
Отправлено конфиденциально с Tutanota. Требуйте сегодня Ваш шифрованный ящик почты!
https://tutanota.com

1. Авг 2017 01:29 от notifications@github.com:
