### ISSUE TITLE
Any interest in a data driven document library for Java which uses the same API as d3.js?

### ISSUE THREAD

**Issue by benelot** [d3/d3#3125]
Am I allowed to name it d3.java or should I use another name? What license would you recommend given that I would implement the same API?

**Comment by mbostock** [comment]
Since it won’t be an “official” port and is likely to fall out-of-sync with this repository (and because I imagine it will have some substantial differences due to it being in a different language and a different runtime), I ask that you *not* use “D3” in the name. However, you are more than welcome to document in your README that your API is inspired or influenced or (even) intended to be compatible with D3.js.

Assuming that you base your implementation off this one here, then I’d also ask you to license your code under D3’s BSD license as is standard practice for forks and derived works. I think you can mix this with additional licenses for your independent works if they are mixed together, but IANAL so you probably shouldn’t ask me for advice…

If you’re doing a “clean room” implementation of the D3 API—which would be substantially more difficult!—then I think the answer is a little murkier, see [Oracle America, Inc. v. Google, Inc.](https://en.wikipedia.org/wiki/Oracle_America,_Inc._v._Google,_Inc.).
