### ISSUE TITLE
getBBox() returns 0 on click with selectAll

### ISSUE THREAD

**Issue by mitenadesign** [d3/d3#3130]
I wanted to get Bounding Box data (x, y, width, and height) of group elements with the class of `.zoomTarget` on click. Everything goes fine on Chrome, Firefox, Edge and even Internet Explorer. But in Safari, it returns 0 for x, y, width, and height. When I add `parentNode ` to this it works fine, but it gives the data of the parent element I think which is not my target.

```
<g class="zoomTarget">
    <rect class="cls-22" x="3345.941" y="3252.744" width="257.842" height="115.165"></rect>
</g>
<g class="zoomTarget">
    <path id="Grand_North_FG-2" data-name="Grand North FG" class="cls-77" d="M3743.812,1194.156a139.514,139.514,0,0,0-185.223,65.26l-0.96,2.879a139.514,139.514,0,0,0,65.26,185.224L5395.476,2295.9s364.689,142.037,297.509,542.235-468.337,422.271-468.337,422.271H3277.4c-75.817,0-138.2,61.421-139.158,137.238v4.8c-0.96,77.736,61.421,141.077,139.158,143,0,0,1929.974-1.92,1980.838-3.839,69.1-2.879,608.455-51.824,723.62-619.971,116.124-573.905-361.81-828.228-361.81-828.228Z" transform="translate(2 -13.424)"></path>
    <text class="cls-78" transform="translate(3810.713 3426.197)">GRAND NORTH</text>
    <text class="cls-79" transform="translate(4325.982 1635.587) rotate(26.053)">GRAND NORTH</text>
</g>
```

```
d3.selectAll(".zoomTarget").on("click", function() {

    var bbox = this.getBBox()

    console.log(bbox.width); //returns 0
    console.log(bbox.height); //returns 0
    console.log(bbox.x); //returns 0
    console.log(bbox.y); //returns 0

});
```

**Comment by mbostock** [comment]
Hello! This issue appears to concern the behavior of [*locatable*.getBBox](https://www.w3.org/TR/SVG/types.html#__svg__SVGLocatable__getBBox), which is a browser-native method rather than a D3 method. Therefore I suggest you use [Stack Overflow](https://stackoverflow.com) to ask for help, and consider filing a Safari bug if you think this is a violation of the SVG specification.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
