### ISSUE TITLE
Add sideEffects: false to package.json. 

### ISSUE THREAD

**Issue by TheLarkInn** [d3/d3#3131]
Hello D3 Family!!!!! @TheLarkInn from [webpack](https://github.com/webpack) here! 

We have been working on a new feature for webpack 4+ which allow's library authors to add a special field to package.json allowing them to declare that their libraries that have "reexports" in them do not contain side effects!

#### Tiny Backstory
Because webpack implements the Harmony Module Specification to spec, we include code that was reexported (even if it wasn't used). This is because all code [per spec] must be eval'd). The beautiful news is that we do not have to implement _exactly to spec_. So we have created what is called "pure-module". webpack as imports are being resolved will also check to see if the module is pure (which is indicated through the `pure-module` flag in the package.json fields). Therefore, there would be no bundle size difference between the following examples:

```
import {bottomAxis} from "d3-axis";
```

and 

```
import bottomAxis from "d3-axis/direct/path/to/d3AxisBottom"
```

#### Proposal
If there are no side-effects within the D3 packages in places where re-exports occur, then I'd love to propose that all D3 packages add `pure-module: true` to their package.json. 

#### Pros
Developers (using webpack) get huge perf wins by doing nothing.

#### Cons
Bit more work to get it all done. 

Please let me know if you have any questions, the webpack team is really anxious to help in any way if we can (that means, submitting PR's, adding issues to individual repo's to track, etc). 

sideEffects: true
- [x] [d3-format](https://github.com/d3/d3-format) ([src/defaultLocale.js](https://github.com/d3/d3-format/blob/master/src/defaultLocale.js))
- [x] [d3-time-format](https://github.com/d3/d3-time-format) ([src/defaultLocale.js](https://github.com/d3/d3-time-format/blob/master/src/defaultLocale.js))
- [x] [d3-transition](https://github.com/d3/d3-transition) ([src/selection/index.js](https://github.com/d3/d3-transition/blob/master/src/selection/index.js))

sideEffects: false
- [ ] [d3](https://github.com/d3/d3)
- [x] [d3-array](https://github.com/d3/d3-array)
- [x] [d3-axis](https://github.com/d3/d3-axis)
- [ ] [d3-brush](https://github.com/d3/d3-brush)
- [x] [d3-chord](https://github.com/d3/d3-chord)
- [x] [d3-color](https://github.com/d3/d3-color)
- [x] [d3-contour](https://github.com/d3/d3-contour)
- [x] [d3-delaunay](https://github.com/d3/d3-delaunay)
- [x] [d3-dispatch](https://github.com/d3/d3-dispatch)
- [x] [d3-drag](https://github.com/d3/d3-drag)
- [x] [d3-dsv](https://github.com/d3/d3-dsv)
- [x] [d3-ease](https://github.com/d3/d3-ease)
- [x] [d3-fetch](https://github.com/d3/d3-fetch)
- [x] [d3-force](https://github.com/d3/d3-force)
- [x] [d3-geo](https://github.com/d3/d3-geo)
- [x] [d3-hexbin](https://github.com/d3/d3-hexbin)
- [x] [d3-hierarchy](https://github.com/d3/d3-hierarchy)
- [x] [d3-interpolate](https://github.com/d3/d3-interpolate)
- [x] [d3-path](https://github.com/d3/d3-path)
- [x] [d3-polygon](https://github.com/d3/d3-polygon)
- [x] [d3-quadtree](https://github.com/d3/d3-quadtree)
- [x] [d3-random](https://github.com/d3/d3-random)
- [x] [d3-scale](https://github.com/d3/d3-scale)
- [x] [d3-scale-chromatic](https://github.com/d3/d3-scale-chromatic)
- [x] [d3-selection](https://github.com/d3/d3-selection)
- [x] [d3-shape](https://github.com/d3/d3-shape)
- [ ] [d3-tile](https://github.com/d3/d3-tile)
- [x] [d3-time](https://github.com/d3/d3-time)
- [x] [d3-timer](https://github.com/d3/d3-timer)
- [ ] [d3-zoom](https://github.com/d3/d3-zoom)

**Comment by mbostock** [comment]
Great! Thanks for the request.

How can we test that it is working as intended? Most D3 modules should be side-effect free, but I know of at least a few places that are not, and I don’t know whether there is a way to restructure them to make them “pure”. Some examples:

* [defaultLocale.js](https://github.com/d3/d3-time-format/blob/master/src/defaultLocale.js) in [d3-time-format](https://github.com/d3/d3-time-format) initializes the default locale to en-US; this affects the value of d3.timeFormat, d3.timeParse, d3.utcFormat and d3.utcParse.

* Likewise [defaultLocale.js](https://github.com/d3/d3-format/blob/master/src/defaultLocale.js) in [d3-format](https://github.com/d3/d3-format) initializes the default locale to en-US; this affects the value of d3.format and d3.formatPrefix.

* [selection/index.js](https://github.com/d3/d3-transition/blob/master/src/selection/index.js) in [d3-transition](https://github.com/d3/d3-transition) modifies d3.selection.prototype.

I’m not sure if there are others. My guess is that the rest should be considered pure but I don’t know how to verify that.

**Comment by curran** [comment]
This is awesome! So glad to see some ideas from the original discussion in https://github.com/d3/d3/issues/3076 are coming to fruition.

**Comment by TheLarkInn** [comment]
> How can we test that it is working as intended? 
For now you could pull down the PR to test it out. (In the future we are working on [webpack-canary](https://github.com/webpack-contrib/webpack-canary) which can help us and everyone else test webpack versions/commits/branches against anything they want. 

Currently today the behavior is this (I'm using a plugin in VSCode that calculates the cost based on way it is imported): 

**Larger sized because reexported code is being evaluated and included in bundle even if not used**
![d3importlarge](https://user-images.githubusercontent.com/3408176/29088709-9bedf31a-7c3f-11e7-8089-a142565baa61.PNG)

**Smaller sized because importing directly from module w/ no reexports**
![d3importsmall](https://user-images.githubusercontent.com/3408176/29088755-c09b0932-7c3f-11e7-8dc4-b9db7be2f3c1.PNG)

So with this pure-module change, you will know its _working_ in that you can use either syntax seen above and the size should be representative of the second image. (aka it should be small no matter what for any pure modules). 

>  Most D3 modules should be side-effect free, but I know of at least a few places that are not, and I don’t know whether there is a way to restructure them to make them “pure”. 

I think there are going to be times where its not really avoidable and that's totally fine. If that's the case you can leave the property off for those specific modules and I think that's totally fine. In terms of suggestions to do it another way, I'm not quite sure what would be the _easiest_ approach or if even possible. 

Once webpack-canary is closer to a place where it could be leveraged in lets say unit/functional tests, I'll let you know, but otherwise if you wanted to try it out earlier you can try and run webpack from [this PR](https://github.com/webpack/webpack/pull/5435).

Let me know if there's any other ways we can help. When I find some time in the near future, I'll try and run the PR locally against a modded package.json file for d3 and make sure it is doing the expected behaviors myself. Thank you for the collaboration. This is going to be an awesome out of the box perf win when people use d3 with webpack 4 and that's what excites me the most.

**Comment by martgnz** [comment]
@TheLarkInn, any news on this?

**Comment by erosenberg** [comment]
Not sure if related, but I'm getting the following error from ESLint because of the way that these modules are exported/imported:

```
[eslint] 'd3-scale' should be listed in the project's dependencies. Run 'npm i -S d3-scale' to add it (import/no-extraneous-dependencies)
```

**Comment by mbostock** [comment]
@erosenberg They are listed as dependencies; see the [package.json](https://github.com/d3/d3/blob/v4.12.0/package.json#L43-L74).

**Comment by erosenberg** [comment]
@mbostock - thanks for your speedy reply! I believe it meant my project's `package.json` and not `d3`'s. Even still, ESLint should recognize that it's a dependency of a dependency, so this may just be an ESLint issue.

**Comment by TheLarkInn** [comment]
I'll be giving more of an update as webpack 4 draws near. Thanks for all the patience folks.

**Comment by martgnz** [comment]
@TheLarkInn Any news on this now that v4 is out?

**Comment by marcofugaro** [comment]
Nice! So when d3 adds `sideEffects: false` to its package.json, it will allow us to do
```js
import { scaleLinear } from 'd3'
```
without thinking about it?

**Comment by TheLarkInn** [comment]
Yess that correct. So the change can come by adding sideEffects: false today at the package.json. I know there are some exports which do prototype things, however the only sideEffects we are concerned about are the ones that cause other exports within a module to be affected

**Comment by TheLarkInn** [comment]
That is correct!!! So to clarify the only side effects that sideEffects:
false is really caring about, is between existing exports of the same
package. For example if
*index.js*
```
import {a} from "./utils";

```

*utils.js*
```
import {a} from "./a"
import {b} from "./b"
import {c} from "./c"

a = b+c; // this is a side effect at the module level because you would
need to pull in all deps from here
export {a, b, c};
```

Then this would not qualify for sideEffects: false.

Does that make sense?

**Comment by tomwanzek** [comment]
@TheLarkInn To continue your clarification, what about inter-package side-effects? Specifically for D3:
`d3-transition` and `d3-selection-multi` have side-effects on `d3-selection` by extending the prototype of one of its core exports, `Selection`.

According to your last comment, these side-effects would not require a `sideEffects: true` statement in and of themselves. Could you kindly confirm this understanding?

**Comment by marcofugaro** [comment]
Wait, does it also works if I put `sideEffects: false` to MY project's package.json? (where I import d3)

Or do we have to wait for d3 to publish its updated package.json?

**Comment by TheLarkInn** [comment]
Here is a better explanation that I provided for a user on Stack Overflow. Please let me know if this answers your questions. 

https://stackoverflow.com/a/49203452/1624684

**Comment by TheLarkInn** [comment]
@marcofugaro it will only be specific to your code and not other node modules.

**Comment by TheLarkInn** [comment]
With this information in mind would it be safe to say we can add this flag in the top d3 package?

**Comment by mbostock** [comment]
@TheLarkInn I haven’t done this because I haven’t had time to find where all the side-effects are in D3. I identified a few likely cases above https://github.com/d3/d3/issues/3131#issuecomment-321025584, but there could be more, and I’m not sure how I would easily discover them. I don’t feel safe turning this on without someone surveying the code and making sure it won’t break users.

**Comment by TheLarkInn** [comment]
Totally understandable and no worries. Just wanted to double-check!! Keep up the killer work.

**Comment by mbostock** [comment]
If I understand the design of the sideEffects flag correctly, we can’t set sideEffects: false on the top-level d3 package because this package imports both d3-selection and d3-transition, and d3-transition modifies the d3.selection.prototype. So, if we set sideEffects: false, if you

```js
import {select, selectAll} from "d3";
```

you’ll no longer be able to call `selectAll(…).transition()` because webpack will not include the import of d3-transition which applies the side-effect.

That said, I don’t understand how the sideEffects flag applies recursively to packages. If d3 has sideEffects: true, d3-transition has sideEffects: true, and (say) d3-scale and d3-selection have sideEffects: false, will webpack be smart enough not to pull in d3-scale in the above case?

**Comment by mbostock** [comment]
Per https://github.com/d3/d3/issues/3131#issuecomment-321025584, this is my best guess as to which D3 modules have side-effects according the definition above.

My current plan is not to test whether these flags are correct (because it would be a lot of work), but to release them and see if people complain. If someone who uses webpack wants to volunteer to verify these flags and submit PRs to every D3 module, that’d be fantastic.

- [ ] d3 sideEffects: true
- [ ] d3-array sideEffects: false
- [ ] d3-axis sideEffects: false
- [ ] d3-brush sideEffects: false
- [ ] d3-chord sideEffects: false
- [ ] d3-color sideEffects: false
- [ ] d3-contour sideEffects: false
- [ ] d3-delaunay sideEffects: false
- [ ] d3-dispatch sideEffects: false
- [ ] d3-drag sideEffects: false
- [ ] d3-dsv sideEffects: false
- [ ] d3-ease sideEffects: false
- [ ] d3-fetch sideEffects: false
- [ ] d3-force sideEffects: false
- [ ] d3-format sideEffects: true ([src/defaultLocale.js](https://github.com/d3/d3-format/blob/master/src/defaultLocale.js))
- [ ] d3-geo sideEffects: false
- [ ] d3-hexbin sideEffects: false
- [ ] d3-hierarchy sideEffects: false
- [ ] d3-interpolate sideEffects: false
- [ ] d3-path sideEffects: false
- [ ] d3-polygon sideEffects: false
- [ ] d3-quadtree sideEffects: false
- [ ] d3-random sideEffects: false
- [ ] d3-scale sideEffects: false
- [ ] d3-scale-chromatic sideEffects: false
- [ ] d3-selection sideEffects: false
- [ ] d3-shape sideEffects: false
- [ ] d3-tile sideEffects: false
- [ ] d3-time sideEffects: false
- [ ] d3-time-format sideEffects: true  ([src/defaultLocale.js](https://github.com/d3/d3-time-format/blob/master/src/defaultLocale.js))
- [ ] d3-timer sideEffects: false
- [ ] d3-transition sideEffects: true ([src/selection/index.js](https://github.com/d3/d3-transition/blob/master/src/selection/index.js))
- [ ] d3-zoom sideEffects: false

**Comment by mbostock** [comment]
Upon further reflection, I don’t think d3-format and d3-time-format are considered side-effects according to the description above, since the side-effect in src/defaultLocale.js is simply to set the values of the bindings that are exported by that module; it’s not modifying anything exported by another module.

**Comment by mindrones** [comment]
Great to see this, thanks!

I tried using [`acorn-has-side-effect`](https://github.com/ForbesLindesay/acorn-has-side-effect) [1], which is 5 years old now so not very reliable (in fact it marked ALL of the d3 modules as side-effectful), but maybe this is the way to go?

[1] https://gist.github.com/mindrones/3480b493d254c331b004fd4018c6e8cd

**Comment by mbostock** [comment]
I think that meaning of side-effects is different than the meaning of the sideEffects flag at the package.json.

I *believe* the sideEffects flag specifically refers to side-effects that happen when a symbol is imported, and whether those side-effects would be visible to things that are exported *by a different file* (or package).

For example, d3-transition is considered to have side-effects because importing it modifies d3-selection’s d3.selection.prototype. But as a counterexample, even though d3-time-format has a side-effect on import of initializing the default locale, this is not considered a side-effect because the initialization happens in the same file that defines the symbols being exported (see [src/defaultLocale.js](https://github.com/d3/d3-time-format/blob/master/src/defaultLocale.js)).

At least, that’s my understanding.

**Comment by stof** [comment]
@mbostock your understanding is also mine. This is about having side effects on other modules.

**Comment by xulin-lll** [comment]
> 如果我正确理解sideEffects标志的设计，则无法在顶级d3包上设置sideEffects：false，因为此包同时导入了d3-selection和d3-transition，并且d3-transition修改了d3.selection.prototype 。因此，如果我们设置sideEffects：false，如果您
> 
> ```js
> 从“ d3 ”导入 { select，selectAll } ; 
> ```
> 
> 您将无法`selectAll(…).transition()`再拨打电话，因为Webpack将不包含导入d3转换的效果，而导入会产生副作用。
> 
> 就是说，我不明白sideEffects标志如何递归地应用于包。如果d3具有sideEffects：true，则d3-transition具有sideEffects：true，并且（例如）d3-scale和d3-selection具有sideEffects：false，在上述情况下，webpack是否足够聪明，不会拉入d3-scale？

1111

**Comment by Beelucky** [comment]
The Fetch json is unload on apache cordova undermatch gonna be done so on..

think so transition project of d3.refextor

**Comment by mbostock** [comment]
Hey @TheLarkInn, I know it took me a few years, but I’ve finally marked all the D3 modules as sideEffects: false (or sideEffects: true as appropriate). But I still am not clear on whether to mark the `d3` package itself as sideEffects: false: if `d3` imports a package with a side-effect, does that mean that I should set sideEffects: true on `d3`, or not?

**Comment by Fil** [comment]
Following [this tutorial](https://webpack.js.org/guides/getting-started/) I've created a simple webpack application with src/index.js containing: 
~~~
import {select} from "d3";
const element = select("body").append("div").html("hello");
element.style("color", "red").transition().style("color", "green");
~~~

then ran `npx webpack`
~~~
main.js  38.1 KiB       0  [emitted]  main
Entrypoint main = main.js
[30] ./src/index.js + 115 modules 123 KiB {0} [built]
     | ./src/index.js 166 bytes [built]
     |     + 115 hidden modules
    + 424 hidden modules
~~~
The resulting page says hello in red then transitions to green. 


Then I manually edited node_modules/d3/package.json to add sideEffects: false, and ran webpack again. This time the resulting page says hello in red, then errors with  `t.style(...).transition is not a function`

~~~
[5] ./node_modules/d3-selection/src/selection/index.js + 37 modules 23.4 KiB {0} [built]
    |    38 modules
[8] ./src/index.js 166 bytes {0} [built]
    + 501 hidden modules
~~~

**Comment by tuuling** [comment]
> Hey @TheLarkInn, I know it took me a few years, but I’ve finally marked all the D3 modules as sideEffects: false (or sideEffects: true as appropriate). But I still am not clear on whether to mark the `d3` package itself as sideEffects: false: if `d3` imports a package with a side-effect, does that mean that I should set sideEffects: true on `d3`, or not?

My guess is that it is `sideEffects: true `.

But anyone who wants to optimise their build will then import from the specific module they need. Stuff like "d3-transition" is a problem tho. I have to `import { transition } from 'd3-transition';` to get stuff like @Fil did to work. That's bad because I am not even using the function I am importing directly.

**Comment by stof** [comment]
@tuuling you need to `import 'd3-transition';`, as that package has a side-effect of defining the `.transition()` method on the selection

**Comment by tuuling** [comment]
@stof Yeah, I know. I guess I wasn't clear as to what I was trying to say, sry.

So what I do is include d3 as a dependency in package.json:
`"d3": "^6.2.0"`
But in my code I import only from the modules I need:
```
import { scaleLinear } from 'd3-scale';
import { axisRight } from 'd3-axis';
import { sum as d3sum, bisector } from 'd3-array';
```
That way my package only includes what I really need and I don't need to micromanage my package.json. So it's fine if the main d3 package has sideEffects: true;

UNLESS I want to use d3-transition like this:
`select(...).transition()`
I then have to import transition like you said `import 'd3-transition';` which works fine, but is different from how you import everything else. Plus my IDE can't do it's magic and does not know I have to import it.

I guess my problem is more about d3-transition and the way it's structured. I have not used all the d3 modules, but I think it's is the only one that works by extending another module?

**Comment by stof** [comment]
@tuuling I reviewed all d3 packages 1 year ago to open PRs adding `sideEffects: false` (now almost all merged). And `d3-transition` is indeed the only one being designed based on a side effect. When opening my PRs, I excluded `d3-zoom` and `d3-brush` as well, but that's because they import `d3-transition` (and so inherit its side effect).
So I agree with you that this is an unfortunate architectural choice in `d3-transition` (but that choice was before in earlier days than the focus on tree-shaking AFAICT)

**Comment by jarrettmeyer** [comment]
You can always `.call` transitions if you want to get rid of side effects. I frequently find myself writing code like..

```
circles = circles
  .call(circles => 
    circles.transition().whatever()
  )
```

to make typescript happy, instead of calling `.transition()` directly on the selection. Obviously, that would be an enormous breaking change, tho.

**Comment by tuuling** [comment]
> You can always `.call` transitions if you want to get rid of side effects. I frequently find myself writing code like..
> 
> ```
> circles = circles
>   .call(circles => 
>     circles.transition().whatever()
>   )
> ```
> 
> to make typescript happy, instead of calling `.transition()` directly on the selection. Obviously, that would be an enormous breaking change, tho.

It's almost like d3-transition is designed opposite to everything else. 

Most modules create a behaviour and then you attach to a selection (drag, zoom, axis). For example
`d3.selectAll(".node").call(d3.drag().on("start", started));` Not `d3.selectAll(".node").drag().on("start", started);`

But changing d3-transition would be a major braking change for a benefit many people won't notice or care about.

**Comment by mbostock** [comment]
Closing because I don’t think there’s any additional work here slash I’m not sure what else there is to do. But feel free to comment or open a PR if there is.
