### ISSUE TITLE
the line is repainted in d3.js

### ISSUE THREAD

**Issue by YeisonVelez11** [d3/d3#3144]
Maybe it's not the medium, but I want you to help me with this.

I'm trying to draw a line based on a few points that come with the help of a setinterval, I'm passing the points one at a time but I could also pass several. for now I want the points of the line to be drawn one at a time but without re-drawing those that have already been drawn. How can I solve this problem ?

http://plnkr.co/edit/JjIiqrf97Y8K7YUJRodo?p=preview

      var path=g.selectAll(".line1")
      .data(data)
        .enter()
        .append("path")
        .attr("class", "line1")
        .attr("d", function(d,i) { return (line(data)); })
        .style("stroke", function(d) { return "brown" });

 in my real problem, I will receive points in real time that is why I am practicing how to draw point to point and generate an animation
https://i.stack.imgur.com/Xr5Lv.jpg

**Comment by mbostock** [comment]
One related technique for simulating a line being drawn is to animate the stroke-dasharray property; see my [Stroke Dash Interpolation example](https://bl.ocks.org/mbostock/5649592). But, this would still require re-drawing the whole line whenever the data changes. 

The only way to avoid re-drawing the whole line is to draw individual line segments for just the new data. Rather than replacing your entire line, just add a new line representing the new segments. If you are using [d3.curveLinear](https://github.com/d3/d3-shape/blob/master/README.md#curveLinear) this should “just work”. If you are using a fancier curve then you will have to deal with the discontinuities.

If you have a lot of points (like say more than fifty thousand), then you probably won’t want to create a path element in the DOM for each line segment for performance reasons. One very performant solution, albeit one that is a lot of work to implement, would be to use Canvas, and then just draw the new line segments as the data comes in, reusing the canvas so that the old line segments are still visible without you needing to redraw them. You can use [*line*.context](https://github.com/d3/d3-shape/blob/master/README.md#line_context) to render a d3.line to canvas.

If you want further advice, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
