### ISSUE TITLE
There is possible bug in `d3_svg_axisX` method

### ISSUE THREAD

**Issue by fortooon** [d3/d3#3151]
When we use big numbers in data to create histogram by d3.js (v3.5.5) error appears :
> Error: <rect> attribute transform: Expected number, "translate(1e+39,40)".

So after read source code I have some question :
 Is check `isFinite()` legally to validate argument for SVG 'translate()' in 
[in this line](https://github.com/d3/d3/blob/78ce531f79e82275fe50f975e784ee2be097226b/src/svg/axis.js#L155) ?

Maybe we need check whether it is [**octaword**](https://en.wikipedia.org/wiki/Integer_(computer_science)#Common_integral_data_types) ? Because `translate(1e+38)` works fine, but `translate(1e+39)` failed?
If there is a really problem, was it fixed in version 4, or Is it possible to fix this in the current version?

**Comment by razh** [comment]
You've reached the maximum single-precision floating-point value:

> (2 − 2<sup>−23</sup>) × 2<sup>127</sup> ≈ 3.402823 × 10<sup>38</sup>

https://en.wikipedia.org/wiki/Single-precision_floating-point_format

You can see this issue with these example SVGs:

### Valid

```xml
<svg>
  <g transform="translate(3.402823e+38,0)"></g>
</svg>
```

### Invalid

```xml
<svg>
  <g transform="translate(3.402824e+38,0)"></g>
</svg>
```

**Comment by mbostock** [comment]
If you want me to investigate, please post a live example to reproduce the issue; I can’t speculate as to the cause of this issue from the error message alone. It looks like the scale you are using in conjunction with the axis is returning unreasonably large values. Any value equal or higher than 1e21 (or smaller than 1e-6) will be formatted using exponential notation. If I recall correctly, older browsers didn’t always support parsing exponential notation, but I can’t remember if that problem applied to SVG or CSS. In any case, you probably want to investigate how your scale domains and ranges are defined, and which values you are passing to them; you should also be careful to avoid defining a log scale with a domain that crosses zero, passing zero to a log scale, or trying to transition the axis from a log scale to a non-log scale.

When reporting an issue, please include a link to a live example, preferably on [bl.ocks.org](http://bl.ocks.org) or [RunKit](https://runkit.com/npm/d3), or as a pull request in the [appropriate repository](https://github.com/d3) with new unit tests, that demonstrates that the described behavior is not the [expected behavior](https://github.com/d3/d3/blob/master/API.md). Use only the minimum amount of code necessary to reproduce the unexpected behavior.

A good bug report should **isolate specific methods** that exhibit unexpected behavior and precisely define how expectations were violated. What did you expect the method or methods to do, and how did the observed behavior differ? The more precisely you isolate the issue, the faster I can investigate.

Non-actionable bugs may be temporarily closed until you provide additional information. If you can’t isolate the bug any further, please let me know and I will try to help. However, I beg your patience: I must balance your request against many other responsibilities—fixing other bugs, answering other questions, new features, new documentation, *etc.* Please also consider asking for help on [Stack Overflow](https://stackoverflow.com/tags/d3.js).

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by fortooon** [comment]
http://jsfiddle.net/fortooon/q5fyae9c/
there is you can see in this live example error in console like in my case.
Please help, how I can avoid it or may be it is a really bug inside d3.js

**Comment by Fil** [comment]
You might use `tickFormat` ([documentation](https://github.com/d3/d3-3.x-api-reference/blob/master/SVG-Axes.md#tickFormat)):
```
var xAxis = d3.svg.axis()
  .scale(x)
  .tickFormat(d3.format(",.0e"))
  .orient("bottom");
```

**Comment by mbostock** [comment]
This doesn’t appear in 4.x, but it’s somewhat of a coincidence given that the ticks are now offset by a half-pixel (https://github.com/d3/d3-axis/commit/95e3f54d2655c0d0b99297c63dc2202cdb0b7d67).

The trigger is that the value returned by the scale for is very-nearly but not exactly zero, and thus is formatted in exponential notation with a large negative exponent (9.2e-48), which Chrome then considers as invalid SVG. However, this is a browser bug, because the [SVG specification](https://www.w3.org/TR/SVG/coords.html#TransformAttribute) documents that exponential notation is valid for transforms and paths, and indeed it is for other exponents such as 9.2e4. (D3 is not a compatibility layer.)

Here are a few ways to avoid the problem:

* Ensure that your range doesn’t include zero. For example, if you use the newer margin convention where the scale range is [margin.left, width - margin.right], and margin.left is positive, the range won’t cross zero so you won’t be at risk of producing a near-zero value.

* Enable rounding, *e.g.*, [scale.rangeRound](https://github.com/d3/d3-scale/blob/master/README.md#continuous_rangeRound).

Here’s an example:

https://bl.ocks.org/mbostock/23c6093cc6f9c8ef50d630f80a054d42
