### ISSUE TITLE
e6 modules: 82 malformed imports

### ISSUE THREAD

**Issue by backspaces** [d3/d3#3255]
While looking into use of D3 as imports to modules, I ran into errors. These seem to be related to imports that are malformed, found by a project search using this RegEx: `import.*from .[^./]` in the atom editor.  See below.

I will get better details shortly, but I just wanted to make sure these imports are indeed an issue.

Specifically, I think:
> import {dispatch} from "d3-dispatch";

.. should be a path to a d3dispatch module or to the specific dispatch.js file.

![snap 01 28 18-17 39 51](https://user-images.githubusercontent.com/124366/35494164-e7cca40c-0475-11e8-8df0-edb95b4d1812.jpg)

**Comment by mbostock** [comment]
The D3 modules use bare imports so that the module loader can resolve using the package.json. You’ll need an environment that supports bare module specifiers if you want to load the ES modules directly. For example, you can use Rollup to bundle the D3 modules as an ES module (in a single file), or you can use [unpkg.com ?module](https://unpkg.com) which rewrites bare imports.

**Comment by backspaces** [comment]
I *really* want to thank you! Es6 modules are so important and these insights are fabulous. As is an eye-opener on a 30 sub-repo repo.
