### ISSUE TITLE
Update License Year

### ISSUE THREAD

**Issue by reviewher** [d3/d3#3277]
To solve the problem once and for all, you can just use present, as is done with [React](https://github.com/facebook/react/blob/master/LICENSE#L3):

> Copyright (c) 2013-present, Facebook, Inc.

**Comment by Loksly** [comment]
This must be exhausting for you.

I've watched this repo for so many months and most of the issues are too poor in content.
Too many people worried about the year: #3277 #3259 #3170 #3172  
Too many questions about v3 and v4 compatibility.
So many bots that report an issue without really content.
So many questions that should be made in StackOverflow instead of reported.
@mbostock , nobody will blame you if you write a bot that closes every issue every time it gets opened.

Good luck, and thanks for d3.

**Comment by reviewher** [comment]
@Loksly one of the reasons people point out the license issue is that it is the first thing they check.  [In some environments like Google, projects using licenses like AGPL are a no-go](https://opensource.google.com/docs/using/agpl-policy/), and it's a good habit to check the licensing before investing time in a project.  I understand that it may seem to be a trivial issue to you, but when you have to get something cleared by the legal department you always check the licensing.

@mbostock we are all deeply appreciative of your work on d3.  Other popular projects like https://github.com/facebook/react addressed the problem years ago by using a year-agnostic copyright message (https://github.com/facebook/react/commit/bef45b0b1a98ea9b472ba664d955a039cf2f8068#diff-9879d6db96fd29134fc802214163b95a is from end of 2015), and such a fix would have obviated this issue and the ones enumerated in @Loksly's reply.

**Comment by Loksly** [comment]
@reviewher sorry, I didn't mean to offend you or your issue. My comment was more related to the thing that the most of the issue are not really bugs. Sorry again.

**Comment by reviewher** [comment]
@Loksly no offense was taken.  Your first comment suggested that you, like so many people in the space, might have had a lackadaisical view regarding licensing.  With the stated background in mind, hopefully you can see why people would actually look at the license text.
