### ISSUE TITLE
d3js.org has several broken example links.

### ISSUE THREAD

**Issue by tatsujb** [d3/d3#3286]
the main page : https://d3js.org/

has beehive alveolas of examples usages on diverse sites but some of the examples have ceased to be hosted by the sites. here are some examples : 

http://www.nytimes.com/interactive/2012/11/30/us/tax-burden.html
https://www.theguardian.com/info/2017/feb/05/removed-interactive

**Comment by zzyou** [comment]
Hi,
I would like to work on these links~
Is this issue still open?
Thanks!

**Comment by tatsujb** [comment]
yeah :)

**Comment by mbostock** [comment]
Thanks for the report. I’ll try to fix these soon. My immediate problem is that I can’t recall how to update the thumbnail montage used by the examples, so it’s a pain to update the example links.

**Comment by Kaszanas** [comment]
Found yet another broken example @mbostock 
"Deep Learning Snake Game"
https://deep-snake.herokuapp.com/
I had really high hopes for that one :D

**Comment by StoneCypher** [comment]
When you remember how to make the thumbnail, let me know and I'll wrap it up in a github action for you, so that it can be perma-forgotten 😄

**Comment by scottosmith** [comment]
Any progress on updating the thumbnail montage or help needed to make some progress?

**Comment by curran** [comment]
I just clicked all the current links. These are the only broken ones I saw:

 * https://www.jasondavies.com/maps/raster/ (map does not show up)
 * https://www.chronicle.com/article/women-as-academic-authors-1665-2010/ (behind a paywall or something)

**Comment by Fil** [comment]
- the raster maps are much modernized in e.g. https://observablehq.com/@jjhembd/robust-raster-reprojection
- the chronicle links work for me.

with this notebook https://observablehq.com/d/e8c334b5ff9cdbca I was able to recreate the  montage and update three links in https://github.com/d3/d3.github.com/commit/a9196e69b76fb9681251774295424de9876da17e ; can do more updates as needed—as a stop-gap measure, but it would be much nicer to go back to [the original format](https://github.com/d3/d3.github.com/commit/cabeca40be061ae8a4ae582d599b05929bd8b3b9), but do it with JS rather than a clunky gm montage :)

**Comment by mbostock** [comment]
We are in the process of redesigning the website and will remove broken links. Folding into #3655.
