### ISSUE TITLE
The radius of circles in pack layout is not strictly sorted by value attribute

### ISSUE THREAD

**Issue by Frag17** [d3/d3#3290]
I was making a pack view to represent a hierarchical relationship(a tree). Each node has a size attribute.
I suppose the radius of circles is related to its size. But I found two of these circles of the same parent does not meet it.
To some reason, I can't upload image so I will try to describe it by words.
There is one node we call it 0712. Its value is 23. Its radius is 0.100.
Another is called 0701. Its value is 14. Its radius is 0.110.
All the other circles is ranged by its value except these two. 0712 should be much larger than 0701.
I can sure the value attribute is calculated right, so there must be something wrong in the pack function.
Is cicle's radius not strictly related to its value?

**Comment by mbostock** [comment]
Are you sure you aren’t comparing the radius of nodes at different levels of the hierarchy? Siblings are always sized exactly proportional to their value (radius to the square root of the value).

When reporting an issue, please include a link to a live example, preferably as an [Observable notebook](https://beta.observablehq.com) or as a pull request in the [appropriate repository](https://github.com/d3) with tests. You should demonstrate that the described behavior is not the [expected behavior](https://github.com/d3/d3/blob/master/API.md) using the minimum amount of code.

A good bug report should **isolate specific methods** that exhibit unexpected behavior and define precisely how expectations were violated. What did you expect the method or methods to do, and how did the observed behavior differ? By isolating the issue, you assist the investigation.

Non-actionable bugs may be closed until you provide additional information. If you can’t isolate the bug further, please reply and ask for help. However, please be patient: open-source maintainers have many competing responsibilities—fixing other bugs, answering questions, developing features, writing documentation, *etc.* Please also consider asking for help on [Stack Overflow](https://stackoverflow.com/tags/d3.js).

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
