### ISSUE TITLE
D3 v5.9.7 missing d3-scale

### ISSUE THREAD

**Issue by cfremgen** [d3/d3#3341]
`Can't resolve 'd3-scale'` when importing in to Angular 8 project.

let d3_scale: any = require('d3-scale');

Downgrading to v5.9.6 still works

**Comment by mbostock** [comment]
d3-scale is a different package than d3, so if you installed d3, I wouldn’t expect you’d be able to require d3-scale; you need to install the latter separately. Otherwise, if you’d like me to investigate further, please post something that reproduces this error as I would otherwise find it difficult to investigate. Thank you.
