### ISSUE TITLE
Touchpad zoom in v5.9.7 is not working.

### ISSUE THREAD

**Issue by hariroshan** [d3/d3#3342]
Hello, I added d3 from npm package installer to my project. When I tried to zoom using touchpad with 2 fingers, the zoom is not listening. Although when I double click, the zoom listener is working.
I tried to test this in JSBIN using this  _https://d3js.org/d3.v5.min.js_  which is the same version but it works in JSBIN. Is there a bug in npm version?. Does anybody have this bug?. I also tried to create a new project just to test zoom. It isn't working in it as well.

**Comment by mbostock** [comment]
When reporting an issue, please include a link to a live example, preferably as an [Observable notebook](https://beta.observablehq.com) or as a pull request in the [appropriate repository](https://github.com/d3) with tests. You should demonstrate that the described behavior is not the [expected behavior](https://github.com/d3/d3/blob/master/API.md) using the minimum amount of code.

A good bug report should **isolate specific methods** that exhibit unexpected behavior and define precisely how expectations were violated. What did you expect the method or methods to do, and how did the observed behavior differ? By isolating the issue, you assist the investigation.

Non-actionable bugs may be closed until you provide additional information. If you can’t isolate the bug further, please reply and ask for help. However, please be patient: open-source maintainers have many competing responsibilities—fixing other bugs, answering questions, developing features, writing documentation, *etc.* Please also consider asking for help on [Stack Overflow](https://stackoverflow.com/tags/d3.js).

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
