### ISSUE TITLE
TickFormat type error

### ISSUE THREAD

**Issue by syedaatif** [d3/d3#3357]
Hi , 
On most recent deployment(2days ago) were getting following error.
We suspect this could be due to latest update of d3 or one of its internal dependencies. This happens only in production.
TypeError: Object(...) is not a function
    at Fx (main.0208b4faad4fd850fb0e.js:1)
    at Function.t.tickFormat.

We are having a angular 6 application.
Have attached screenshots of our build pipeline and error message.
Following are our packages from package.json pertaining to d3.
"d3": "5.7.0",
    "d3-color": "1.3.0",
    "d3-time-format": "2.1.3",
    "d3-scale": "3.1.0"
Screenshots of error and buildpipeline attached.
[
![typeerror](https://user-images.githubusercontent.com/24632276/69339300-03164500-0c8b-11ea-8f13-4a3a322ee4d1.PNG)
![buildPipeline](https://user-images.githubusercontent.com/24632276/69339335-17f2d880-0c8b-11ea-8229-0d5bb16b2ba2.PNG)

](url)

in local , all charts load fine and no error is observed.

**Comment by mbostock** [comment]
Sorry, but this isn’t enough information for me to investigate. I’d need a live reproduction (running code) in order to help identify what’s happening here. It looks like you’ve pinned the exact versions of the D3 modules you are using, but I would investigate changes to your yarn.lock or package-lock.json file to see what happened here when you updated your code.

I’ll also note that Angular’s optimizer is [known to break code](https://github.com/angular/angular-cli/issues/11439), and they don’t appear to have plans to fix this behavior. This has affected other D3 libraries (e.g., https://github.com/d3/d3-color/issues/68#issuecomment-537147753), and may be the cause of what’s happening here.

**Comment by Nagaraju-Pateti** [comment]
@syedaatif , u got any solution for this issue?

**Comment by syedaatif** [comment]
Hi @Nagaraju-Pateti . Not at the moment. As of now we've disabled angulars build optimisation as a temporary fix until we find a solution.
