### ISSUE TITLE
Replace var with let or const as appropriate.

### ISSUE THREAD

**Issue by curran** [d3/d3#3435]
I'm curious, what the stance is in terms of adopting `let` and `const` in this repo?

Possible approaches:
 * Consistently ES5 (`var` only)
 * Consistently ES6 (e.g. would a PR be welcome that converts all `var` to `let` & `const`?)
 * Allow internal inconsistency (mixed `var`, `let`, `const` within & between files)

This relates to how PRs should be reviewed with respect to usage of these keywords. Thanks!

**Comment by curran** [comment]
Let's `lebab` `d3/d3-*/**/*.js`!

Here's a question: would PRs be welcome that just migrate individual files to ES6?

Maybe one file (or few files) at a time is the safest way to do it.

**Comment by mbostock** [comment]
It’s not a goal at this time to rewrite everything. We’re focused on getting 6.0 released.

**Comment by Fil** [comment]
@domoritz has done the manual work of replacing `var` declarations with the appropriate `const` and `let` for d3-scale (https://github.com/d3/d3-scale/pull/212). One issue is that the resulting (compressed) file size has increased by 1%.

**Comment by domoritz** [comment]
Is the 1% more after or before gzip compression? 

To me, 1% more is a good trade off for safer code. Also, you could run Babel over the code to remove the let/const in the released code.

**Comment by Fil** [comment]
Ah, right! I had measured the minified's size—but you're correct that what we should measure is the gzip'ed minified: then it's not even 1%, but 0.4% "heavier" 👍

**Comment by domoritz** [comment]
Great. To me, that's within the noise.

**Comment by anlexN** [comment]
please rewrite d3 in es2015+ syntax

**Comment by curran** [comment]
lol PRs welcome.

**Comment by domoritz** [comment]
I sent one here: https://github.com/d3/d3-scale/pull/212 ;-)

**Comment by curran** [comment]
I think it makes sense to use ES6 in the documentation sample code provided in the README for all D3 packages.

**Comment by mbostock** [comment]
The eventual goal is to replace var with let or const, to adopt arrow functions, and otherwise to adopt ES2015+ language features as appropriate. For D3 6.0 we focused on the user-visible aspects of this (namely supporting iterables, and encouraging the use of arrow functions as event listeners). Eventually it’d be nice to update the internals as well, but I’m a little wary of churn and have plenty of other stuff to work on that I think is more pressing.

**Comment by domoritz** [comment]
@lgrammel has been working on a bot that could automate a lot of the work.

**Comment by Fil** [comment]
My experiment with lebab was quite positive, too, so I believe a bot could do the work without creating too many new issues by itself.
However note we currently have 138 pull-requests open throughout the D3 project, and a large change like this might impact every single one of them, creating random conflicts. I'd rather we spend our collective time on evaluating, rejecting and merging those PRs.

**Comment by lgrammel** [comment]
I'd love to help with the adoption of new ES2015+ language features. I could tune/modify the bot ( https://p42.ai/ ) to fit the needs of D3 exactly, so all you'd need to do would be to generate/review bot pull requests.

**Comment by domoritz** [comment]
The final decision is with you of course. I just wanted to share my experience.

Consistent code style (e.g. through automatic formatting) and splitting variable declarations (from one line for multiple declarations to one line per variable) could reduce churn in the long run. We had pretty good experiences with Prettier+ESlint in the Vega project where formatting reduced the number of conflicts (and updating prs with the right format is straight forward as well). Automated formatting also reduced our burden as reviewers of external prs since we didn't have to ask for style changes anymore.

**Comment by Fil** [comment]
If there's a way to upgrade the PRs, that objection vanishes. I am totally sold on the benefits of using ES6 and prettier throughout. But I think Mike doesn't like prettier as much as I do.

**Comment by d9j** [comment]
i know it's off topic. but want to thank you guys for this library. literally saved  my ass. few times.. using it in combination with other  chart libraries.. using d3js for customization of third party vendors svg graphs where api for customization is not provided by vendors

**Comment by mbostock** [comment]
We don’t have any immediate plans to do this, and don’t need a tracking issue for it. Maybe we’ll do it eventually.
