### ISSUE TITLE
Provide esm download

### ISSUE THREAD

**Issue by dronus** [d3/d3#3597]
It's cumbersome to bring up a whole npm based environment just to bundle d3 into an esm module.
The CDN releases on the other hand can't be downloaded into a single file easily (strange import indirections).

So would be good to provide a default single-file ESM distribution. Or a multi-file .mjs tree.

As the README states, "D3 is written using ES2015 modules" - but the npm packages contain legacy modules.

**Comment by mbostock** [comment]
ES modules are already published to npm and exposed as the default export. You can access them on the CDN like so:

https://cdn.jsdelivr.net/npm/d3-array/src/index.js

We don’t provide a single-file ES module for each package because cross-package dependencies require bare specifiers, e.g.,

https://cdn.jsdelivr.net/npm/d3/src/index.js

There isn’t really a way to publish single-file ES modules with dependencies that work out-of-the-box in web browsers on a CDN. Either users would be required to specify [import maps](https://html.spec.whatwg.org/multipage/webappapis.html#import-maps) (user burden, and unsure about browser support), or the published files would have to use relative paths or absolute URLs, which would cause problems in Node.

Given these challenges and the lack of a convention (other than the ones already used by D3), I don’t think it should be D3’s responsibility to implement bundling. If you want a pre-built bundle, I recommend using one of the existing ESM CDN bundlers such as Skypack or jsDelivr’s esm.run. Try one of these:

https://cdn.jsdelivr.net/npm/d3@7/+esm
https://cdn.skypack.dev/d3@7

**Comment by dronus** [comment]
But neither of these methods provide an easy path to have the **files** needed to ship or host d3.js without the use of an extensive build system cumbersome to understand and get a build out of it. 
Neither jsdelivr nor skypack provide something I can donwload, put into my codebase (or onto my server) and give it a go, or could I? 

I've actually ended with reconverting a downloaded single file CommonJS build into ESM format again (needing some manual operations to get it working).

**Comment by yurivish** [comment]
One service that provides bundled ES modules is esm.sh: https://esm.sh/d3@7.9.0/es2022/d3.bundle.mjs
