### ISSUE TITLE
scale.ticks(maxCount)

### ISSUE THREAD

**Issue by pekeler** [d3/d3#490]
I wish the count argument for ticks was interpreted as maxCount instead of suggestedCount.

Example: I'm using a time.scale for my x-axis and I'm not in control of the domain. But I know that on my range or width, I can render a maximum of 6 date labels before they start overlapping. I've seen ticks(count) returning twice the provided count, suggesting I should use ticks(3) but then I sometimes end up with just one tick (which is bad - the user needs to see at least 2 ticks to make sense of the scale).

**Comment by yshahin** [comment]
Any clarification on this point? Some spec for the feature and if possible test case examples so that someone can implement it.
or is it not needed any more, this bug is from 2012

**Comment by eric-poitras** [comment]
Exactly the same problem here. I know the space available and the current implementation of the suggestedCount creates a lot of overlap of date labels on some x-axis.

**Comment by swergas** [comment]
I also experience the problem of overlaping tick names quite often (because minimal spacing it not guaranteed).
![unnamed](https://cloud.githubusercontent.com/assets/733425/7137977/9cabc5f2-e2bd-11e4-9228-337795d59832.png)
![capture du 2015-04-14 15 35 53 copie](https://cloud.githubusercontent.com/assets/733425/7138051/ef575b5e-e2bd-11e4-9e91-ea5b814b2d9f.png)
