### ISSUE TITLE
influence on easing functions?

### ISSUE THREAD

**Issue by janwillemtulp** [d3/d3#76]
Hi Mike,

is there a way to have some influence on the easing functions being used? For instance, right now I have some small experiment where I use the elastic easing function. Is there for instance a way to increase the amplitude? 

Thanks!

**Comment by jkuntorov** [comment]
Hey guys, I have a very weird problem whilst using the `ease("elastic", a, p)` function. I am transitioning the radius of circles and I'm getting a flood of errors in the console, which are significantly slowing down my webpage. The errors state that I'm setting a negative radius — after some debugging (from console logging everything to diffs with previous code) I found out that's caused by the `elastic` easing. Here's my code:

```
function redraw() {
	var day = d3.select('input[name="day"]:checked').node().value;
	var time = d3.select('input[type="range"]').node().value.toString();
	var direction = d3.select('input[name="direction"]:checked').node().value;

	// fix bug in which data for single digit hours is not displayed
	if (time.length == 1) {time = "0" + time;}

	if (circles !== undefined) {
		circles.transition().duration(900).ease('elastic', 1, 0.75).attr({
			fill: function(d) {
				return shadeColor("#ff0000", (-1 * getCircleSize(d.data, day, time, direction)));
			},
			r: function(d) {
				var size = getCircleSize(d.data, day, time, direction);

				if (size > 0 && size < 2) {
					return size + 2;
				} else if (size > 50) {
					return size*0.1 + 50;
				} else {
					return size;
				}
			}
		});
	}
}
```
And here is an example of the error I'm getting:
```
Error: Invalid negative value for <circle> attribute r="-0.04404809159933931"
(anonymous function)
@ d3.v3.min.js:5l
@ d3.v3.min.js:3Lt
@ d3.v3.min.js:1qt
@ d3.v3.min.js:1
```

If I change the line:
```
circles.transition().duration(900).ease('elastic', 1, 0.75).attr({...});
```
to:
```
circles.transition().duration(900).ease('quad').attr({...});
```
...it doesn't spit out any errors in the console.

Here's a screenshot as well:
![d3-elastic-bug](https://cloud.githubusercontent.com/assets/4628273/7569592/aada56ee-f801-11e4-8385-e97853bf628b.png)

It would be great if you can give me some guidance on how to solve this problem. Thanks in advance!
